### ISSUE TITLE
Use the new MSIX installation format

### ISSUE THREAD

**Issue by manuelelucchi** [felixse/FluentTerminal#10]
Hi, I've seen that you have in the roadmap to make an msi package. I'm my opinion that would be a waste of time since Microsoft recently announced a new format that combines the best of both .msi and .appx, the .msix. Could you please do the installer with this format? You would be one of the firsts to do it.
Link to the msix repository: https://github.com/Microsoft/msix-packaging

Regards,
Manuele

**Comment by felixse** [comment]
I had a look at this as well, but I don't think it will help with what I am trying to achieve. I don't want to replace the .appx with a .msi, but wrap it into one which also handles the certification registration, enabling sideloading and adds the registry keys for the context menu integration. 

Also I am making good progress on the .msi thanks to this https://github.com/aL3891/AppxInstaller
