### ISSUE TITLE
[Feature request] Auto download/extract/open updates

### ISSUE THREAD

**Issue by KaKi87** [felixse/FluentTerminal#1002]
Hello,

When receiving a notification from FluentTerminal offering to open GitHub releases when a new update is published, I often ignore it because I'm lazy to :
- download the latest ZIP
- extract the APPX
- install the APPX
- delete the APPX
- delete the ZIP

However, I would be more motivated to perform the update if the app would automatically download and extract it before notifying me, and automatically open the APPX when clicking the notification.

Thanks

**Comment by KaKi87** [comment]
Using the Windows Store requires creating a Microsoft account, which I do not want to.

**Comment by felixse** [comment]
I'm not planning on implementing an updater since there are already enough ways of distribution, sorry.

**Comment by KaKi87** [comment]
In that case, how to disable update notifications ?
