### ISSUE TITLE
Resizing the window makes you unable to type

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#101]
If I launch FT, maximize the window, then restore it, I am no longer able to type into the terminal.  I've also noticed that resizing the windows in other ways will lead to the same issue.  For example, I use WinDock to set up zones on my display.  I can drag a window to an edge of the screen, and it'll snap to a specified size.  Doing this will sometimes lead to me being unable to type in the terminal. Opening a new tab will let me type in the new tab, but the old tab will have the same issue.

**Comment by felixse** [comment]
Sounds like some issue with resizing. I hope this will get better once we support conpty

**Comment by villasv** [comment]
Happens with me sometimes as well, but I think sometimes its not that I can't type, but what I'm typing isn't being displayed. If I hold `<Enter>` or send a `clear<Enter>`, I recover the terminal.

**Comment by mjs** [comment]
This might be largely fixed since #394 landed. Perhaps this issue can be closed now?
