### ISSUE TITLE
New Git Bash window after starting a Git Bash session

### ISSUE THREAD

**Issue by avocardio** [felixse/FluentTerminal#1011]
After adding the Git Bash path in FluentTerminal and starting this terminal, a new (git bash) window appears instead of displaying it in the FluentTerminal.

![Capture](https://user-images.githubusercontent.com/74978236/177569624-0898bc8d-a47d-48d9-8fb8-128cc3d7b1f8.PNG)

Or is the Git Bash path not correct? 

![Capture](https://user-images.githubusercontent.com/74978236/177570055-66cfff0f-144c-4ae3-921b-18b0c0534fb9.PNG)

**Comment by felixse** [comment]
Have a look at this issue: https://github.com/felixse/FluentTerminal/issues/255

**Comment by avocardio** [comment]
Thanks, it worked!
