### ISSUE TITLE
problem with font setting

### ISSUE THREAD

**Issue by MooRoakee** [felixse/FluentTerminal#1013]
It looks something wrong when i try to set font with fluent terminal. This font shows well in window terminal and other ide software
![图片](https://user-images.githubusercontent.com/25135228/179450384-93a34a1c-c13a-479a-98ed-655d0c095974.png)
fluent terminal version: 0.7.7

**Comment by hanskokx** [comment]
Duplicate of #233

**Comment by MooRoakee** [comment]
Thanks for replying though the font i used is mono font which is `JetBrainsMono-NF-Mono` installed through `scoop`. It's weird i try it on another computer with win11 that it displays correctly.

**Comment by MooRoakee** [comment]
Solving by installing font manually
