### ISSUE TITLE
Not all completed translations are mentioned in README.md

### ISSUE THREAD

**Issue by Ramin-RX7** [felixse/FluentTerminal#1026]
I was checking [POEditor](https://poeditor.com/join/project/TfKNIt826z) and noticed that there are several languages with complete translation are not added in README.md .  I wasn't sure if it was intentional so I opened this issue

**Comment by hanskokx** [comment]
Oooh, would you mind putting in a quick pull request to add those 
languages? Sometimes documentation gets forgotten when progress happens. 
Thanks for the find!
