### ISSUE TITLE
Transparency in background

### ISSUE THREAD

**Issue by sinnlosername** [felixse/FluentTerminal#104]
If I focus another window the transparency of the terminal will go away until I focus the terminal window the next time. I know this also happens for other fluent designs, however in the case of fluent terminal literally the entire window is transparent, so it's really distracting. It would be nice if you could somehow disable this

**Comment by felixse** [comment]
I'm afraid this is the default behaviour of the acrylic brushes in Windows 10. Nothing we can do on our side, maybe Microsoft changes its mind in the future.

**Comment by IgnusG** [comment]
Track progress here https://github.com/microsoft/microsoft-ui-xaml/issues/491

**Comment by KaKi87** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/491#issuecomment-871748206
Do you think you could so that on your end ?

**Comment by bottleof-water** [comment]
yea, it would look good
