### ISSUE TITLE
Resize let texture disappear

### ISSUE THREAD

**Issue by sinnlosername** [felixse/FluentTerminal#105]
If I resize my window bigger than it was on the start of the terminal it won't load anymore textures in the "new space".

Here's a video: https://streamable.com/6gdao

You can see the small blue border of the window both nothing inside it. 

After a restart it will show the entire terminal with the new size.

**Comment by felixse** [comment]
Ok, that looks strange. What version of Windows 10 are you using?

**Comment by sinnlosername** [comment]
I'm using the April Update (1803).

**Comment by felixse** [comment]
https://www.reddit.com/r/Windows10/comments/9e18t2/strange_bug_that_happens_when_resizing_uwp_apps/?st=JNREDGLL&sh=123e0238

Might this be your issue? Then it should be fixed with 1809

**Comment by sinnlosername** [comment]
Okay, but as far as I know 1809 isn't out yet, is it?

**Comment by felixse** [comment]
I think it has been rereleased or will be soon

**Comment by sinnlosername** [comment]
There are ISOs of it however I can't get it from windows update and I don't want to clean reinstall my pc. Is there maybe a workaround?

**Comment by skipmeister123** [comment]
I think you're looking for this.

https://support.microsoft.com/en-us/help/3159635/windows-10-update-assistant
--
Hans Kokx

**Comment by sinnlosername** [comment]
Unfortunately it's also only the tool for v1803.

**Comment by sinnlosername** [comment]
@Riebart Yea, I couldn't manage to get the update in the time it was public. Thanks for the tip with the reboot, Looks like we need to wait for 1809
