### ISSUE TITLE
Font weight

### ISSUE THREAD

**Issue by cjbdev** [felixse/FluentTerminal#109]
Is there a way to set font weight? I use Operator Mono, which comes in many weights. By default, Fluent Terminal defaults to medium weight, which looks really bad on my screen. Normally, I use the light weight version, but I don't see an option for that in Fluent Terminal.

**Comment by felixse** [comment]
Currently not, but xterm has an option 'fontweight', so this should be no big deal to add

**Comment by felixse** [comment]
Fixed with #183

**Comment by ericcornelissen** [comment]
Actually, #183 only allows you to toggle between "medium" (called "normal" in CSS) and "bold". This could be updated to include an option "light" using radio buttons rather than a toggle
