### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by sinnlosername** [felixse/FluentTerminal#110]
I got some trouble with line breaks. Bash on Windows (WSL) works with LF as it is a linux system, while the windows cmd works (afaik)´with CRLF.

If I copy a text from notepad with CRLF and paste it into fluentterm=>WSL it will do twice as much new lines. So for example

```
test1
test2
test3
```

will be pasted as 

```
test1

test2

test3

```

It would be nice to specify a linebreak per profile and convert pasted text to it. So if I specify "LF" for WSL and paste a text with "CRLF" it will replace all CRLF with LF.

**Comment by skipmeister123** [comment]
I see this when pasting into vim, too.
--
Hans Kokx

**Comment by Riebart** [comment]
I have this built in a branch, I could create a PR, and divorce it from my tab shortcut code.

**Comment by felixse** [comment]
@Riebart thanks for taking care of this 😄  I don't mind if it is in the same PR as tab shortcuts. How is your progress over there?

**Comment by Riebart** [comment]
Been crazy, haven't had a free evening in three weeks. But a bunch of stuff finished up this weekend, I should be able to polish up that pr this week,  thanks for you patience!

**Comment by felixse** [comment]
No worries, take your time 😃

**Comment by Riebart** [comment]
Ok I've got the shell shortcuts PR updated and passing tests. I'll put in the line breaks PR once that's accepted, since it builds on some of the changes to the profile settings page in the shell shortcuts PR.

My line break editing PR also comes with a new keyboard command, "Paste without newlines" which I found really helpful in Cmder, since the copy-paste wasn't always aware of when what I was copying was soft wrapping at the terminal edge, and would occasionally insert spurious line breaks. Also useful when copying from Powershell, as those are regularly hard-wrapped in the copied text.

**Comment by skipmeister123** [comment]
As long as you're running a relatively recent build, you'll get an update notification.  That's something that was implemented a couple builds ago.

--
Hans Kokx
On 11/7/2018 12:24:00 PM, Florian <notifications@github.com> wrote:
By the way, how do I know when a new update is available? Is there an update notification or do I need to check them manually?

**Comment by sinnlosername** [comment]
any updates

**Comment by sinnlosername** [comment]
Any news?

**Comment by Riebart** [comment]
Taking me a bit longer to rebase the changes, some of the code blocks have changed. Should be in this week. Sorry for the delay. 😸

**Comment by Riebart** [comment]
Does the PR address this issue? It was merged some time ago, so we might be able to close this.

**Comment by ivan-section-io** [comment]
> Does the PR address this issue? It was merged some time ago, so we might be able to close this.

Whilst either LF or CR will work in bash, more interactive console apps (e.g. nano) only recognise CR.

Released build supports LF - Good for Bash
Master supports CR - Good for everything

Let's close this issue.
