### ISSUE TITLE
App crashes when setting background opacity if windows transparency effects are not enabled

### ISSUE THREAD

**Issue by yourbuddypal** [felixse/FluentTerminal#112]
When the windows "Transparency Effects" are not enabled, using the application's "Background Opacity" slider causes the application to crash.  

Before successfully enabling the transparency, I was able to repro this crash 100% of the time.  When toggling the settings and restarting the application, I believe there are some startup crashes of the app before it reverts to being totally opaque.

**Comment by yourbuddypal** [comment]
Good call! That was on Windows 1709 at work. I just installed at home and tested and could not repro. I'll close the ticket, thanks for the fast reply!

**Comment by deathnopool** [comment]
same issue on 1809
