### ISSUE TITLE
Touchpad scrolling not working

### ISSUE THREAD

**Issue by moigagoo** [felixse/FluentTerminal#114]
Scrolling with mouse works but scrolling with touchpad doesn't. The entire content container gets pulled, not the content inside it.

**Comment by skipmeister123** [comment]
I meant to file this bug a long time ago.  Thank you for doing it for me 😅

--
Hans Kokx
On 11/6/2018 3:03:45 PM, Constantine Molchanov <notifications@github.com> wrote:
Scrolling with mouse works but scrolling with touchpad doesn't. The entire content container gets pulled, not the content inside it.

**Comment by ericcornelissen** [comment]
Interesting 🤔 For me scrolling with both touchpad and mouse works just fine...

**Comment by skipmeister123** [comment]
It depends on where I scroll.  If I scroll near the scrollbar, it works fine.  If I scroll in the middle of the terminal, it just drags the page a bit.

--
Hans Kokx
On 11/6/2018 3:37:35 PM, Eric Cornelissen <notifications@github.com> wrote:
Interesting 🤔 For me scrolling with both touchpad and mouse works just fine...

**Comment by ericcornelissen** [comment]
Even more interesting. For me it works everywhere, but I can't find any scrollbar 🤣

**Comment by skipmeister123** [comment]
![ezgif-1-a537c4d85c24](https://user-images.githubusercontent.com/1911919/48092909-ee7c2180-e1db-11e8-810d-6a3273455ae8.gif)

**Comment by felixse** [comment]
that's basically [this issue](https://github.com/xtermjs/xterm.js/issues/1007), right?

There are some files attached over there, maybe we can use them

**Comment by skipmeister123** [comment]
That sounds like it might be related, yeah.  I think we should look into it.

--
Hans Kokx
On 11/7/2018 1:13:39 AM, Felix <notifications@github.com> wrote:
that's basically this issue [https://github.com/xtermjs/xterm.js/issues/1007], right?
There are some files attached over there, maybe we can use them

**Comment by alex-slover** [comment]
I can confirm that touchpad scrolling works for me *only* if my cursor is on the far-right side of the window where the scroll bar would be, otherwise it is broken and scrolls the entire container. I'm on a device with a Windows Precision Touchpad, is it possible that's the difference between the people for whom it's working (since they probably have scroll events sent by the old-style PS/2 emulation) and the people for whom it's broken?

**Comment by skipmeister123** [comment]
Interesting theory. I'm sure my surface book 2 has one too.
--
Hans Kokx

**Comment by ynsgnr** [comment]
Scrolling with touch (on touchscreen) also has same bug
