### ISSUE TITLE
Allow installation to be made through chocolatey

### ISSUE THREAD

**Issue by afnpires** [felixse/FluentTerminal#119]
It would be nice to be able to install FluentTerminal through chocolatey.

**Comment by felixse** [comment]
We can look at this in context of #118. NuGetPackageExplorer is available through chocolatey, and we might be able to achieve similar deployment methods.

**Comment by pgalbraith** [comment]
I made a chocolatey package: https://chocolatey.org/packages/fluent-terminal

**Comment by pgalbraith** [comment]
@felixse email me if you would like to be added as a package maintainer on Chocolatey, I think it makes sense if you have the spare cycles :-)

**Comment by felixse** [comment]
I hardly get to maintain this repo, I don't think I would be of much use 😅
