### ISSUE TITLE
Keybindings: Allow Win key as modifier

### ISSUE THREAD

**Issue by moigagoo** [felixse/FluentTerminal#12]
Currently, you can't set shortcuts with Win key, e.g. Win + ` to toggle the window.

Of course, it's not a critical issue by far, but I'd still like to report it just in case.

**Comment by felixse** [comment]
I originally planned to support this key as well, but had some issues with it. Guess I will have another look at it this weekend, maybe I can find some way.

**Comment by felixse** [comment]
Configuring Win + ´  to toggle the window should work now, but xterm.js is not detecting the meta key correct, so I will keep this open until I found a solution to support the meta key in all keybindings
