### ISSUE TITLE
Weird color issues

### ISSUE THREAD

**Issue by ChristianSauer** [felixse/FluentTerminal#120]
Hello,
I am currently trying FluentTerminal and stumbled on a graphics issue:
![image](https://user-images.githubusercontent.com/7250249/48332500-4db2b980-e654-11e8-896c-89ddc6833003.png)

This happens only if the tab has focus, otherwise the colors appear normal.
This is a JetBrains Darcula.itermcolors theme, but this also happens with e.g. Glacier

**Comment by ChristianSauer** [comment]
I just realized the root cause is a semi transparent background...sorry! But I would love an option to use a non transparent background

**Comment by felixse** [comment]
You can set the background opacity to 1.0 in Settings -> Terminal
