### ISSUE TITLE
Just what I've been looking for!

### ISSUE THREAD

**Issue by patriksvensson** [felixse/FluentTerminal#122]
This is not an issue, but just wanted to tell you that **I really love this project**.

Keep up the good work!

**Comment by skipmeister123** [comment]
🤗
--
Hans Kokx

**Comment by felixse** [comment]
Glad you like it 😃  thanks for the kind words

**Comment by skipmeister123** [comment]
😍

--
Hans Kokx
On 12/6/2018 8:24:31 AM, SAURABH SHARMA <notifications@github.com> wrote:
Just came here to say thank you to you guys.
