### ISSUE TITLE
Global Hotkey?

### ISSUE THREAD

**Issue by dprice** [felixse/FluentTerminal#123]
I just found this app via Scott Hanselman's latest blog post and so far it's really solid. Besides the split window feature from ConEmu, the only other feature I'm missing is the global hotkey for the app. ConEmu defaults to ctrl+`. Is there anyway to do that for FluentTerminal?

Thanks,
Derek

**Comment by skipmeister123** [comment]
You can set the hotkey in Settings > Keybindings.  I think the default is [Scroll Lock].  I agree on the split window feature.  I've already filed a feature request for that.

--
Hans Kokx
On 11/12/2018 9:24:35 AM, Derek Price <notifications@github.com> wrote:
I just found this app via Scott Hanselman's latest blog post and so far it's really solid. Besides the split window feature from ConEmu, the only other feature I'm missing is the global hotkey for the app. ConEmu defaults to ctrl+`. Is there anyway to do that for FluentTerminal?
Thanks,
Derek

**Comment by dprice** [comment]
Oh man! I saw that was thinking about the scroll wheel! D'oh! Thanks for the fast reply!
