### ISSUE TITLE
ConPTY support

### ISSUE THREAD

**Issue by felixse** [felixse/FluentTerminal#128]
So 1809 is about to be rereleased and its time to work on some ConPTY awesomeness.
I created a branch `Dev/ConPty` where I started integrating it. Its based on @pingzing's [ModernPseudoSh](https://github.com/pingzing/ModernPseudoSh) (many kudos).

Todo:
- [x] Basic functionality
- [x] Resize
- [x] Handle shell exit
- [x] pass startup directory
- [x] hide backing console window
- [x] detect conPTY availability and fallback to winPTY if necessary
- [x] Communicate used pty to xterm.js so that we can enable the winPtyCompat addon if necessary
- [ ] Investigate if we can add an option to start the shell process with admin rights

So if someone feels like playing around with ConPTY feel free to grab a task 😄

**Comment by felixse** [comment]
![image](https://user-images.githubusercontent.com/30559812/48715041-5b4bde80-ec14-11e8-800b-ef3de2c50c68.png)
Don't ask me whats going on with color 243

**Comment by skipmeister123** [comment]
😲 Gimmie!

--
Hans Kokx
On 11/19/2018 10:03:19 AM, Felix <notifications@github.com> wrote:
[image] [https://user-images.githubusercontent.com/30559812/48715041-5b4bde80-ec14-11e8-800b-ef3de2c50c68.png]
Don't ask me whats going on with color 243

**Comment by parkovski** [comment]
>  Investigate if we can add an option to start the shell process with admin rights

I don't think you can do this easily. The most straightforward way is to use UAC to start an elevated broker process, as per [this issue](https://github.com/Microsoft/console/issues/332). To get an elevated child process requires tricks like I've been experimenting with [here](https://github.com/parkovski/wsudo). I've researched this a lot, and I'm always happy to discuss it or explore other options.

**Comment by david50407** [comment]
After enabling conPTY, I cannot pass `Ctrl-A` (or `Ctrl-<somekey>`) into the terminal (it is working with always use winpty chekced), that is, I cannot use key-binding with `screen` or other cli tools.

conPTY also caused scrolling text away in terminal when I changed the window of `screen`.

**Comment by DRSDavidSoft** [comment]
Awesome! 👍 Is it possible to include both ConPTY and WinPTY support in the project, and chose to load either at runtime?

---

Two off-topic questions, what color scheme and what kind of bash shell are you using in the screenshot? (WSL, Cygwin, MinGW or something else?)

**Comment by felixse** [comment]
> Awesome! 👍 Is it possible to include both ConPTY and WinPTY support in the project, and chose to load either at runtime?

Yes, the next version will have a configuration to switch between both (winpty by default, conpty is not quite ready yet).

> Two off-topic questions, what color scheme and what kind of bash shell are you using in the screenshot? (WSL, Cygwin, MinGW or something else?)

Thats' just an unaltered unbuntu 18.04 bash and [my configuration](https://github.com/felixse/FluentTerminal/wiki/FAQ#how-can-i-achieve-the-look-of-the-terminal-in-the-readme)

**Comment by mjs** [comment]
This can be closed now right? ConPTY is working quite well in the latest releases.
