### ISSUE TITLE
Allow passing custom CSS to terminal

### ISSUE THREAD

**Issue by moigagoo** [felixse/FluentTerminal#13]
One of huge benefits of XTerm.js is that you can use CSS to customize the output. It would be great to be able to customize the styles for themes in FluentTerminal.

For example, here's how Hyper—another XTerm.js-based terminal emulator—allows you to enable ligatures: https://github.com/zeit/hyper/issues/874

**Comment by felixse** [comment]
Good idea, I will add this for the next release

**Comment by moigagoo** [comment]
Hmm, weird, I could swear I successfully enabled ligatures in hyper, at least in some older version. Apparently, things got broken since then.

**Comment by felixse** [comment]
Do you see any further need for passing custom css now that xterm.js is basically a giant canvas?  I don't think there is much to gain from it right now, but if someone finds a case I will add the feature.

**Comment by moigagoo** [comment]
> Do you see any further need for passing custom css now that xterm.js is basically a giant canvas? 
For me, it was just the ligatures.
> I don't think there is much to gain from it right now,
Yep, I agree.

**Comment by felixse** [comment]
I am going to close this now. If someone has a case for custom css feel free to write here, then I will reopen this.
