### ISSUE TITLE
Clone profile

### ISSUE THREAD

**Issue by giggio** [felixse/FluentTerminal#132]
It would be nice to be able to clone a profile and then be able to extend it.

**Comment by giggio** [comment]
I just installed 0.3.0, but I can't find a way to clone a profile.

**Comment by skipmeister123** [comment]
There's a clone button at the top, now.

--
Hans Kokx
On 1/2/2019 5:31:40 PM, Giovanni Bassi <notifications@github.com> wrote:
I just installed 0.3.0, but I can't find a way to clone a profile.
