### ISSUE TITLE
Install1.ps Sideload Apps Error

### ISSUE THREAD

**Issue by Masken8** [felixse/FluentTerminal#134]
When i try to install FluentTerminal it tells me to enable Developer Mode or Sideload Apps and Sideload Apps is enabled but it says that Sideload Apps isn't enabled

**Comment by felixse** [comment]
What version of Windows 10 are you using? Did you also try the manual way as described in the readme?

**Comment by Masken8** [comment]
Manual install worked, Im running Windows 10 Home x64 Version 1803 and OS-version 17134.407

**Comment by gwojan** [comment]
> Manual install worked, Im running Windows 10 Home x64 Version 1803 and OS-version 17134.407

@felixse Is this why Windows 10 Fall Creators Update is listed as a prerequisite?

**Comment by sean-twie03** [comment]
I was able to reproduce this issue (FT Build 0.3.1.0 on Win10 1803).  During Install.ps1 I was prompted to select SideLoad Apps in the Developer Features Settings.  SideLoad was already selected.  I clicked "Developer Mode" which automatically installed a "Developer Package."  After that package installed, I was able to compete the FluentTerminal install as normal.

**Comment by sean-twie03** [comment]
On my 1803 machine, I had rebooted between selecting SideLoad (months ago) and running Install.ps1.  I did not reboot at any point during the FluentTerminal install.

I spun up a Win10 VM (1709) that has never installed the Developer Mode package, but I was unable to reproduce the issue a second time. I selected SideLoad, rebooted, and the app installed successfully.

**Comment by tblin** [comment]
I had the same issue on an 1809 machine. The registry entry you are parsing is simply not there.
hklm:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock is emtpy and I triple check that SideLoad was enabled in Settings.
