### ISSUE TITLE
Select specific profile when opening new tab

### ISSUE THREAD

**Issue by adammhaile** [felixse/FluentTerminal#135]
Maybe I'm completely blind, but how on earth do you open up a new tab to a specific profile? Seriously, all I can find at the moment is to go to settings and set the profile I want as default, then open the new tab.
What about being able to right-click on the new tab option and choose a profile?

**Comment by jonaskuske** [comment]
`Ctrl` + `Shift` + `T` does the trick.
See Settings > Key Bindings > Configurable new tab, you can change the shortcut there.

**Comment by Riebart** [comment]
There is a PR open that I am slowly working on to get merged that adds shortcuts to open a new tab with a specific profile.
