### ISSUE TITLE
error 0xC00CE015: App manifest validation error

### ISSUE THREAD

**Issue by abhishekgoenka** [felixse/FluentTerminal#136]
I am getting following error while installing
![image](https://user-images.githubusercontent.com/14522198/48670533-20c44200-eb3f-11e8-844c-654d48c91eb0.png)

**Comment by felixse** [comment]
Looks like your trying to install it on a system prior to Windows 10 1709. You need to update to Fall Creators Update or later to use this software.

**Comment by abhishekgoenka** [comment]
Well, then it should be documented in prerequisite. I have submitted a new PR #139

**Comment by felixse** [comment]
Yes, definitively. Thanks for the PR 👍
