### ISSUE TITLE
Alt+Enter causes a crash

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#138]
I keep trying to full-screen the app, and it keeps locking up every time I try it.  Seems to happen on all of my computers.

**Comment by felixse** [comment]
Does it go full screen and then crash? Or maybe something about the key bindings? I should really consider some crash reporting/analytics for the next version 🤔

**Comment by skipmeister123** [comment]
It doesn't crash, as far as I can tell.  Maybe it wants to, but usually I'm busy doing something so I end up force quitting it.

--
Hans Kokx
On 11/19/2018 5:19:05 AM, Felix <notifications@github.com> wrote:
Does it go full screen and then crash? Or maybe something about the key bindings? I should really consider some crash reporting/analytics for the next version 🤔

**Comment by felixse** [comment]
I think this got resolved in the meantime, please let me know if not
