### ISSUE TITLE
Install.ps1 doesn't register explorer integration properly

### ISSUE THREAD

**Issue by Drachenkaetzchen** [felixse/FluentTerminal#140]
Hi,

the explorer integration isn't properly registered in Install.ps1 - there is a double % sign (which is required in the batch scripts) but I believe not in the Install.ps1 script.

I ended up with the following registry entry:

`"C:\Users\Drachenkatze\AppData\Local\Microsoft\WindowsApps\flute.exe" new %%1`

After changing it to the following, it works:

`"C:\Users\Drachenkatze\AppData\Local\Microsoft\WindowsApps\flute.exe" new %1`

By the way, thank you so much for this wonderful terminal 💓 Do you maybe have a patreon where I can support this with a little bit of appreciation?

**Comment by felixse** [comment]
Yeah, looks like some copy&paste error. I will take care of this for the next release.

Thanks for your support, but I don't want to take any donations. Please give it to someone/something more in need 😃

**Comment by felixse** [comment]
Fixed with #145
