### ISSUE TITLE
System.Exception: ConnectNamedPipe Failed : Windows error 232 at FluentTerminal.SystemTray.Service......

### ISSUE THREAD

**Issue by iAmBipinPaul** [felixse/FluentTerminal#143]
![image](https://user-images.githubusercontent.com/9201481/48980314-71afd980-f0ef-11e8-8b66-6500a7a9b3b5.png)

**Comment by skipmeister123** [comment]
What are the steps to reproduce? What log messages are there? How many 
times has this happened?
--
Hans Kokx

**Comment by iAmBipinPaul** [comment]
so basically , It happens after that I'm again installing the Terminal. It works for one or two times after that  again same issue.

I just reset my PC and I did get much time to try this out , I will update the with more log details if it will happen again.
Where I can see the log message?

**Comment by felixse** [comment]
Looks like some problem with anti virus software. Here is how someone managed to solve this: https://github.com/rprichard/winpty/issues/142

**Comment by iAmBipinPaul** [comment]
There is McAfee on my system that comes  Pre-installed on Dell XPS. I will uninstall that from my system. Looks like uninstalling will solve the issue. (I will update about the issue)
Thank you @felixse
