### ISSUE TITLE
Consider adding `-NoLogo` to PowerShell's default profile

### ISSUE THREAD

**Issue by spencerwooo** [felixse/FluentTerminal#147]
There's an annoying thing when you invoke PowerShell: THAT BANNER, and a line telling you how long it took for you to load user configurations.

**Default example:**

![image](https://user-images.githubusercontent.com/32114380/49445082-fa272c00-f80b-11e8-97d6-b31ee9ad401a.png)

**With `-NoLogo` Argument:**

![image](https://user-images.githubusercontent.com/32114380/49445067-eed40080-f80b-11e8-92e6-7b8e1b07cf1e.png)

It took me some time to search for a solution on how to remove that banner. I think if you set that argument as default, it'll be more friendly to new-comers.

**Comment by skipmeister123** [comment]
I have incorporated this into my profile.  Thank you.

I disagree that it should be set by default.  We shouldn't hide information that could help somebody to troubleshoot an issue.  By default, people aren't using oh-my-posh -- that's something they need to install themselves.  If they do that, they should be well aware that they are no longer using a default environment and if they don't like the output, they are on their own to fix it.  We give them the tools to do that.  As a terminal emulator, we shouldn't mess with the default behavior of any terminal -- regardless of the good nature intention.  I'll leave it up to Felix, though.

--
Hans Kokx
On 12/4/2018 8:34:02 AM, Spencer Woo <notifications@github.com> wrote:
There's an annoying thing when you invoke PowerShell: THAT BANNER, and a line telling you how long it took for you to load user configurations.
Default example:
[image] [https://user-images.githubusercontent.com/32114380/49445082-fa272c00-f80b-11e8-97d6-b31ee9ad401a.png]
With -NoLogo Argument:
[image] [https://user-images.githubusercontent.com/32114380/49445067-eed40080-f80b-11e8-92e6-7b8e1b07cf1e.png]
It took me some time to search for a solution on how to remove that banner. I think if you set that argument as default, it'll be more friendly to new-comers.

**Comment by spencerwooo** [comment]
@skipmeister123 Okay. I understand. At least, I think, we can put this solution somewhere in Fluent Term's README or wiki for future reference. I personally find this config very useful.

**Comment by felixse** [comment]
Added this to the FAQ
