### ISSUE TITLE
Background rendering issues

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#149]
I have no idea what causes this, but there are white spots all over my background.  It happens fairly frequently.

![image](https://user-images.githubusercontent.com/1911919/49521449-7143db00-f873-11e8-877c-568142b5acc7.png)

**Comment by felixse** [comment]
Yeah, I noticed this too. Must be something with xterm.js

**Comment by akatsukiyami** [comment]
Same problem...

**Comment by felixse** [comment]
Looks like this has been fixed in xterm. Please reopen if this is still happening to you.
