### ISSUE TITLE
terminal color changes after npm/yarn install

### ISSUE THREAD

**Issue by itsjzt** [felixse/FluentTerminal#150]
First of all, thanks for making this awesome terminal.

* Issue: 
terminal color changes after npm/yarn install

* way to reproduce: 
open terminal and run `npm install <any-package>` or `yarn add <any-project>`

* here is how the color changes.
![capture](https://user-images.githubusercontent.com/22629916/49587750-d50cf780-f98a-11e8-8900-138bc49c7fd4.PNG)

P.S. doesn't happen in powershell but happens in vs code's integrated terminal.

**Comment by felixse** [comment]
I think this will be fixed when we update to the latest version of xterm.js (https://github.com/xtermjs/xterm.js/pull/1739)

**Comment by itsjzt** [comment]
That would be 💯  because currently, some themes make terminal literally unusable after `npm install`

**Comment by r3tex** [comment]
Bump :) Could we have a new build in the releases page with the new xterm?

**Comment by felixse** [comment]
>           Bump :) Could we have a new build in the releases page with the new xterm?

Done 👍
