### ISSUE TITLE
Double Ctrl+C to terminate batch job

### ISSUE THREAD

**Issue by aklein13** [felixse/FluentTerminal#151]
I was trying out Fluent Terminal and I run into an issue with `Terminate batch job (Y/N)` prompt after pressing Ctl+C.

In default PowerShell I could press Ctl+C twice to supress it instead of typing Y but it doesn't seem work in Fluent Terminal. Instead it adds `^C` to the same line.

Example (`yarn start` -> Ctrl+C spam):
PowerShell: https://imgur.com/p4Mfqjy
Fluent Terminal: https://imgur.com/54siKmR

As an example I used `yarn` command but I got the same results with `npm`.

**Comment by felixse** [comment]
Just checked this on my dev branch, this will be fixed by switching to ConPTY

**Comment by Jack-Works** [comment]
Yeah what about auto answer it likesother tools do? When "Terminate batch job" appears, automatically type "Y" then "Enter" to get rid of that.

**Comment by felixse** [comment]
upstream discussion: https://github.com/rprichard/winpty/issues/116

Auto answering sounds like a hassle since it also needs to be localization aware. For German it needs to type 'j' instead of 'y' for example.

I'm closing this now since it's working in ConPty (default for powershell profiles)
