### ISSUE TITLE
Fluent Terminal is Amazing -- Themes ?

### ISSUE THREAD

**Issue by SheepDomination** [felixse/FluentTerminal#152]
This UWP program is great, I love it; although where can I find themes ?

**Comment by skipmeister123** [comment]
Outside of creating your own, you can import any iTerm 2 compatible theme.  
There's a large repository here: https://iterm2colorschemes.com/

**Comment by SheepDomination** [comment]
How do you create your own theme, and how can I make a bread crumb visual pleasing path ?

**Comment by skipmeister123** [comment]
> How do you create your own theme
Head to settings > themes, and click the "Create new" button. Click edit, then click each colored square to choose a color.

> and how can I make a bread crumb visual pleasing path ?
This has been explained a few times.  Here's some information. https://github.com/felixse/FluentTerminal/issues/146

--
Hans Kokx
On 12/16/2018 9:55:03 PM, SheepDomination <notifications@github.com> wrote:
How do you create your own theme, and how can I make a bread crumb visual pleasing path ?

**Comment by Daniel15** [comment]
It would be awesome if FluentTerminal shipped with a few popular themes (like Monokai or one of its variants). Would you accept pull requests to add additional themes?

**Comment by skipmeister123** [comment]
You can import any iTerm2 compatible theme. Check out 
https://iterm2colorschemes.com/ for a bunch of them.

**Comment by tusher-A** [comment]
How to import themes from iterm2 color schemes?

**Comment by ms0uto** [comment]
You can import them actually

**Comment by ms0uto** [comment]
For future users reference @hanskokx was correct despite downvotes. 

I just copied entire file content form clicking in the name of the desired theme at [(https://iterm2colorschemes.com/ )]
Save the content using notepad as a desiredname.itermcolors, check the picture for reference and proof.

![imagen](https://user-images.githubusercontent.com/39985547/120729944-b0a12000-c4e0-11eb-8f83-435d7f33e3d2.png)
