### ISSUE TITLE
á displays as <C3><A1>

### ISSUE THREAD

**Issue by paulovila** [felixse/FluentTerminal#156]
tildes and accents are not displayed correctly

**Comment by r33int** [comment]
Accents does not render correctly on Windows's OpenSSH client, and seem to work fine in PowerShell. However, I can confirm I can't type the "~" sign on an AZERTY keyboard. It only types "2".

**Comment by paulovila** [comment]
Just mention that it doesn't display for me in PowerShell

**Comment by felixse** [comment]
Does this only occur in PowerShell, or also in CMD?

**Comment by ericcornelissen** [comment]
For me it mostly works fine in both PowerShell and CMD, the only issue is that if the combination of the tilde or accent and letter doesn't exists it outputs a capital version of that letter, while I expect it to output the tilde or accent followed by the letter.

Btw, I'm using US International Keyboard (qwerty)

**Comment by DjouGoulart** [comment]
I can't type tilde character in any console, it only types "Þ". I think this is something with system language/keyboard layout. My system is PT-BR, if I change to US then I can use tilde, but using a key that should be for single and double quotes.

**Comment by DjouGoulart** [comment]
I think this is a problem with xterm: https://github.com/xtermjs/xterm.js/issues/2151

**Comment by nsa** [comment]
This issue also continues for Turkish Q layout.

**Comment by paulovila** [comment]
accents are displaying properly, like Á or á, 
I think we can close this, any objections?
