### ISSUE TITLE
Tabs for different privledges ?

### ISSUE THREAD

**Issue by SheepDomination** [felixse/FluentTerminal#157]
Is it possible to run different tabs with different privileges such as, one tab runs in administrator mode while another tab runs in the privilege to which the user is logged into Windows, such as; standard ?

**Comment by felixse** [comment]
Should be possible for Windows 1809+ once we support the new ConPTY

**Comment by SheepDomination** [comment]
It's not possible on 1809 ?

**Comment by felixse** [comment]
It should be, just not implemented yet

**Comment by SheepDomination** [comment]
Could it be added anytime soon 👍 ?

**Comment by felixse** [comment]
It's pretty high on the roadmap. I'm closing this issue since it is already tracked in #6
