### ISSUE TITLE
Having two tabs, opening new window and closing it closes all windows.

### ISSUE THREAD

**Issue by atharos1** [felixse/FluentTerminal#159]
Hi! First of all let mi congratulate you on this most amazing project! I've been using Fluent Terminal for months now with hardly any issues.
One quirk I did notice, was that if I have an open window with an _even_ number of tabs (weird?) (all of them running WSL), then open new window, and close that window by trying to close the tab (it doesn't happen if i attemp to close the window through the window control itself), then original window, the one with multiple tabs, closes itself.
Again, it doen't happen if I have an odd number of tabs in the first window, or if I try to close the new window by pressing the default close window button.
Hope it helps!

**Comment by skipmeister123** [comment]
This sounds like something we've been trying to figure out for a while. The 
even numbered tabs thing is a new suggestion, worth investigating.
--
Hans Kokx
