### ISSUE TITLE
Allow detaching and attaching of tabs

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#16]
I would like to be able to tear a tab off of a window and either create a new window, or drop it onto another window to attach the tab to the new window.

**Comment by felixse** [comment]
This one is a bit tricky.
The problem is that UWP is running each window in a separate thread, so we cannot just move some control to another window. There are two ways this could be implemented, but both a blocked upstream at the moment:
1. Use https://github.com/xtermjs/xterm.js/issues/595 so that we can recreate the terminal state in the new window.
2. Wait for same-thread multi window in UWP (IIRC this was announced for RS5 on this year's Build conference)

**Comment by skipmeister123** [comment]
I think either solution would probably work.  2. might be more elegant, when it comes out, but 1. would be a great stopgap measure.

**Comment by felixse** [comment]
Lets just agree on implementing whatever is available first 😄 

Thanks for your feedback btw, nice to have some fresh ideas on where this project should be heading to

**Comment by skipmeister123** [comment]
Yeah, for sure.  I just got REALLY sick of the lack of decent, beautiful terminal emulators out there. Hyper is the closest thing to a decent looking app we have had, so I set out to build one myself -- except I haven't had any experience in writing this sort of thing.  As I started doing research, your project popped up and it's exactly what I envisioned.  It just needs a few things fixed. :)

fwiw, I look to iTerm2.app as inspiration for what a really good terminal emulator should be like.  Granted, it's macOS only...

--
Hans Kokx
On 5/24/2018 2:52:43 PM, Felix <notifications@github.com> wrote:
Lets just agree on implementing whatever is available first 😄
Thanks for your feedback btw, nice to have some fresh ideas on where this project should be heading to

**Comment by manuelelucchi** [comment]
Imho you should just wait to RS5 to come out. At this point, you should use Sets instead of your implementation, that is integrated in the os and supports more apps/drag and drop etc

**Comment by skipmeister123** [comment]
I agree; that's probably the best option. I can live without it, for now... but it's certainly something I'm very interested in.  HOWEVER...

I don't know if Sets will let you do the OTHER thing that I'd really like:  To be able to do split-pane by dragging a tab off, and dropping it onto another terminal window, thereby splitting the panes side-by-side.  THAT might require solution 1.

--
Hans Kokx
On 5/24/2018 3:01:28 PM, Manuele Lucchi <notifications@github.com> wrote:
Imho you should just wait to RS5 to come out. At this point, you should use Sets instead of your implementation, that is integrated in the os and supports more apps/drag and drop etc

**Comment by felixse** [comment]
I'm not quite sure if Sets will be able to fully replace our custom tab implementation. For example creating a new tab in the same window: I have yet to find some information whether Sets will provide an API for that.

For me it looks like Sets is meant to combine multiple different apps in one window, but not ready yet to replace tabs within an app

**Comment by skipmeister123** [comment]
Given that, maybe a custom implementation is the right way to go, after all.

--
Hans Kokx
On 5/24/2018 3:19:23 PM, Felix <notifications@github.com> wrote:
I'm not quite sure if Sets will be able to fully replace our custom tab implementation. For example creating a new tab in the same window: I have yet to find some information whether Sets will provide an API for that.
For me it looks like Sets is meant to combine multiple different apps in one window, but not ready yet to replace tabs within an app

**Comment by felixse** [comment]
Added with https://github.com/felixse/FluentTerminal/pull/467
