### ISSUE TITLE
Most keyboard shortcuts are broken on master

### ISSUE THREAD

**Issue by Riebart** [felixse/FluentTerminal#164]
Trying to rebase my command line translation PR, and I've noticed that on a fresh pull of master, most (all except shell profile shortcuts, I think) keyboard shortcuts are broken.

Haven't dug too far into it, but I've traced it back to `TerminalBridge.InvokeCommand` is receiving `null` when you press most keyboard shortcuts. Shell profile shortcuts still work though.

**Comment by felixse** [comment]
There were some issues, but the latest commit on master should fix them. Can you try with a rebase?

**Comment by Riebart** [comment]
I just checked again:

- `git clone`, master has a head at ff2cfc36
- `npm install` and `npm run build` in FluentTerminal.Client
- Build solution in VS2017
- Run Debug build
- Try `Ctrl+Shift+T`, and nothing happens.

I don't think I've broken anything...

Notably, my dev VM is an insider build and it just updated to a newer version, perhaps that's it? I'll try stashing my changes in my fork, and create a new dev VM, but that won't be until the weekend likely.

**Comment by Riebart** [comment]
Not sure what it was, but current master (8131140cb0f358826e46ebcc69cb4cec2c971598) on a fresh install of Windows 1809 works. Closing the issue, might have been an insiders release problem.
