### ISSUE TITLE
Version info in the app

### ISSUE THREAD

**Issue by MarcAnt01** [felixse/FluentTerminal#166]
I have to go manually to "Apps and features" in W10 settings to see what version I am runnning

**Comment by jonaskuske** [comment]
Starting from v3.0.0 (current), you can go to the About page and it'll show you both the currently installed and the latest version 😄 
Just go to `☰ → About` !

**Comment by MarcAnt01** [comment]
> I have to go manually to "Apps and features" in W10 settings to see what version I am runnning

Oh, I lost this detail, great
