### ISSUE TITLE
Opening the about page resizes the terminal window

### ISSUE THREAD

**Issue by hanskokx** [felixse/FluentTerminal#167]
I opened the about page and it resized my terminal window to match the size of the settings window. v0.3

**Comment by ericcornelissen** [comment]
I'm not able to reproduce this in any sensible way, I tried:

- Change terminal size, open settings through hamburger menu, open about through navigation pane
- Change terminal size, open about through hamburger menu
- Make terminal full size, open settings through hamburger menu, open about through navigation pane
- Make terminal full size, open about through hamburger menu

This might be related to the resizing problem with the settings Window I described in [this comment](https://github.com/felixse/FluentTerminal/issues/18#issuecomment-436409770) 🤔
