### ISSUE TITLE
Color difference from default shell

### ISSUE THREAD

**Issue by giggio** [felixse/FluentTerminal#170]
Colors are not displaying correctly.
Bellow you can see a comparison between Fluent Terminal and the default powershell output.

Some colors are faded, others are wrong.

In the example bellow `ccat` is simply `pygmentize.exe -g -O style=vs -f console16m` (a Python program). It is outputing VT100 escape code which is enabled by default on my terminals (see [here](https://stackoverflow.com/a/51681675/2723305) how to enable it).

I don't think that the VT100 escape codes are affecting the problem. The colors on the top are not using VT100 and are also incorrect.

![Color difference](https://user-images.githubusercontent.com/334958/50912314-03ae4000-1419-11e9-870d-3fd25df3bde9.png)

**Comment by giggio** [comment]
Maybe the implementation with ConPTY would work better?

**Comment by giggio** [comment]
I noticed that this issue also affects VS Code, so I checked. The same color distortion is there, exactly like it. So, yes, it is rooted on the same problem as #9.

**Comment by skipmeister123** [comment]
Seems likely, but I don't know where we're at with that.
--
Hans Kokx

**Comment by felixse** [comment]
They are currently working on a [buffer that can hold real color information](https://github.com/xtermjs/xterm.js/pull/1878), so its definitively on their roadmap

**Comment by felixse** [comment]
We will track this in #9
