### ISSUE TITLE
Context menu (custom) for terminal tabs does not open when there's only a single tab

### ISSUE THREAD

**Issue by ericcornelissen** [felixse/FluentTerminal#178]
![preview](https://user-images.githubusercontent.com/3742559/51280125-933e8a80-19e7-11e9-9328-af141e9bb2d3.gif)

**Comment by felixse** [comment]
We could move edit title to the hamburger menu when there is only one tab. I would suggest that in context of #173 
Try enabling 'always show tabs' in 'Settings -> General' in the meantime

**Comment by ericcornelissen** [comment]
> We could move edit title to the hamburger menu when there is only one tab. I would suggest that in context of #173

Although that works, I don't think that is a satisfying solution...


> Try enabling 'always show tabs' in 'Settings -> General' in the meantime

Works great, thanks 😄
