### ISSUE TITLE
Allow bold text for prompts etc

### ISSUE THREAD

**Issue by EdwardJB** [felixse/FluentTerminal#182]
ConsoleZ (right hand side) has an option to enable bold text for prompts etc (which is how the native `gnome-terminal` looks). Is this possible (or could it be implemented :smile:)?

![screenshot_win10_2019-01-20_16 17 50](https://user-images.githubusercontent.com/30390944/51441975-882d7800-1ccf-11e9-992c-3d6b704ced81.png)

**Comment by ericcornelissen** [comment]
This should be easily implemented through the terminal configuration (for more info see [the xterm documentation](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/)).

Some early tests confirm that it should work, only strange thing is that it doesn't work for me if I specify the `fontWeight` in [the `terminalOptions`](https://github.com/felixse/FluentTerminal/blob/369b5ddacf15508f632b21ce478e26d8183801f7/FluentTerminal.Client/src/index.js#L29)... 🤔

**Comment by ericcornelissen** [comment]
@EdwardJB do you know how the native `gnome-terminal`/ConsoleZ deals with bold text? Xterm distinguishes between [Font Weight](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#fontweight) and [Font Weight Bold](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#fontweightbold), for example in the image ⬇️ "D:\Workspace" is normal text and "erico@LAPTOP-ERIC" is already bold text.

![image](https://user-images.githubusercontent.com/3742559/51444822-7d8dd580-1d05-11e9-8dd9-90affcd1c432.png)

**Comment by EdwardJB** [comment]
I don't know *how* it does it, but it looks like this, if it helps at all.

![screenshot from 2019-01-22 15-11-36](https://user-images.githubusercontent.com/30390944/51544538-17659780-1e58-11e9-9a13-9259a26bdebd.png)

**Comment by ericcornelissen** [comment]
Hmm 🤔 [there](https://user-images.githubusercontent.com/30390944/51544538-17659780-1e58-11e9-9a13-9259a26bdebd.png) it looks "ed@pop" is the same weight as [my](https://user-images.githubusercontent.com/3742559/51444822-7d8dd580-1d05-11e9-8dd9-90affcd1c432.png) "erico@LAPTOP-ERIC" and "touch test" is the same weight as "ls" so it seems you can already achieve what you want by following the description found in #146.

Still I think having a bold option is nice, we just have to figure out how to distinguish [Font Weight](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#fontweight) and [Font Weight Bold](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#fontweightbold)...

**Comment by EdwardJB** [comment]
Sorry I don't follow. I need to install OMZ or OMP - or something?

**Comment by ericcornelissen** [comment]
It seems you're using WSL, you should install [OMZ](https://github.com/robbyrussell/oh-my-zsh). However, I realize now that this will drastically change the overall look of the terminal - unless there is some theme for ZSH that looks the same as a normal terminal shell 🤔 

I have not yet enabled WSL on my machine so I cannot properly test this for you at the moment, perhaps someone else can (or yourself if you want to setup the development environment)? Either way, I feel like #183 is not going to solve the particular issue you're having 😞

**Comment by skipmeister123** [comment]
I use oh-my-zsh, but can confirm that something funky happens with bold text (and, hint: it's not bold).

![image](https://user-images.githubusercontent.com/1911919/51711515-53386280-1ffa-11e9-86ff-ecb670fbad9d.png)
