### ISSUE TITLE
Unable to scroll back after Ctrl+L

### ISSUE THREAD

**Issue by y1zhou** [felixse/FluentTerminal#184]
After hitting `Ctrl+L` I'm unable to scroll up to view the commands / outputs. If the screen is cleared with running `clear`, I'm still able to scroll back. I always assumed these two are equivalent, so is this expected or a bug?

Thanks for the great work! Best terminal app I've found on Windows so far!

**Comment by felixse** [comment]
Yes, that's be design. `clear` is handled by the shell, which most commonly just writes enough blank lines to bring everything out of view. `Ctrl+L` is linked to a clear method in xterm.js which really clears the complete buffer
