### ISSUE TITLE
$Host.UI.RawUI Foreground and Background Color reset to White

### ISSUE THREAD

**Issue by migalicious** [felixse/FluentTerminal#186]
Hi,

I'm not sure if this is an issue with FluentTerminal itself, or one of the underlying components, as this happens for me in [Terminus](https://github.com/Eugeny/terminus), but not the 3.0.0-canary.6 release of [Hyper](https://github.com/zeit/hyper).  It's also seemingly an issue with something in my profile, as it doesn't happen on my test VM, only on my desktop. I'm making an issue here as I'm not sure where else to, and Google doesn't turn up much.  Feel free to close as irrelevant.

Whenever I start typing a command, it seems that $Host.UI.RawUI.Foreground and $Host.UI.RawUI.Background get reset to white. Even after I manually reset one, after typing/running a new command, it gets reset again, making everything unreadable.

I've confirmed it's not an issue with PsReadline 2.0.0.  It's also not an issue with something in my Powershell profile, as it happens with no profile.

I also want to say thanks for this project. I've been really wanting a modern terminal emulator for Windows, and was excited to come across this project yesterday.

OS: Windows 10 1809 Build 17763.292
$PSVersionTable | fl

Name  : PSVersion
Value : 5.1.17763.134

Name  : PSEdition
Value : Desktop

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}

Name  : BuildVersion
Value : 10.0.17763.134

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : WSManStackVersion
Value : 3.0

Name  : PSRemotingProtocolVersion
Value : 2.3

Name  : SerializationVersion
Value : 1.1.0.1

---

Output from screenshot:

echo $Host.UI.RawUI 

ForegroundColor       : White
BackgroundColor       : White
CursorPosition        : 0,7
WindowPosition        : 0,2
CursorSize            : 25
BufferSize            : 87,3000
WindowSize            : 87,28
MaxWindowSize         : 87,236
MaxPhysicalWindowSize : 768,236
KeyAvailable          : True
WindowTitle           : john@DESKTOP C:\Users\John

![](https://i.imgur.com/oqvRmlD.png)

**Comment by migalicious** [comment]
I figured out the issue:
Computer\HKEY_CURRENT_USER\Console\ScreenColors was set to ff instead of 7, causing the issue.

Please delete this.  My apologies.

**Comment by skipmeister123** [comment]
Cheers! Glad you figured it out, and thanks for using FT!
--
Hans Kokx

**Comment by jptrosclair** [comment]
You know I've had problems like this with nearly all non-cmd.exe terminals, most notably in vscode. Tried fluent terminal recently and low and behold, there it is again. Decided to take a look at the issue tracker and found this. Exported my console registry, deleted the thing entirely and... fixed! Terminal problems in vscode... fixed!

I'd buy you a freaking beer anytime @migalicious. Thanks for following up on this!

**Comment by acharkq** [comment]
> I figured out the issue:
> Computer\HKEY_CURRENT_USER\Console\ScreenColors was set to ff instead of 7, causing the issue.
> 
> Please delete this. My apologies.

Solved the same issue. Thanks a lot!
