### ISSUE TITLE
How do I get the powershell to open and I get FluentTerminal?

### ISSUE THREAD

**Issue by cooper1x** [felixse/FluentTerminal#189]
I want to open this theme directly from powershell, instead of selecting FluentTerminal each time I hold down the Shift key in the folder.

By the way, how do I uninstall this if I don't want to use it?

**Comment by ericcornelissen** [comment]
I'm not sure about you first question, but to uninstall this you can go to the Windows Settings (e.g. using <kbd>Win</kbd>+<kbd>i</kbd>) select "Apps" and find "Fluent Terminal" under "Apps & features", just like you would uninstall other apps on Windows 10...

**Comment by cooper1x** [comment]
@ericcornelissen Thx,now I know how to uninstall it.
I mean, I want to replace the native powershell with FluentTerminal, which means that every time I open the powershell, I will switch to open the FluentTerminal. After all, the interface of powershell is so ugly...

**Comment by skipmeister123** [comment]
I think that would require Windows letting you set a default for the 
terminal, which is not currently supported. I don't think this will be 
possible.
--
Hans Kokx

**Comment by felixse** [comment]
I don't think this is possible. But if you install the Explorer integration and configure to launch on startup its pretty easy to reach a fluent terminal window if you need one.
