### ISSUE TITLE
type one number, display double

### ISSUE THREAD

**Issue by oooowing** [felixse/FluentTerminal#191]
type number after app started
<img width="842" alt="snipaste_2019-01-31_16-36-44" src="https://user-images.githubusercontent.com/7744263/52041845-8ccb1980-2576-11e9-8853-a4093d602192.png">

if I type string, then number,it will be ok

**Comment by felixse** [comment]
So, if you type a digit it gets inserted twice, but letters are ok?
Does this only happen with a powershell profile? Does the built-in PowerShell behave the same way?

**Comment by Mredrock** [comment]
I got the same troble. Whatever I choose the WSL, CMD, or powershell, it types number after app started
