### ISSUE TITLE
Thank you so much

### ISSUE THREAD

**Issue by matan335** [felixse/FluentTerminal#197]
I have saw your comment

I also met this problem after upgrading my Xcode to version 10.
Combining all the possible workarounds above, I fix this by:

Clean RN cache

```shell
$ rm -rf ~/.rncache
```

Re-install the deps

```
$ cd your_project_path
$ rm -rf node_modules/ && npm install
```
Then install the third-party

```shell
$ cd node_modules/react-native/scripts
$ ./ios-install-third-party.sh
```

Run the commands below if glog installation failed.

```shell
$ cd ../third-party/glog-0.3.x
$ ./configure
```

It works for me, I hope it helps for you.

it just got my app to work your the best!!!

Thank you soo much

**Comment by felixse** [comment]
I don't think this belongs here, but nice to hear you found a solution to your problems 😄
