### ISSUE TITLE
[Feature request] Consider shipping a portable binary release

### ISSUE THREAD

**Issue by krishnakumarg1984** [felixse/FluentTerminal#198]
I am using FluentTerminal on my personal laptop in my home, and it is amazing. Thank you and good work!

Now, in my work environment, the ICT department will not give me `admin` privileges. Therefore, I cannot run any arbitrary script without the `UAC` popping up and asking for privilege escalation.

Currently, I am using [`cmder` ](https://github.com/cmderdev/cmder/releases) which provides portable releases that can simply be unzipped anywhere and used straightaway.  

It would be awesome if you can consider this feature request.

**Comment by felixse** [comment]
I am afraid we cannot do this. UWP does not allow to create portable releases 😢

**Comment by cebaa** [comment]
@felixse Is this due to https://github.com/microsoft/WindowsAppSDK/issues/134?
