### ISSUE TITLE
Contextual Menu "Open FluentTerminal in this folder"

### ISSUE THREAD

**Issue by manuelelucchi** [felixse/FluentTerminal#2]
Fluent Terminal is really awesome but to be perfect it needs just one thing: the ability to be opened inside a specific folder from the right click contextual menu (like visual studio or visual studio code)
Regard,
Manuele

**Comment by felixse** [comment]
Already thought about this, but it seems like there is no UWP or Desktop Bridge way of achieving this. I am open to ideas on this one.

**Comment by felixse** [comment]
As of 0.1.4.0 there is command line support for Fluent Terminal. E.g calling "flute new" opens a new window. It should be easy to extend the CLI here to also be able to specify a startup directory and write some *.bat to register this in the directory context menu. I am not sure if we can integrate this into the SystemTray component. But offering this as a separate download should be possible.

**Comment by felixse** [comment]
Added standalone *.bat scripts to install and uninstall the Explorer context menu integration

**Comment by neilsustc** [comment]
Perfect! And it would be better to mention this in the `README`

**Comment by felixse** [comment]
Good point 👍 

I added a link to the scripts in the readme
