### ISSUE TITLE
Most fonts have large gaps between letters

### ISSUE THREAD

**Issue by Wheezeasauraus** [felixse/FluentTerminal#200]
![image](https://user-images.githubusercontent.com/47489250/52528300-36c34800-2cd3-11e9-8a50-d987f94b3b65.png)

**Comment by skipmeister123** [comment]
Out of curiosity, are these Asian fonts?
--
Hans Kokx

**Comment by felixse** [comment]
Thats because most fonts are not suitable for terminals. Please select a monospaced font like Consolas, Courier etc.
