### ISSUE TITLE
[Suggestion] New logo

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#203]
I've been working on an idea for an updated logo, using the existing one as a base.  Feedback?
![48x48](https://user-images.githubusercontent.com/1911919/52744453-bf2f3a80-2faa-11e9-954d-a7a6064c76b9.png)
![1280x1280](https://user-images.githubusercontent.com/1911919/52744452-be96a400-2faa-11e9-90c5-e60886be4862.png)

**Comment by ericcornelissen** [comment]
Can I ask what your motivation for this change is? It's not clear to me what the additional line is supposed to represent 🤔

**Comment by skipmeister123** [comment]
Sure; fair question.  Here was my thought process in designing it:

The current logo accurately represents the product, however I believe that visibility could be improved.  As it stands, with just a white logo it will get lost on a white background.  Including a framing device will naturally give it contrast.  That way, on a white background, you wouldn't have to change the color - and therefore the branding - of the logo.

The line on the bottom has a few purposes:

1) It offers a suggestion of depth.  It could be viewed as the side of a 3D box, suggesting FluentTerminal has depth.
2) It is representative of the tab bar.
3) It acts as a form of punctuation; and "underline", if you will.  It's a subtle way of saying, "This is your terminal."

Does that help?

--
Hans Kokx
On 2/14/2019 3:19:12 AM, Eric Cornelissen <notifications@github.com> wrote:
Can I ask what your motivation for this change is? It's not clear to me what the additional line is supposed to represent 🤔

**Comment by felixse** [comment]
I'm not a fan of the black background. I would like to keep the icon a single colored shape to be in line with the rest of the Windows 10 icons. 

I think we should make the prompt symbol more unique, for example by adding some perspective to it (similar to the current Visual Studio icons) or something

**Comment by ericcornelissen** [comment]
I agree with @felixse, but I think your argument (contrast and recoloring) is pretty strong @skipmeister123. Even with your explanation I still don't like the line at the bottom though 😅 but that's pure personal preference


> I think we should make the prompt symbol more unique, for example by adding some perspective to it (similar to the current Visual Studio icons) or something

I expect it will be difficult to do that without looking to much like the Visual Studio icons, and I don't think it is a good idea to have logo that people will associate with that brand if it's not actually related.

**Comment by skipmeister123** [comment]
I'm going to think on this and come up with a second proposal.


--
Hans Kokx
On 2/15/2019 7:53:14 AM, Eric Cornelissen <notifications@github.com> wrote:
I agree with @felixse [https://github.com/felixse], but I think your argument (contrast and recoloring) is pretty strong @skipmeister123 [https://github.com/skipmeister123]. Even with your explanation I still don't like the line at the bottom though 😅 but that's pure personal preference
I think we should make the prompt symbol more unique, for example by adding some perspective to it (similar to the current Visual Studio icons) or something
I expect it will be difficult to do that without looking to much like the Visual Studio icons, and I don't think it is a good idea to have logo that people will associate with that brand if it's not actually related.

**Comment by moigagoo** [comment]
I don't like the new one either. What's the purpose of the horizontal line?

**Comment by Tommasov** [comment]
I've got your point... and I agree.
This is how it looks like in my taskbar: 
![taskbar](https://user-images.githubusercontent.com/9279914/54705832-f199fd80-4b3d-11e9-9769-9cb4796fe206.jpg)
This is your logo:
![taskbarnew](https://user-images.githubusercontent.com/9279914/54706090-653c0a80-4b3e-11e9-9e25-e75c888c898a.png)

Maybe not black but I like the solid color.

**Comment by ericcornelissen** [comment]
@moigagoo as mentioned in [this comment](https://github.com/felixse/FluentTerminal/issues/203#issuecomment-463653241):

> The line on the bottom has a few purposes: 1) It offers a suggestion of depth.  It could be viewed as the side of a 3D box, suggesting FluentTerminal has depth. 2) It is representative of the tab bar. 3) It acts as a form of punctuation; and "underline", if you will.  It's a subtle way of saying, "This is your terminal."

@Tommasov I can see why you would want that in your task bar, but maybe not in other places like the system tray :thinking: Also, UWP apps by Microsoft (e.g. Calculator and Groove in your screenshots) tend to have the same style. I'm not saying we **must** follow that but it's word considering. Just my two cents :slightly_smiling_face:

**Comment by mikemaccana** [comment]
This is a Windows 10-style icon, design to fit  in with Edge, vscode, Office and other recent Microsoft apps.  

 - Sharp edges (not curved)
 - A distinct shape
 - Positive (occupies space) not negative (a cutout from a square)

The points used in the vector come from Microsoft's own Powershell icon. Let me know what you think.

![image](https://user-images.githubusercontent.com/172594/55295252-c5fef900-5402-11e9-834b-1e51015904fd.png)

I have the vector source and the .ico file - I can send a PR if you like it, just tell me where to put them!

**Comment by felixse** [comment]
I don't know about the blue, but I like the shape 👍

**Comment by mikemaccana** [comment]
Thanks @felixse! 😃 Would you prefer to keep white or a different color?

**Comment by moigagoo** [comment]
Love the new variant ❤

**Comment by musm** [comment]
I like the shape not soo sure I like the color through

**Comment by skipmeister123** [comment]
I'm still working my way through the design process for a second pass at this.

**Comment by skipmeister123** [comment]
How about something that fits the Fluent design language? These are based off of Microsoft's new Office suite of icons.

![FluentTerminalIcon](https://user-images.githubusercontent.com/1911919/55366918-c6f26200-54b8-11e9-80ff-1cd06b32b6f9.png)
![FluentTerminalIcon-64](https://user-images.githubusercontent.com/1911919/55366919-c8238f00-54b8-11e9-90c5-f3d1eec5e9c6.png)

**Comment by skipmeister123** [comment]
Alternative gradient:

![FluentTerminalIcon](https://user-images.githubusercontent.com/1911919/55367017-120c7500-54b9-11e9-9c21-897f68f1cfe8.png)

**Comment by mikemaccana** [comment]
I don't think the new Office icons are a good fit for Fluent. 

Office icons are unique though in that they have a letter - O, X, P, etc + and have to 'honor the heritage' - https://medium.com/microsoft-design/redesigning-the-office-app-icons-to-embrace-a-new-world-of-work-91d72608ee8f. 

W stands for word, the thing behind that is a Word document: X stands for Excel, the thing behind that is a spreadsheet:

![image](https://user-images.githubusercontent.com/172594/55412283-0e332e00-555f-11e9-8828-62a25e7978d2.png)

**If Fluent Terminal was going to do the same thing, it'd be an F with a terminal behind it. But Fluent isn't an Office app - it's a Windows one.**

**Comment by felixse** [comment]
Another problem would be the scaling for the SystemTray, context menu. I think a clear shape based icon would perform better in smaller sizes.

For the color I would say white and also a black version to support the new light theme in 19H1. I'm not sure about a gradient, but I'm open for proposals 😄

**Comment by moigagoo** [comment]
@mikemaccana I wanted to bring in the Powershell Preview icon as an example of icon design I like, but I see you don't like it much 😂: https://github.com/PowerShell/PowerShell/issues/7441

I do like Powershell Preview icon though. It's fun. It may need some finetuning for small sizes, but I like the idea behind it. I'd love Fluent Terminal to have a funkier icon than your conventional monochrome blue or green or white or black one.

Anyway, I like your icon. I can see why Powershell team declined it (they're not entirely free to choose), and I can see it in Fluent Terminal. My wish for an alternative, funkier variant with a gradient, is absolutely optional.

**Comment by mikemaccana** [comment]
> For the color I would say white and also a black version to support the new light theme in 19H1.

Sure, white:

![image](https://user-images.githubusercontent.com/172594/55475041-c2d65980-560a-11e9-9237-21e569c556a0.png)

Dark version, shown with light theme:

![image](https://user-images.githubusercontent.com/172594/55474933-64a97680-560a-11e9-8eb2-cd1cdd50afb4.png)

Both colors taken from same as Windows icon (FBFBFB for white, full black for black).

@felixse Can you make the icon color change with the theme?

**Comment by felixse** [comment]
https://blog.mzikmund.com/2018/11/supporting-light-theme-taskbar-icons-in-uwp/
Should be no problem

**Comment by skipmeister123** [comment]
I can get behind your design. Great work. 👍

**Comment by mikemaccana** [comment]
@felixse Want me to add the svg to the repo? Where should I put it?

**Comment by felixse** [comment]
@mikemaccana Yes sure, thanks a lot 😃 Just create a 'Icon Source' folder or something like that in the root directory
