### ISSUE TITLE
[Suggestions]Add Global Key Bingdings to Start FluentTerminal

### ISSUE THREAD

**Issue by oycy0306** [felixse/FluentTerminal#205]
Maybe I did not find where it is. Could you please add global key bingdings to open fluent terminal to open a new window when it is running in the background?

**Comment by ericcornelissen** [comment]
If you go to Settings `>` Keybindings there is an option called "Toggle window", I think this is what you're looking for.

Side note, I have not used this yet (as I haven't switched to Fluent Terminal as my main CLI yet) and while trying it out for you I discovered it seems to be a bit buggy, let us know if you have the same experience...

**Comment by oycy0306** [comment]
Thank you, my problem is solved. And...I didn't find this buggy...

**Comment by ericcornelissen** [comment]
In that case It's probably a problem with my machine :unamused: I guess this issue can be closed @felixse
