### ISSUE TITLE
[Solved][Bug]The 0.3.1.0 No_Dependencies can't be unziped successfully

### ISSUE THREAD

**Issue by Saafo** [felixse/FluentTerminal#208]
I use the **Bandizip** to unzip the 0.3.1.0 No_Dependencies version for twice, but each time it can't be unzip successfully due to "something is damaged in the zip files"

**Comment by Saafo** [comment]
![image](https://user-images.githubusercontent.com/46736350/52951716-85e93700-33bd-11e9-9f88-78eca0965309.png)
which meaning "data error, some files is damaged"
this problem also happened when I try to unzip the 0.3.1.0 version(without no_dependencies)

**Comment by patriksvensson** [comment]
@Saafo That's a problem with Bandizip and not the zip package. I can unzip the file using the file extraction in Windows and 7zip. Try using one of these applications instead.

![image](https://user-images.githubusercontent.com/357872/52976712-c69b7d00-33ca-11e9-9ef4-d34398113c4f.png)

**Comment by Saafo** [comment]
@patriksvensson Well thank you! It seems like something went wrong with the Bandizip. But I'm curious about why did the Bandizip go wrong...I've used it for about half a year and never met this kind of situation.

**Comment by felixse** [comment]
I had no problems unzipping it with BandiZip, maybe your installation got corrupted somehow?

**Comment by Saafo** [comment]
@felixse Finally I found the reason: I used the **Photon**(a downloader based on aria2) to download the zip, and today I used my broswer to download it and I can successfully unzip it using BandiZip. So actually it's a problem with Photon.

**Comment by Saafo** [comment]
OK I figured out that I've used the old verson(0.2.2) of Photon, and now I updated photon to 0.3.0, there's no bugs unzipping the files downloading from photon
