### ISSUE TITLE
Tab tooltips don't display entire text

### ISSUE THREAD

**Issue by kwikadi** [felixse/FluentTerminal#212]
When I have a tab open with text longer than what the tab area can show, I get truncated text, which is fine, but the tooltip doesn't show the entire text either, instead showing the exact same text that i can already see on the tab (Which is pretty pointless).

Also, when there is a single tab open, there is no tooltip at all (and the text is still truncated, which looks odd since there is no demarcation for the tab when only one is open.

A rename option (#141) would also be useful till this can be fixed.

**Comment by ericcornelissen** [comment]
> Also, when there is a single tab open, there is no tooltip at all (and the text is still truncated, which looks odd since there is no demarcation for the tab when only one is open.

For now you can solves this particular problem by enabling 'always show tabs' in 'Settings -> General'

> A rename option (#141) would also be useful till this can be fixed.

That is already implemented and you should be able to do this either from the tabs context menu (which requires the above solution, see #178) or using the shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> (see #193)

**Comment by felixse** [comment]
![image](https://user-images.githubusercontent.com/30559812/53589633-2bf02a80-3b90-11e9-97e5-bf68ac1e434d.png)

Looks good on my machine 😕 

But I agree that this looks weird and should be fixed:
![image](https://user-images.githubusercontent.com/30559812/53589709-58a44200-3b90-11e9-8d50-3fc7d9d029cb.png)

**Comment by kwikadi** [comment]
I did a little bit of testing, and you're right, this works fine when you rename a tab, but not when you let the tab stay as is (when it displays the path), when it clips off the front of the path.

![image](https://user-images.githubusercontent.com/4578690/53592032-6b803c00-3bbb-11e9-984a-ccf93605a546.png)

**Comment by felixse** [comment]
Ah, I see. Looks like your shell is somehow shortening your title.
