### ISSUE TITLE
Why not support Windows 7 ?

### ISSUE THREAD

**Issue by maxbitcoin** [felixse/FluentTerminal#219]
When I run "choco install fluent-terminal" by powershell, I found below:
ERROR: fluent-terminal is not supported on Windows 7 Ultimate, (Ultimate), Windows Kernel: 6.1.7601

**Comment by skipmeister123** [comment]
All of the target frameworks (eg, UWP) are available only on windows 10. In 
addition, even Microsoft no longer supports windows 7.
--
Hans Kokx

**Comment by felixse** [comment]
Yes, we rely on the UWP framework which is only available on Windows 10. No chance for Windows 7 support without rewriting the complete UI part.
