### ISSUE TITLE
Should `TERM_PROGRAM` be set?

### ISSUE THREAD

**Issue by DRSDavidSoft** [felixse/FluentTerminal#222]
### Description <kbd>Feature Request</kbd>
The `TERM_PROGRAM` environment variable is set by [Hyper](https://github.com/zeit/hyper/blob/663b16bc12bf33f5462006c3573e4fbe64360002/app/session.js#L95), [Terminus](https://github.com/Eugeny/terminus/commit/e246e22bfd51b1ee5e9e97a391ba6f51230070bb), [VS Code](https://github.com/Microsoft/vscode/blob/431b462fa7cf6582d8d06a62dd8c1bbe7ddb6031/src/vs/workbench/contrib/terminal/node/terminalEnvironment.ts#L55), and a couple of other apps (like iTerm 2) to inform the script of the terminal emulator program.

In turn, [Yarn](https://github.com/yarnpkg/yarn/blob/19ec98c5dd3f6edca0ae848893d19edd74e9cae8/src/cli/index.js#L107), [neofetch](https://github.com/dylanaraps/neofetch/blob/288a81a9e213eeb37c877edd74134e58e141c480/neofetch#L2784-L2791) and [neovim](https://github.com/neovim/neovim/blob/f050aaabbb31b58ebac519a6f7014610f2b119f0/src/nvim/tui/tui.c#L206-L211) use this variable to:
- **Yarn:** display emojis on Hyper and macOS terminals
- **neofetch:**  identify the terminal emulator program
- **neovim:** address terminal emulator capabilities and bugs

This is a pretty non-standard feature, but other xterm.js-based terminals like **Hyper** and **Terminus** set it, and **Yarn** happily uses it to display emojis on Windows.
Since **FluentTerminal** also uses _xterm.js_, would it be proper to set the `TERM_PROGRAM` to `FluentTerminal` by default?

Here's a summary of other terminals support:
https://github.com/Maximus5/ConEmu/issues/1837#issuecomment-469199525

### Demo
Notice the `✨` emoji on the last line:
<img width="430" alt="wmoj" src="https://user-images.githubusercontent.com/4673812/53727831-76222600-3e86-11e9-8bf8-915f05fcaf14.png">

**Comment by felixse** [comment]
I don't see anything speaking against it. But maybe it would be better to agree on something like `xterm.js`. That way applications wouldn't need to keep track on xterm.js based emulators and new projects could instantly benefit from it.

**Comment by DRSDavidSoft** [comment]
@felixse Actually your idea is better, but unfortunately, each of the following terminals has decided to use the package name instead of setting it to anything similar to `xterm.js`

| name | value |
| :------- | :------ |
| macOS Terminal | `Apple_Terminal` |
| [iTerm2](https://www.iterm2.com/) | `iTerm.app` |
| [Hyper](https://hyper.is) <sup>2</sup> | [`Hyper`](https://github.com/zeit/hyper/blob/663b16bc12bf33f5462006c3573e4fbe64360002/app/session.js#L95) (formerly `HyperTerm`) |
| [Terminus](https://eugeny.github.io/terminus/) <sup>1</sup> | [`Terminus`](https://github.com/Eugeny/terminus/commit/e246e22bfd51b1ee5e9e97a391ba6f51230070bb) |
| [VS Code](https://code.visualstudio.com/)'s integrated terminal <sup>2</sup> | [`vscode`](https://github.com/Microsoft/vscode/blob/431b462fa7cf6582d8d06a62dd8c1bbe7ddb6031/src/vs/workbench/contrib/terminal/node/terminalEnvironment.ts#L55) |

<sup>1</sup> Until recently, Terminus set the variable `Terminus=1` instead of `TERM_PROGRAM=Terminus` (https://github.com/Eugeny/terminus/issues/702)
<sup>2</sup> VS Code and Hyper did not set the variable until someone asked (respectively https://github.com/Microsoft/vscode/issues/23295#issuecomment-290672645 and https://github.com/zeit/hyper/issues/1186#issue-195380977)

Respectively, the macOS terminal has always used `TERM_PROGRAM=Apple_Terminal` in their implementation.

In support of your idea, maybe _all_ xterm.js-based terminals should set `TERM=xterm` in their environment?

**Comment by skipmeister123** [comment]
We should be cautious using xterm if we intend to switch to ConPTY.

**Comment by DRSDavidSoft** [comment]
@skipmeister123 Are there any plans to switch from `xterm.js` to ConPTY?

**Comment by felixse** [comment]
There is a bit of a misunderstanding. ConPty is something we might use in the backend (instead of WinPty) but it won't have any influence on xterm.js being our frontend

**Comment by skipmeister123** [comment]
https://github.com/felixse/FluentTerminal/issues/128

**Comment by skipmeister123** [comment]
Oh. My mistake.

**Comment by DRSDavidSoft** [comment]
@skipmeister123 Thanks, so since `xterm.js` is going to power the front-end, the `TERM_PROGRAM` would be appropriate here since it's used to determine color/emoji/escape sequence support.
