### ISSUE TITLE
The right-click menu option remains after uninstall

### ISSUE THREAD

**Issue by ArnoFranklin** [felixse/FluentTerminal#226]
Hi.

A few days ago, I was uninstalled my FluentTerminal from start menu, I noticed it the right-click menu option still exist, I don't know where to delete it.

Any help will be appreciated.

Thank you for your work, FluentTerminal is beautiful.

![image](https://user-images.githubusercontent.com/26758820/54071474-c1ce3880-42a7-11e9-9bf8-bf838904d7e0.png)

**Comment by felixse** [comment]
You can find a uninstall script here: https://github.com/felixse/FluentTerminal/blob/master/Explorer%20Context%20Menu%20Integration/Uninstall.bat

**Comment by ArnoFranklin** [comment]
Thank you Felix, it works!

**Comment by kumarharsh** [comment]
Thanks for the script. But why doesn't it remove the context menu? IMO, this issue should be kept open till it's resolved.

**Comment by vikaspatelp83** [comment]
Hey there one solution: you can remove the **context menu** entry by deleting it from one of the registries.

- HKEY_CLASSES_ROOT\*\OpenWithList
- HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers
- HKEY_CLASSES_ROOT\Directory\Background
- HKEY_CLASSES_ROOT\Directory\shell
- HKEY_CLASSES_ROOT\Directory\shellex\ContextMenuHandlers
- HKEY_CLASSES_ROOT\Drive\shell
- HKEY_CLASSES_ROOT\Drive\shellex\ContextMenuHandlers
- HKEY_CLASSES_ROOT\Folder\shell
- HKEY_CLASSES_ROOT\Folder\shellex\ContextMenuHandlers 

I found it here **HKEY_CLASSES_ROOT\Directory\Background**
