### ISSUE TITLE
Wrong padding

### ISSUE THREAD

**Issue by chewnglow** [felixse/FluentTerminal#233]
Hello! The padding of terminal has something wrong in Chinese. System version is 18351.
![image](https://user-images.githubusercontent.com/22649869/54515937-8236d900-4998-11e9-9699-32a412a6cd56.png)

**Comment by chewnglow** [comment]
Some lining fonts has no problem, but most other fonts has.

**Comment by felixse** [comment]
What font did you select? You have to select a [monospaced font](https://en.wikipedia.org/wiki/List_of_monospaced_typefaces) to avoid these padding issues

**Comment by chewnglow** [comment]
Noto sans current. Now I have changed into monofont and behaving normally. Thanks!
