### ISSUE TITLE
How to open FluentTerminal with a command

### ISSUE THREAD

**Issue by Salil03** [felixse/FluentTerminal#234]
How can I open the fluent terminal with a command? Something like `cmd /k "your command"`.

Is this possible?

**Comment by skipmeister123** [comment]
https://github.com/felixse/FluentTerminal/pull/194

**Comment by Salil03** [comment]
So is it flute.exe?

**Comment by Salil03** [comment]
Thanks for the prompt reply

**Comment by skipmeister123** [comment]
Yup!

**Comment by Salil03** [comment]
Shouldn't we add this to the wiki?

**Comment by skipmeister123** [comment]
Probably not a horrible idea.

**Comment by Salil03** [comment]
Done. https://github.com/felixse/FluentTerminal/wiki/How-to-open-FluentTerminal-with-a-command

**Comment by skipmeister123** [comment]
Skål!

**Comment by Salil03** [comment]
Google translate says that Skål means "bowl" !!!

**Comment by skipmeister123** [comment]
It does, lol. It also means something along the lines of "Cheers!"

**Comment by Salil03** [comment]
Hey this doesn't work for me see this:

![image](https://user-images.githubusercontent.com/32109637/54707613-849b5d80-4b67-11e9-8d1f-d79f3c114382.png)



This is the only thing that happens. Python is not executed

**Comment by skipmeister123** [comment]
Yeah, that's because that PR I linked to earlier hasn't been merged yet 😅

**Comment by Salil03** [comment]
Oh. Any tentative date. :)

**Comment by Salil03** [comment]
And is there any other way for now?

**Comment by skipmeister123** [comment]
🤷‍♂️

**Comment by Salil03** [comment]
Oh well then

**Comment by felixse** [comment]
More like days than weeks 😉

**Comment by Salil03** [comment]
Oh thanks you very much. Can you create a release so that I can download it?

**Comment by felixse** [comment]
There will be a regular release once #236 is merged

**Comment by Salil03** [comment]
Thanks closing this issue now
