### ISSUE TITLE
Suggestion: Create new tab simillar to chrome

### ISSUE THREAD

**Issue by Salil03** [felixse/FluentTerminal#238]
I would like to just put it out there that FluentTerminal just rocks. It is one the most beautiful and fastest terminal emulators I have seen with active development.

In google chrome, we can create new tabs by clicking the '+' button next to the new tab. Adding a similar functionality would increase the speed of creating new tabs in FluentTerminal. In the current version we have to click the menu button and then open a new tab.

A step further would be to 'reopen closed tab'. But that is not a priority, at least right now.

**Comment by felixse** [comment]
Thanks 😃 

You can toggle 'Always show Tabs' in Settings -> General. That way you always see the '+' next to the tab.

'Reopen closed tab' would just open a tab with the same profile as the last one, but we would not be able to restore the state of the closed tab. I don't know if that would be very useful.

**Comment by Salil03** [comment]
Thanks for telling me that. Best wishes for this project from me :+1:
