### ISSUE TITLE
FluentTerminal does not throw error when command is invalid in CLI mode

### ISSUE THREAD

**Issue by Salil03** [felixse/FluentTerminal#241]
When I run the command `flute run "echo hello"`, there is no output on the FT screen. It just stays blank.

**Comment by Salil03** [comment]
Nor does it recognise the command `pause`

**Comment by Salil03** [comment]
And can we join two commands together by using ``&&`` ?

**Comment by felixse** [comment]
That's because commands are not executed in a shell and echo is provided by shell (as opposed to something like npm which you can execute without a shell beneath). It works if your command is `cmd /k echo hello && pause`

**Comment by Salil03** [comment]
Also another thing is that if I put some invalid command like `paithon`, the window stays open instead of saying `paithon is not recognised as an external or internal command`

**Comment by felixse** [comment]
Yes, that's not optimal. I will address this in 0.4.1.0 once some more issues appeared with the new version.
