### ISSUE TITLE
Installs fine, but then no access when I try to run it

### ISSUE THREAD

**Issue by reckoner** [felixse/FluentTerminal#243]
Installs fine, but then I get this:

    [Window Title]
    C:\Program Files\WindowsApps\53621FSApps.FluentTerminal_0.4.0.0_x64__87x1pks76srcp\Win32\FluentTerminal.SystemTray.exe

    [Content]
    Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.

    [OK]

**Comment by felixse** [comment]
Can you share the content of the log files? They are located at `%AppData%\Local\Packages\53621FSApps.FluentTerminal_87x1pks76srcp\LocalCache\Logs\`

**Comment by reckoner** [comment]
I found this directory,

    AppData\Local\Packages\53621FSApps.FluentTerminal_87x1pks76srcp\LocalCache\Logs

but there is only a config.json in there.

    {"logLevel":"error"}

**Comment by felixse** [comment]
Ok, that means no error has been logged. can you set the logLevel to debug and try starting it again? You might also find some helpful information in Windows Event Viewer -> Windows Protocols -> Application

**Comment by reckoner** [comment]
Here is the contents of that log file:

    2019-03-24 13:12:58.369 -07:00 [INF] Initialized
    2019-03-24 13:12:58.374 -07:00 [DBG] Created ApplicationViewAdapter for ApplicationView with Id: [-331463]

The light blue Fluent window opens but there is nothing in it. When I do

    flute run bash 

I get the error I originally mentioned.

**Comment by felixse** [comment]
Did you download the normal or the No_Dependencies release?

**Comment by reckoner** [comment]
No_Dependencies

**Comment by felixse** [comment]
Ok, maybe some dependency is missing. Can you try to uninstall it and then reinstall it using the full release?

**Comment by reckoner** [comment]
Yes. I did that, but I get the same permissions error. I uninstalled it from Settings. Do I have to reboot also?

**Comment by felixse** [comment]
I don't know, maybe it helps. On which version of Windows 10 are you experiencing this?

**Comment by reckoner** [comment]
Version	10.0.17763 Build 17763

**Comment by reckoner** [comment]
I rebooted and did the re-install. Still having same permissions problem. Thanks for following up! I'll check back later.

**Comment by leyafo** [comment]
Same problem as you.

**Comment by felixse** [comment]
@reckoner Do you also see a second log file, with 'SystemTray' in the name?

**Comment by reckoner** [comment]
No. There was none.

**Comment by felixse** [comment]
Then the SystemTray didn't start. Do you have .NET Framework (4.7.1 or newer) installed?

**Comment by reckoner** [comment]
.NET Framework 4.7.1 or a later update is already installed on this computer.


I just checked.

**Comment by felixse** [comment]
Ok, I have no idea whats going on here 😞

**Comment by reckoner** [comment]
@felixse  Thanks for trying.
