### ISSUE TITLE
explorer integration does not open the shell in the correct folder

### ISSUE THREAD

**Issue by NikkyAI** [felixse/FluentTerminal#244]
i installed Fluent Terminal 0.4.0.0 fromhttps://github.com/felixse/FluentTerminal/releases/tag/0.4.0.0

i tried this with Powershell and Bash (as bundled by git)

when using the explorer integration the new temrinal always just opens in the home folder

is there some sort of replacement string i have to put into the working directory field?

**Comment by skipmeister123** [comment]
For bash? I put ~ as an argument.

**Comment by NikkyAI** [comment]
the argument i have for bash is atm `-l` would `~` come before or after and what does this do ? afaik ~ is just pointing to the home dir right ?

**Comment by skipmeister123** [comment]
Probably after. It just tells bash to launch to your home dir.

**Comment by Gwokhov** [comment]
Try replacing the space character of the folder name?

**Comment by felixse** [comment]
There seems to be an issue with paths containing spaces. I will have a look at this tonight

**Comment by NikkyAI** [comment]
@skipmeister123 but it always launches it in the home dir anyways.. what i want is to open a terminal in a specific folder
i will also try withj paths that contain no spaces next time on windows
