### ISSUE TITLE
how to open a new tab with non-standard profile?

### ISSUE THREAD

**Issue by NikkyAI** [felixse/FluentTerminal#249]
i seem to be unable to find a w<ay in the GUI to open a new tab using anything other than the current default profile
i think a dropdown on righclicking the + button to select the profile would be nice
also a way to run powershell, cmd, etc as admin or checkboxes for that in the profile settings?

**Comment by ericcornelissen** [comment]
> i seem to be unable to find a w<ay in the GUI to open a new tab using anything other than the current default profile

This is indeed currently not available in the GUI, though it is being discussed in #196. Not sure if you're aware but it is possible to do this through a keyboard shortcut (by default <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd>).


> i think a dropdown on righclicking the + button to select the profile would be nice

I like the idea and would vote in favor of adding this on top of what is being discussed in #196 (as this is not immediately obvious)


> also a way to run powershell, cmd, etc as admin or checkboxes for that in the profile settings?

For more on this see the discussion in #6

**Comment by NikkyAI** [comment]
thanks
