### ISSUE TITLE
Install.ps1 doesn't work with pwsh.exe

### ISSUE THREAD

**Issue by pingzing** [felixse/FluentTerminal#250]
When attempting to install the application via the bundled `Install.ps1`, if the certificate needs to be installed, certificate installation will fail if the installer is run with `pwsh.exe` install of `powershell.exe`. The culprit is this line here: https://github.com/felixse/FluentTerminal/blob/43e4f8290e2496427af2e4dc444e4f0769237f42/Install.ps1#L366 as it assumes that there is always a `powershell.exe` under `$PSHOME`.

**Comment by didierms** [comment]
<html>
<body>

powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File .\Install.ps1
--



</body>
</html>
