### ISSUE TITLE
Using git-bash shell with FluentTerminal

### ISSUE THREAD

**Issue by stevenkkim** [felixse/FluentTerminal#255]
Is it possible to use the git-bash shell with FluentTerminal? I see some references to git-bash in the GitHub issues so I think it may be possible, but I don't know. I'm using Windows 10 Version 1809.

I tried creating a new profile, and setting the "Shell executable location" to my git-cmd.exe but when I launch FluentTerminal, I still seem to be in Windows command line mode (e.g. 'ls' does not work but 'dir' does.)

**Comment by felixse** [comment]
You need to create a profile with these values:

Location: `"C:\Program Files\Git\bin\bash.exe"`
Arguments: `-i`

**Comment by stevenkkim** [comment]
Wow, thanks for the quick reply. This works for me!

Thanks so much for creating this. I was using Hyper before, and this is a really nice replacement. (Hyper was too slow to load for me - FluentTerminal is much quicker).

**Comment by skipmeister123** [comment]
♥️ Thanks for supporting us!

**Comment by Loreno10** [comment]
I use `--login` argument. I noticed that it gives me the coloring of output (for example `ls` makes folders blue). When I used `-i` everything was just white. By the way, if someone knows why is that, it would be interesting to learn.

**Comment by Loreno10** [comment]
Another thing, I had to disable "ConPty" (whatever that is) for bash to work.

**Comment by yuwanlin** [comment]
thank you

**Comment by vsilaire** [comment]
Hey, unfortunaltely all of these solutions doesn't work for me :(
Here is the profile:
![image](https://user-images.githubusercontent.com/13857671/180434103-b9aaf9e9-7f43-404a-8d05-a4dc13099828.png)

Here is what I get:
![image](`https://user-images.githubusercontent.com/13857671/180433901-dec31f21-1207-4453-a125-f0e7db9b959e.png`)

**Comment by vsilaire** [comment]
and here is what I get:
![image](`https://user-images.githubusercontent.com/13857671/180433901-dec31f21-1207-4453-a125-f0e7db9b959e.png`)
