### ISSUE TITLE
Line ending style in profile preview is not always correct

### ISSUE THREAD

**Issue by ericcornelissen** [felixse/FluentTerminal#256]
> I've noticed the line-endings option doesn't always switch when selecting different profiles, and it appears that this is part of it. When selecting other profiles `DoNotModifyIsSelected` property is updated to `False` but the setter doesn't inspect that, and just sets `LineEndingStyle = LineEndingStyle.DoNotModify`.

_Originally posted by @ivanjh in https://github.com/felixse/FluentTerminal/pull/251#issuecomment-476201715_

* * *

Steps to reproduce (approximate):

1. Create a profile with `LineEndingStyle` do not modify
1. Create a profile with `LineEndingStyle` to CR+LF
1. Switch between the profiles a couple of times
1. Both profiles will display the same `LineEndingStyle` in the preview (for me it is always "do not modify")

note that this does not reflect the actual value, if you click edit on the profile with the wrong value, the setting will appear correctly.

**Comment by ivanjh** [comment]
Proposed fix in #257
