### ISSUE TITLE
Copy/Paste options

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#26]
I would like to have the option to select-to-copy and right-click-to-paste as alternatives to the right click menu as it exists today.

**Comment by felixse** [comment]
I plan to implement these three options, is there anything I'm missing?

- Right click opens context menu (current behaviour)
- Right click will copy selected text, or paste if no text is selected
- Selecting text will also copy it, right click will always paste

**Comment by skipmeister123** [comment]
Middle click to paste

Hans Kokx

**Comment by felixse** [comment]
Like a 4th option?

Selecting text will also copy it, middle click will paste, right click will open context menu?

**Comment by skipmeister123** [comment]
That would be a good option. Some people like middle click to paste.

Hans Kokx
