### ISSUE TITLE
"Open in Fluent Terminal" doesn't work when path of the directory includes a space

### ISSUE THREAD

**Issue by itshoro** [felixse/FluentTerminal#260]
Tried to open fluent terminal, via the context menu, the folder in question is called  `F:\Development\HTML\Test Folder`, however the terminal that was spawned opened at `C:\Users\USERNAME`.

It worked as intended, with all other characters I tried, but space.

Fluent Terminal 0.4.0
Windows 10, Version 1809

**Comment by ericcornelissen** [comment]
Seems to be the same as #244, can you confirm it works for folders without a space?

**Comment by itshoro** [comment]
Yes like I said in the initial post, it works for folders without a space.

For example `F:\Development\HTML\Test_Folder` resolved correctly.

**Comment by ericcornelissen** [comment]
My bad, in that case the issue was solved in #244 and should be fixed in the next release

**Comment by felixse** [comment]
Yes, this will be fixed in 0.4.1.0 which should drop later tonight. Thanks anyway for reporting 😃
