### ISSUE TITLE
How do I compile the project with msbuild.exe

### ISSUE THREAD

**Issue by christianmende** [felixse/FluentTerminal#262]

**Comment by skipmeister123** [comment]
Please see [this page](https://github.com/felixse/FluentTerminal/wiki/How-to-set-up-a-development-environment) for build instructions.

**Comment by felixse** [comment]
basically `msbuild.exe FluentTerminal.sln`
Do you have any specific error?

**Comment by christianmende** [comment]
Yes, I have a specific error, but my computer is updating right now. :(

**Comment by skipmeister123** [comment]
Tell it to stop 😅

**Comment by christianmende** [comment]
How should I xD, but its almost done (90%)

**Comment by skipmeister123** [comment]
PULL THE PLUG! 🤣

**Comment by christianmende** [comment]
It's a surface haha

**Comment by skipmeister123** [comment]
Shake it like an etch-a-sketch!

**Comment by christianmende** [comment]
Ok! Now I am opening the Project in VS Code and try to build

**Comment by christianmende** [comment]
And the error message is in German...

**Comment by skipmeister123** [comment]
> 
> 
> And the error message is in German...

Prost!

**Comment by christianmende** [comment]
Ok here it is

`PS C:\Users\chris\OneDrive\Desktop\FluentTerminal> msbuild.exe .\FluentTerminal.sln
Microsoft (R)-Buildmodul, Version 14.0.23107.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
Der Buildvorgang wurde am 29.03.2019 19:44:57 gestartet.
Projekt "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.sln" auf Knoten "1" (Standardziele).
ValidateSolutionConfiguration:
  Die Projektmappenkonfiguration "Debug|Any CPU" wird erstellt.
ValidateProjects:
  Das Projekt "FluentTerminal.App" ist in der Projektmappenkonfiguration "Debug|Any CPU" nicht zum Erstellen ausgewählt.
Das Projekt "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.sln" (1) erstellt "C:\Users\chris\OneDrive\Desktop\FluentTerminal\Fluent
Terminal.SystemTray\FluentTerminal.SystemTray.csproj" (2) auf Knoten "1" (Standardziele).
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1097,5): warning MSB3644: Die Verweisassemblys für Framework ".NETF
ramework,Version=v4.7.1" wurden nicht gefunden. Installieren Sie zum Beheben dieses Problems das SDK oder das Paket zur Festlegung von Zielversione
n für die vorliegende Frameworkversion, oder legen Sie als neues Ziel für die Anwendung eine Version des Frameworks fest, für die Sie das SDK oder 
Paket zur Festlegung der Zielversionen installiert haben. Assemblys werden im globalen Assemblycache (GAC) aufgelöst und anstelle von Verweisassemb
lys verwendet. Daher wird die Assembly für das gewünschte Framework unter Umständen nicht ordnungsgemäß als Ziel festgelegt. [C:\Users\chris\OneDri
ve\Desktop\FluentTerminal\FluentTerminal.SystemTray\FluentTerminal.SystemTray.csproj]
Das Projekt "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.SystemTray\FluentTerminal.SystemTray.csproj" (2) erstellt "C:\Users\chri
s\OneDrive\Desktop\FluentTerminal\FluentTerminal.App.Services\FluentTerminal.App.Services.csproj" (3) auf Knoten "1" (Standardziele).
C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.App.Services\FluentTerminal.App.Services.csproj(1,1): error MSB4041: Der MSBuild-XML-
Namespace muss der Standard-XML-Namespace des Projekts sein. Wenn das Projekt im MSBuild 2003-Format erstellt wurde, fügen Sie dem <Project>-Elemen
t xmlns="http://schemas.microsoft.com/developer/msbuild/2003" hinzu. Wenn das Projekt im alten Format 1.0 oder 1.2 erstellt wurde, konvertieren Sie
 es in das MSBuild 2003-Format.
Die Erstellung des Projekts "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.App.Services\FluentTerminal.App.Services.csproj" ist abg
eschlossen (Standardziele) -- FEHLER.

Das Projekt "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.SystemTray\FluentTerminal.SystemTray.csproj" (2) erstellt "C:\Users\chri
s\OneDrive\Desktop\FluentTerminal\FluentTerminal.Models\FluentTerminal.Models.csproj" (4) auf Knoten "1" (Standardziele).
C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.Models\FluentTerminal.Models.csproj(1,1): error MSB4041: Der MSBuild-XML-Namespace mu
ss der Standard-XML-Namespace des Projekts sein. Wenn das Projekt im MSBuild 2003-Format erstellt wurde, fügen Sie dem <Project>-Element xmlns="htt
p://schemas.microsoft.com/developer/msbuild/2003" hinzu. Wenn das Projekt im alten Format 1.0 oder 1.2 erstellt wurde, konvertieren Sie es in das M
SBuild 2003-Format.
Die Erstellung des Projekts "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.Models\FluentTerminal.Models.csproj" ist abgeschlossen (
Standardziele) -- FEHLER.

Die Erstellung des Projekts "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.SystemTray\FluentTerminal.SystemTray.csproj" ist abgesch
lossen (Standardziele) -- FEHLER.

Das Projekt "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.sln" (1) erstellt "C:\Users\chris\OneDrive\Desktop\FluentTerminal\Fluent
Terminal.RuntimeComponent\FluentTerminal.RuntimeComponent.csproj" (5) auf Knoten "1" (Standardziele).
C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.RuntimeComponent\FluentTerminal.RuntimeComponent.csproj(123,3): error MSB4019: Das im
portierte Projekt "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets" wurde nicht gefunden. Verge
wissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datenträger vorhanden ist.
Die Erstellung des Projekts "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.RuntimeComponent\FluentTerminal.RuntimeComponent.csproj"
 ist abgeschlossen (Standardziele) -- FEHLER.

Das Projekt "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.sln" (1) erstellt "C:\Users\chris\OneDrive\Desktop\FluentTerminal\Fluent
Terminal.App.ViewModels\FluentTerminal.App.ViewModels.csproj" (6) auf Knoten "1" (Standardziele).
C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.App.ViewModels\FluentTerminal.App.ViewModels.csproj(1,1): error MSB4041: Der MSBuild-
XML-Namespace muss der Standard-XML-Namespace des Projekts sein. Wenn das Projekt im MSBuild 2003-Format erstellt wurde, fügen Sie dem <Project>-El
ement xmlns="http://schemas.microsoft.com/developer/msbuild/2003" hinzu. Wenn das Projekt im alten Format 1.0 oder 1.2 erstellt wurde, konvertieren
 Sie es in das MSBuild 2003-Format.
Die Erstellung des Projekts "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.App.ViewModels\FluentTerminal.App.ViewModels.csproj" ist
 abgeschlossen (Standardziele) -- FEHLER.

Die Erstellung des Projekts "C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.sln" ist abgeschlossen (Standardziele) -- FEHLER.


Fehler beim Buildvorgang.

"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.sln" (Standardziel) (1) ->
"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.SystemTray\FluentTerminal.SystemTray.csproj" (Standardziel) (2) ->
(GetReferenceAssemblyPaths Ziel) -> 
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1097,5): warning MSB3644: Die Verweisassemblys für Framework ".NE
TFramework,Version=v4.7.1" wurden nicht gefunden. Installieren Sie zum Beheben dieses Problems das SDK oder das Paket zur Festlegung von Zielversio
nen für die vorliegende Frameworkversion, oder legen Sie als neues Ziel für die Anwendung eine Version des Frameworks fest, für die Sie das SDK ode
r Paket zur Festlegung der Zielversionen installiert haben. Assemblys werden im globalen Assemblycache (GAC) aufgelöst und anstelle von Verweisasse
mblys verwendet. Daher wird die Assembly für das gewünschte Framework unter Umständen nicht ordnungsgemäß als Ziel festgelegt. [C:\Users\chris\OneD
rive\Desktop\FluentTerminal\FluentTerminal.SystemTray\FluentTerminal.SystemTray.csproj]


"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.sln" (Standardziel) (1) ->
"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.SystemTray\FluentTerminal.SystemTray.csproj" (Standardziel) (2) ->
"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.App.Services\FluentTerminal.App.Services.csproj" (Standardziel) (3) ->
  C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.App.Services\FluentTerminal.App.Services.csproj(1,1): error MSB4041: Der MSBuild-XM
L-Namespace muss der Standard-XML-Namespace des Projekts sein. Wenn das Projekt im MSBuild 2003-Format erstellt wurde, fügen Sie dem <Project>-Elem
ent xmlns="http://schemas.microsoft.com/developer/msbuild/2003" hinzu. Wenn das Projekt im alten Format 1.0 oder 1.2 erstellt wurde, konvertieren S
ie es in das MSBuild 2003-Format.


"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.sln" (Standardziel) (1) ->
"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.SystemTray\FluentTerminal.SystemTray.csproj" (Standardziel) (2) ->
"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.Models\FluentTerminal.Models.csproj" (Standardziel) (4) ->
  C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.Models\FluentTerminal.Models.csproj(1,1): error MSB4041: Der MSBuild-XML-Namespace 
muss der Standard-XML-Namespace des Projekts sein. Wenn das Projekt im MSBuild 2003-Format erstellt wurde, fügen Sie dem <Project>-Element xmlns="h
ttp://schemas.microsoft.com/developer/msbuild/2003" hinzu. Wenn das Projekt im alten Format 1.0 oder 1.2 erstellt wurde, konvertieren Sie es in das
 MSBuild 2003-Format.


"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.sln" (Standardziel) (1) ->
"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.RuntimeComponent\FluentTerminal.RuntimeComponent.csproj" (Standardziel) (5) ->
  C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.RuntimeComponent\FluentTerminal.RuntimeComponent.csproj(123,3): error MSB4019: Das 
importierte Projekt "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets" wurde nicht gefunden. Ver
gewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datenträger vorhanden ist.


"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.sln" (Standardziel) (1) ->
"C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.App.ViewModels\FluentTerminal.App.ViewModels.csproj" (Standardziel) (6) ->
  C:\Users\chris\OneDrive\Desktop\FluentTerminal\FluentTerminal.App.ViewModels\FluentTerminal.App.ViewModels.csproj(1,1): error MSB4041: Der MSBuil
d-XML-Namespace muss der Standard-XML-Namespace des Projekts sein. Wenn das Projekt im MSBuild 2003-Format erstellt wurde, fügen Sie dem <Project>-
Element xmlns="http://schemas.microsoft.com/developer/msbuild/2003" hinzu. Wenn das Projekt im alten Format 1.0 oder 1.2 erstellt wurde, konvertier
en Sie es in das MSBuild 2003-Format.

    1 Warnung(en)
    4 Fehler

Verstrichene Zeit 00:00:01.08
PS C:\Users\chris\OneDrive\Desktop\FluentTerminal>`

**Comment by skipmeister123** [comment]
Erm. Uh.

Do you *have* Visual Studio? It's free, ya know? (Basically, I don't read enough German to know what's wrong, and VS is free, so..... why are you making it harder on yourself than it needs to be? :))

**Comment by skipmeister123** [comment]
OH, also, " Any CPU" should be "x64". This is called out specifically in the build instructions...

**Comment by skipmeister123** [comment]
(Google Translate for the win)

I'm guessing that's probably your issue.  Did you read the docs I pointed to before? :P

**Comment by christianmende** [comment]
A bit xD, but normaly msbuild is enough….. But i only got Visual Studio Code hahaha

**Comment by skipmeister123** [comment]
You are killing me.

https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=15#

Click that link, follow the instructions I linked before.  You're awesome, but... I'm going to start drinking (more) if you don't do the simple thing and grab the proper IDE XD

**Comment by christianmende** [comment]
I am doing it tommorow...

**Comment by skipmeister123** [comment]
I'll allow it.

**Comment by christianmende** [comment]
Ok, now i am installing it.
