### ISSUE TITLE
App crashes when fails to start the shell process

### ISSUE THREAD

**Issue by luisduenas** [felixse/FluentTerminal#263]
I was playing around with the FluentTerminal and i notice that by default i have the WSL profile even when i don't have wsl.exe in my PC:

![image](https://user-images.githubusercontent.com/16164843/55168951-1a6b5580-5131-11e9-8db8-1217cf26d67d.png)

I set it as default and closed FluentTerminal.

Then, when i try to open it again shows this message and closes

![image](https://user-images.githubusercontent.com/16164843/55168690-826d6c00-5130-11e9-9660-635d52e2314a.png)

I don't have much free time right know to send a pull request but i can give it a look in the weekend.

Also, there's a easy way to install the app, just right click ```Add-AppDevPackage.ps1``` and select ```Run with PowerShell``` and it will install the certificate and everything automatically, i can update the README if you want to.

**Comment by felixse** [comment]
This has been fixed in the meantime
