### ISSUE TITLE
Can this be run on Windows 8.1?

### ISSUE THREAD

**Issue by E3V3A** [felixse/FluentTerminal#264]
Has anyone tried to beat this into running on a Windows 8.1 machine?  
(Fully updated and using PWSH 6.1.1.) 

I made a lame try running the Install.ps1 but it responded with a certificate error even though I installed the cert according to README.

**Comment by ericcornelissen** [comment]
I don't think, also see #219

> All of the target frameworks (eg, UWP) are available only on windows 10.

However, it is kind of interesting you get the certificate error when you installed it :thinking: But I'm no expert on that, there might be a perfectly reasonable explanation...

**Comment by E3V3A** [comment]
I get: 
```
Error: The package or bundle is not digitally signed or its signature is corrupted.
Press Enter to continue...:
```

**Comment by felixse** [comment]
You need at least Windows 1709 (UAP Framework 10.0.16299.0). I don't think thats something you can patch into Windows 8.1.

**Comment by E3V3A** [comment]
> I don't think thats something you can patch into Windows 8.1.

I'm sure you can, but certainly not trivial. Everything about this article
* https://msdn.microsoft.com/magazine/dn973012.aspx


> If you’re comfortable with Windows 8 universal app development, then building Windows apps targeting the UAP should feel like home cooking. Windows apps don’t target Windows 10; the UAP is the target and it’s decoupled from the Windows SKU. UAP increments versions at a cadence apart from Windows. This means Windows apps won’t need to retarget every time the Windows OS revs. Windows apps target one or more UAP versions and test for those capabilities just as they test for device capabilities. This flexible approach gives you a nice, clean way to take advantage of future capabilities.
> 
> Building a Windows app means your app can run on any Windows device. This gift comes with a real-world caveat: The UAP can run your app, but only developers and designers can make the UI and the code adapt to deliver the best possible UX. If you want to build separate device-specific binaries, you can do that. But, should you choose to build a Windows app that supports multiple device types, all the tooling and infrastructure is in place and ready to make you successful.


...seem to indicate that all the framework is already there. But surely MS would never admit or support such a hack. Since so many UAP apps (including Office 2016) are already compatible with W8.1, my guess is that for our purposes, it should be doable by only replacing/adding some of the framework files. 

Perhaps some or more of these?
```
Win32/GlobalHotKey.dll
Win32/PListNet.dll
Win32/winpty.NET.dll
Microsoft.Graphics.Canvas.dll
Robmikh.CompositionSurfaceFactory.dll
Win32/Serilog.Sinks.File.dll
Win32/Serilog.dll
Win32/Serilog.Sinks.Async.dll
Win32/System.Net.Sockets.dll
Win32/System.Security.SecureString.dll
Win32/System.IO.Compression.dll
Win32/System.Globalization.Extensions.dll
Win32/System.Diagnostics.Tracing.dll
Win32/System.Diagnostics.StackTrace.dll
Win32/System.Data.Common.dll
Win32/System.Threading.Overlapped.dll
Win32/System.Security.Cryptography.Algorithms.dll
Win32/System.Net.Http.dll
Win32/System.Xml.XPath.XDocument.dll
Win32/System.Runtime.Serialization.Primitives.dll
Win32/Newtonsoft.Json.dll
Win32/winpty.dll
Win32/Autofac.dll
Win32/RestSharp.dll
clrcompression.dll
Win32/FluentTerminal.Models.dll
Win32/FluentTerminal.App.Services.dll
FluentTerminal.App.dll
Win32/GlobalHotKey.dllPK
Win32/PListNet.dllPK
Win32/winpty.NET.dllPK
Microsoft.Graphics.Canvas.dllPK
Robmikh.CompositionSurfaceFactory.dllPK
Win32/Serilog.Sinks.File.dllPK
Win32/Serilog.dllPK
Win32/Serilog.Sinks.Async.dllPK
Win32/System.Net.Sockets.dllPK
Win32/System.Security.SecureString.dllPK
Win32/System.IO.Compression.dllPK
Win32/System.Globalization.Extensions.dllPK
Win32/System.Diagnostics.Tracing.dllPK
Win32/System.Diagnostics.StackTrace.dllPK
Win32/System.Data.Common.dllPK
Win32/System.Threading.Overlapped.dllPK
Win32/System.Security.Cryptography.Algorithms.dllPK
Win32/System.Net.Http.dllPK
Win32/System.Xml.XPath.XDocument.dllPK
Win32/System.Runtime.Serialization.Primitives.dllPK
Win32/Newtonsoft.Json.dllPK
Win32/winpty.dllPK
Win32/Autofac.dllPK
Win32/RestSharp.dllPK
clrcompression.dllPK
Win32/FluentTerminal.Models.dllPK
Win32/FluentTerminal.App.Services.dllPK
FluentTerminal.App.dllPK
```

Don't you find it funny, that you can run these apps on just about any HW and device, but not on same HW using W8.1, but all other above. So my take is that, as long as W8 is getting OS updates, it should be possible to patch or build for.

**Comment by E3V3A** [comment]
The major OS version numbers are probably not as important as MS want you to believe. What is important are the last 5 digits of these:
```
  OS BuildLabEx         : 9600.19304
  OS HAL                : 6.3.9600.18969
  OS Kernel             : 6.3.9600.18217
  OS UBR                : 19302
```
![device-family-tree 1](https://user-images.githubusercontent.com/194392/55194457-a7e68e00-51a1-11e9-8fe6-5dc66cb0e6d1.png)

![selectiotextensionsdk 1](https://user-images.githubusercontent.com/194392/55194492-be8ce500-51a1-11e9-955f-b9c9ab08860c.png)

**Comment by felixse** [comment]
Interesting idea, looking forward to hearing your progress on this (if you really want to do this).
But I don't think this something we can or should support in an official way.
