### ISSUE TITLE
how can I get the FluentTermianl open directly with kerboard shortcuts

### ISSUE THREAD

**Issue by jameslahm** [felixse/FluentTerminal#267]

**Comment by wp999** [comment]
place  it anywhere on the taskbar  and press`windows logo key` + numeric keys corresponding to the position.

**Comment by jameslahm** [comment]
thx

**Comment by ericcornelissen** [comment]
More generally you can use the first keyboard shortcut in the settings (forgot the name) to toggle the FluentTerminal window as long as the process is running

**Comment by jameslahm** [comment]
@ericcornelissen get it，thx
