### ISSUE TITLE
Fluent terminal should automatically exclude failed startup options

### ISSUE THREAD

**Issue by wp999** [felixse/FluentTerminal#268]
I use  the WSL as the default startup item, while I uninstall it, Fluent would not revert to the default settings and cannot Start, I can only reset the app by System setting it, which are a bad experience

**Comment by felixse** [comment]
You should be able to access the settings from the SystemTray to change your default profile. Or else open the settings by calling `flute settings` in CMD/Powershell

**Comment by wp999** [comment]
thx🙂
