### ISSUE TITLE
Random dirty pixels when using block-style cursor

### ISSUE THREAD

**Issue by edward-p** [felixse/FluentTerminal#269]
I don't know what is this, so I just call it `dirty pixels`
![Annotation 2019-03-29 174833](https://user-images.githubusercontent.com/7891089/55224340-43800900-524b-11e9-9e62-f67ddb65d412.jpg)
![Annotation 2019-03-29 175844](https://user-images.githubusercontent.com/7891089/55225027-ab831f00-524c-11e9-9a62-39e03e452715.jpg)

It is seems that happens only with block-style cursor. I can't reproduce it when using other cursor styles.

**Comment by skipmeister123** [comment]
I tend to get this issue, as well.

**Comment by felixse** [comment]
This is already tracked in #149
