### ISSUE TITLE
`Open FluentTerminal here` fails for directories nested 4 levels deep (and above)

### ISSUE THREAD

**Issue by okeyokoro** [felixse/FluentTerminal#273]
FluentTerminal simply opens in the home directory (or it ignores you completely)

### system specs
make: Lenovo G50-70
processor: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz 2.60GHz
ram: 12.0 GB
system type: 64-bit operating system, x64-based processor
windows edition: Windows 10 Pro
windows version: 1803

### app details
FluentTerminal Version: 0.4.1.0
default terminal: CMD

### steps to reproduce
0. download FluentTerminal 0.4.1.0
1.  create a directory in your home directory
2.  create a directory within the directory you just created
3. repeat __step 2__ twice
4. try to launch FluentTerminal from the context menu

**Comment by felixse** [comment]
What was the problem?
