### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by moigagoo** [felixse/FluentTerminal#276]
I keep Fluent Terminal always running. Pwsh startup is too slow to run it everytime I need a terminal, and I need a terminal pretty often.

So, it'd be great to have Fluent Terminal minimized in tray instead of taskbar. It's an app that's always running, no need to show it in the taskbar until it's visible.

**Comment by felixse** [comment]
I'm afraid this won't be possible until Microsoft releases some API for UWP apps to use.
You can vote on this proposal here: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/12817866-uwp-system-tray-support
