### ISSUE TITLE
Unicode characters sometimes cause screen corruption

### ISSUE THREAD

**Issue by mjs** [felixse/FluentTerminal#282]
The following output was created with:
```bash
while true; do echo ☎ ;done
```
With Ctrl-C being used to stop it. 

![image](https://user-images.githubusercontent.com/14993/55369632-d83c7c80-5553-11e9-88e4-c4519866ed8c.png)

You can see the unicode telephone character is partially left behind at the bottom right of the screen. The `clear` shell command does not remove it, nor does a FluentTerminal clear (Ctrl-L).

**Comment by skipmeister123** [comment]
We had another bug filed recently like this.  It's also something I've seen, myself.

**Comment by mjs** [comment]
Another data point: the issue happens when "force WinPty" is on or off  (I'm on 1809).

**Comment by felixse** [comment]
Yes, this is #149 
Problem is somewhere in xterm.js, probably a compatibility issue with the Edge engine, since other terminals based on electron and xterm.js don't have this issue.
