### ISSUE TITLE
Command line configuration of fluent terminal

### ISSUE THREAD

**Issue by darkliquid** [felixse/FluentTerminal#283]
Is there a way I can configure fluent terminal from the command line? I'm trying to script the bootstrapping of my dev environment and would like to be able to import a theme, set it as the active theme and tweak a number of other config settings without having to actually manually open the app and do so.

**Comment by felixse** [comment]
so far not, but our command line parser is quite easy to extend 😉

**Comment by darkliquid** [comment]
In that case, is there a schema for all the settings that are currently supported? 

I was looking at https://github.com/felixse/FluentTerminal/blob/master/FluentTerminal.App.Services/Implementation/SettingsService.cs to try and figure out how the config works (and it looks like it is being stored as JSON in some cases, presumably encoded into the settings.dat file, basd on all the `WriteValueAsJson` calls in there). 

I was thinking about trying to add an `--import-config myconf.json` option that would allow importing all of the config from outside the app, but it's a little hard to know where to start, since I've never written a windows app before, nor worked with C#.

Any pointers welcome :)

**Comment by darkliquid** [comment]
Hmm, llooking at this: https://github.com/felixse/FluentTerminal/blob/master/FluentTerminal.App/App.xaml.cs#L230 am I understanding things correctly that if a `config.json` is placed in the _logging_ directory for fluent, it will import that?

**Comment by felixse** [comment]
That file is actually just configuring serilog, our logging framework.

Something to import a json config file sounds like a good approach. You would need to deserialize it using json.net (you can find something very similar in the theme parser) and pass the values to the settings service.

**Comment by darkliquid** [comment]
Ahh, cool. I shall have a poke around and see what I can come up with :)
