### ISSUE TITLE
Add --pre to install command

### ISSUE THREAD

**Issue by aashutoshrathi** [felixse/FluentTerminal#286]
Since this is pre-release, Chocolatey throws this error:
```
 - fluent-terminal - fluent-terminal not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
```

To fix this the README should contain the command `choco install --pre fluent-terminal` instead of `choco install fluent-terminal`

**Comment by felixse** [comment]
This might have happened because the update was not yet approved on chocolatey. I don't think this is necessary in general, maybe @pgalbraith can confirm this.

**Comment by pgalbraith** [comment]
Yes I suspect you got this error because you may have tried to install before the package was approved by the Chocolatey moderators.  Please try again now, and let us know if it works without the '-pre' argument.
