### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yukunshang** [felixse/FluentTerminal#287]
FluentTerminal conflicts with mobile usage.

**Comment by felixse** [comment]
I'm not quite sure what you mean, can you elaborate?

**Comment by yukunshang** [comment]
when I use mobileu usage, i cannot open it. 
![Uploading image.png…]()

**Comment by yukunshang** [comment]
![image](https://user-images.githubusercontent.com/25716306/55768710-84301b80-5ab0-11e9-8499-64e1d979f154.png)
I find i cannot open the mobile usage, when i install the fluentTerminal

**Comment by felixse** [comment]
I have no idea how this happens 😕 
You should report this to Microsoft, we shouldn't have any influence on this.
