### ISSUE TITLE
Different style from provided screenshot

### ISSUE THREAD

**Issue by aligulzar729** [felixse/FluentTerminal#288]
How to make the installed fluent terminal look like the one in screenshot provided by dev?

**Comment by mikemaccana** [comment]
What specifically do you mean? I think the cool prompt is powerline or similar.

**Comment by felixse** [comment]
I have written down my setup [here](https://github.com/felixse/FluentTerminal/wiki/FAQ#how-can-i-achieve-the-look-of-the-terminal-in-the-readme)
