### ISSUE TITLE
SSH implemented - let's discus design

### ISSUE THREAD

**Issue by peske** [felixse/FluentTerminal#289]
Hey @felixse and crew!

I'm member of a team that works on fork https://github.com/jumptrading/FluentTerminal. Although started with this only few days ago, we've already made first new feature: SSH. Here's 1 minute demo: https://youtu.be/9L63rujAZCs. We also plan to implement mosh...

We have few devs fully dedicated to this, and chances are that things will happen rapidly. For this reason we would like to talk with you guys about software design / implementing new features. Our plan is to upstream our work here (assuming that you want us to), so we would like to hear your guidelines, plans, etc., to be in sync. Maybe we can arrange a live chat meeting to discus that? Pls. contact me at peske.nis(at)gmail.com.

Thanks for your great work!

**Comment by felixse** [comment]
Looks awesome, thanks for picking this up 👍 
I will send a mail to further discuss collaborating.
