### ISSUE TITLE
Allow changing background opacity of built-in themes

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#29]
The background opacity slider should be available for built-in themes (good solution), or be configured as a global property separate from a given theme (ideal solution)

**Comment by felixse** [comment]
Global property would be fine for me, might also make importing iTerm themes easier

**Comment by skipmeister123** [comment]
Agreed. That's probably the best way to go.

**Comment by felixse** [comment]
Background opacity is global now
