### ISSUE TITLE
Feature Request: Allow scrolling down another page

### ISSUE THREAD

**Issue by TChristoph** [felixse/FluentTerminal#297]
I am very happy that I have discovered this great software!

I would like to be able to scroll one page further down so that I can always position the current input line anywhere, up to the top of the screen. You know this from almost every code editor or even built-in cmd/PowerShell:

![image](https://user-images.githubusercontent.com/38782922/55672460-ac92fc80-589b-11e9-9b8f-7193cbe07484.png)
Please notice there is free space under the last command line but the command history is longer than one screen page.

I would prefer a setting that you maximally can scroll one more page, so the input line cannot disappear but be freely positioned on the screen. This is the standard you might be accustomed to by Visual Studio (Code).

I am looking forward to your reactions!

**Comment by felixse** [comment]
This is nothing we can do on our side, this is handled by [xterm.js](https://github.com/xtermjs/xterm.js)

**Comment by TChristoph** [comment]
Okay, opened [an issue](https://github.com/xtermjs/xterm.js/issues/2001) there.
