### ISSUE TITLE
Background opacity when inactive

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#30]
I'd like the option to only make the background transparent/translucent when the window is not focused.

**Comment by felixse** [comment]
I'm afraid this won't be possible since UWP is not allowing transparency on non focused windows.

**Comment by TailyFair** [comment]
Is it still the case? https://github.com/JasonStein/Notepads seems to stay transparent even if not in focus.

**Comment by felixse** [comment]
Just gave it a try and itbehaves the same on my devices(1809 and 1903)
