### ISSUE TITLE
Updates break functionality

### ISSUE THREAD

**Issue by clragon** [felixse/FluentTerminal#302]
When an update is available, the app seems to forget to actually start the terminal and I'm stuck with just a blank screen. 

Edit: nevermind me, this seems to be just a random chance of completely breaking down and doing nothing. This sadly makes this emulator pretty useless, since I dont wanna spend 10 minutes on trying to open a terminal. It also ruins the explorer integration.

**Comment by ericcornelissen** [comment]
Seems to be the same problem as #206. It is unfortunate I agree, as [said here](https://github.com/felixse/FluentTerminal/issues/206#issuecomment-478229692) could you provide your log data @clragon?

**Comment by clragon** [comment]
I already unnistalled it, but I'll try to look into it later.

By the way, uninstalling doesnt remove the context menu entry.

**Comment by ericcornelissen** [comment]
> I already unnistalled it, but I'll try to look into it later.

Don't worry about it if you think it takes too much time 😉


> By the way, uninstalling doesnt remove the context menu entry.

Is it correct that you installed that separately? If so, the `Uninstall.bat` script [over here](https://github.com/felixse/FluentTerminal/tree/master/Explorer%20Context%20Menu%20Integration) will remove it for you.

**Comment by clragon** [comment]
Oh, very interesting.
I installed it with the appx bundle file.
