### ISSUE TITLE
Feature Proposal: History and reopen closed tabs

### ISSUE THREAD

**Issue by TChristoph** [felixse/FluentTerminal#303]
This is basically what you know from almost every browser when pressing `Ctrl + H` resp. `Ctrl + Shift + T`. You could then open tabs closed recently and continue with their session, or even search the full history for a certain command or something like this.

I think it would not cost incredibly high storage to save each terminal session, if the user would like so. To make a session serializable, the data to save for the moment could be restricted to the list of input and output strings - as it might be more expensive to even save local PowerShell variables etc., or even all active associated processes. (Over the long term, you could still consider if certain shells are easilly serializable, maybe via [`Export-Session`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-pssession?view=powershell-6)).

Introducing history would also allow implementation of other new features:

- **Set tabs aside,** as known from Edge.
- **Time line support.**

Looking forward to your opinions.

**Comment by felixse** [comment]
I don't think there is any feasible solution to store the state of shell process. We don't even have the means to reliable tell in which directory the process was when it exited.

It's an interesting idea, but in my opinion totally out of scope for this project
