### ISSUE TITLE
I can't open 2 windows of terminal 

### ISSUE THREAD

**Issue by GodOxidus** [felixse/FluentTerminal#305]
Allow opening 2 or more windows of FluentTerminal. 
It will be useful for split screen and show many terminals, or use in different workspaces.

**Comment by ericcornelissen** [comment]
Did you try opening a second window using <kbd>Ctrl</kbd> + <kbd>N</kbd>? That is the default keybinding for opening a new FluentTerminal window (a GUI button will be available as soon as #196 is merged).

**Comment by GodOxidus** [comment]
The second window lost opacity.

**Comment by felixse** [comment]
Only the active window can have acrylic effects. This is restricted by Windows
