### ISSUE TITLE
[feature request] Open a new window per every virtual desktop

### ISSUE THREAD

**Issue by brukbrhane** [felixse/FluentTerminal#306]
Can you make it possible to make a new window whenever you go to another virtual desktop where the first window wasn't opened and try to open Fluent-terminal?

EDIT:
I found [this](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp) link to further explain what I mean and also provide how to implement it. Alternatively, instead of making multiple instances of the application it might be less complicated to use [this](https://msdn.microsoft.com/en-us/library/windows/apps/dn434070.aspx)

**Comment by AndrewKralovec** [comment]
Yeah, you are going to want a new instance. Multiple view will still be on share the same window.

**Comment by felixse** [comment]
Resolved by #513
