### ISSUE TITLE
[Feature request] : update the app icon for Windows Light theme

### ISSUE THREAD

**Issue by leoktsbnsk** [felixse/FluentTerminal#307]
See, the icon is transparent and white when the theme is black but gains a colored background when the theme is white. 
See example of a Mail app icon behaviour:
![image](https://user-images.githubusercontent.com/30351651/55733333-ed1a8380-5a1d-11e9-93e6-f6b5e84227cf.png)
![image](https://user-images.githubusercontent.com/30351651/55733344-f0157400-5a1d-11e9-96ad-229607bfd49c.png)

Thank you!

**Comment by mikemaccana** [comment]
Done in https://github.com/felixse/FluentTerminal/pull/290

**Comment by felixse** [comment]
This is tracked in #203
