### ISSUE TITLE
enhancement: meanings of color palette. Which is which?

### ISSUE THREAD

**Issue by ghost** [felixse/FluentTerminal#308]
First of all, I'd like to thank you, all contributor, for creating such a cool terminal emulator. 

This issue is related to the color palette in "Settings > Themes".

Now each color's meaning (for example, normal text, highlighted text, background, ls command related color and so on) is not indicated.
So almost all of us cannot create the new theme, I guess.

It is helpful if descriptions that which color is assigned which part of the console.

**Comment by skipmeister123** [comment]
This is something I've been thinking about recently.  I might give a stab 
at a mock-up to help clarify.

**Comment by kzymtn** [comment]
Thank you for the quick reply. And I am glad to hear that you are already getting started with that.
I am looking forward to the completion of that.

**Comment by skipmeister123** [comment]
As an example, here's how [Terminus ](https://eugeny.github.io/terminus/)handles it.

![image](https://user-images.githubusercontent.com/1911919/55920057-4b826600-5bc6-11e9-97f0-59f913080a29.png)

**Comment by kzymtn** [comment]
thanks to showing an example. I think that the Terminus example gives enough information.

**Comment by felixse** [comment]
![image](https://user-images.githubusercontent.com/30559812/75609401-79d3a180-5b08-11ea-858d-68979874d19f.png)

Themes settings are now a bit more verbose. I'm not a fan of adding some example like Terminus does, since the usage of the colors is very dependent on what kind of shell and how it is configured.
