### ISSUE TITLE
Editing profile name changes the arguments fields instead; no way to name a profile

### ISSUE THREAD

**Issue by moigagoo** [felixse/FluentTerminal#31]
While adding a new profile, it doesn't matter what name you enter. The profile will be saved as “New Profile” anyway.

Also, “Arguments” field gets populated as you type in “Name,”

![image](https://user-images.githubusercontent.com/1045340/40766035-4ec6193c-64bf-11e8-87fc-8dde5b0036d7.png)

P.S. Congrats on a new release! Thank you so much for the time and effort you spend on FluentTerminal, I really love it!

**Comment by felixse** [comment]
Yeah, stupid mistake 😅 
This is already fixed on master, I will create a new release soon.

Your  title bar buttons look strange, guess I should work on some optimizations for the 'colored title bar' setting.
