### ISSUE TITLE
Thoughts - is tray icon used / needed?

### ISSUE THREAD

**Issue by mikemaccana** [felixse/FluentTerminal#312]
Just wondering if you think this feature is necessary @felixse. You might be able to remvoe it without anyone caring. 

 - Fluent Terminal is an app, not something that's monitored (like wifi connection or antivirus or volume) 
 - Apps having their own system try icons was common in Windows XP but isn't that common anymore
 - We already have the taskbar where items can be pinned if we need persistent launchers
 - I can see zero bugs to do with the system try icon  nobody seems to be using it
 - The ysstem try icon is hidden by default, so users won't see it

I suspect Fluent Terminal would be better without the tray icon clogging up space. Totally up to you though @felixse

**Comment by skipmeister123** [comment]
I tend to agree with this. I don't need *more* stuff cluttering my system tray.  However, since we just introduced the option to hide it from the system tray, I think we need to leave it there until we're certain that we can get away with removing the option entirely.  My suggestion, for the next couple versions, is to make the default option to hide the system tray icon, rather than removing it entirely.  If we don't get any bug reports in the next few months, we can remove it.

**Comment by felixse** [comment]
The SystemTray is actually hosting the shell processes, so no way we can just remove it. Also toggle window wouldn't work anymore.
We can hide it, but this leads to no way quit the tray process besides the Task Manager (we need to restart it if we want to refresh the environment variables that are passed to the shell process).

**Comment by mikemaccana** [comment]
> We can hide it, but this leads to no way quit the tray process besides the Task Manager

Killing 'FluentTerminal' the app in Task Manager seems to kill everything: 

![image](https://user-images.githubusercontent.com/172594/55833013-b8d2c000-5b0e-11e9-94e6-c60b4edc6353.png)

I'm comfortable using Task Manager to kill processes on Windows. I susepct most users are used to using Task Manager, and very few know Fluent can have anything restarted via the system tray icon.

**Comment by skipmeister123** [comment]
Can exiting the last shell also kill the tray process?

**Comment by felixse** [comment]
We could, but then I couldn't spawn a new window with the toggle screen keybinding, and I like this feature 😅

**Comment by MrBMT** [comment]
Would it perhaps be possible to add a toggle within settings to control this behaviour? e.g. "Quit on last terminal closed" or something along those lines?

**Comment by TailyFair** [comment]
I actually really like option to have fluent always available in icons tray. I often close and re-open terminals, so just double clicking on icon is super convenient and I use it constantly.

**Comment by mikemaccana** [comment]
> I often close and re-open terminals, so just double clicking on icon is super convenient and I use it constantly.

@TailyFair Why don't you use the taskbar to launch apps?

**Comment by themobiledev** [comment]
Count me in as wanting the background process to close after the last terminal is closed. I don't use the system tray icon and I find it inconvenient to have to keep the process when I want to refresh my path (or other environment variables).

**Comment by TailyFair** [comment]
While I was in support for keeping icon tray. After using fluent-terminal extensively, I never actually used icon tray.
I think it's not really needed.

**Comment by MarcAnt01** [comment]
I like tray icons in UWPs, but in the case of Fluent Terminal I don't find it necessary, having an option to hide it would be great, but according to what I've read it's not possible

**Comment by skipmeister123** [comment]
There's already an option to hide it. I think it's nice to have, and have 
recently taken to leaving it on. If you change an environment variable, it 
won't be picked up until the FT process is restarted. Personally, I'd like 
to see the tray icon improved to include a restart option, instead of just 
quit.

**Comment by MarcAnt01** [comment]
Thanks, I missed it.

**Comment by felixse** [comment]
I think this can be closed now
