### ISSUE TITLE
Terminus

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#315]
I think we should be talking to these guys.  Their UI is way better than ours. 😅

Also, why can't we specify environment variables, like they do? 🤔

![image](https://user-images.githubusercontent.com/1911919/55920151-c0ee3680-5bc6-11e9-846a-e39fb6d79ada.png)

**Comment by felixse** [comment]
Well, that's subjective 😄 

The environment variable editor is missing because nobody asked for it so far. Would be no problem to add one. Of course they have a few more features than us, but they are also around for a bit longer

**Comment by TomerZeitune** [comment]
Unlike Terminus, Fluent terminal follows the Microsoft design language. it blends better with Windows 10.

**Comment by AndrewKralovec** [comment]
I agree with TomerZeitune, it blends with windows better. As for the missing features, are there any they have that were requested by the community?

**Comment by MrBMT** [comment]
Funnily enough, I just switched from using Terminus to FluentTerminal yesterday; personally I much prefer FluentTerminal's UI over it (it also loads _much_ more quickly).

**Comment by vasiby** [comment]
>  missing features, are there any they have that were requested by our community?

Please remove the certificate installation requirement

**Comment by skipmeister123** [comment]
That requirement can only go away once the app is submitted/approved to the Microsoft Store.

**Comment by felixse** [comment]
Environment variables are editable now, and maybe we can get this submitted to the Store soon 🤞
