### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by TomerZeitune** [felixse/FluentTerminal#318]
How can I open fluent terminal from the command line and cd to a specific directory? 
What I tried :
`explorer.exe shell:appsFolder\53621FSApps.FluentTerminal_87x1pks76srcp!App
`
works but does let me specify a directory.

**Comment by skipmeister123** [comment]
Take a look here.

https://github.com/felixse/FluentTerminal/wiki/Command-Line-Arguments
