### ISSUE TITLE
SSH host in tab

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#32]
If I'm SSH'd to a host, I'd like to have the hostname prepended to the tab

**Comment by felixse** [comment]
I don't think this can be done here since it is very dependent on what you are using for SSH. You can configure a title change in your remote shell profile, or create a wrapper like it is described here: https://ondergetekende.nl/setting-terminal-title-to-ssh-hostname.html

**Comment by skipmeister123** [comment]
That's reasonable.
