### ISSUE TITLE
Increase active tab contrast?

### ISSUE THREAD

**Issue by mikemaccana** [felixse/FluentTerminal#322]
Right now the active tab contrast is a little too subtle:

![image](https://user-images.githubusercontent.com/172594/56141898-9ff65e80-5f95-11e9-9b88-7e41673504e1.png)

Comapre with, say, vsode:

![image](https://user-images.githubusercontent.com/172594/56142172-1abf7980-5f96-11e9-83e7-76e3b78d78ab.png)

It might be better to make the active tab pop out a little more by darkening it.

**Comment by felixse** [comment]
We are using the Windows accent color for the active tab, which seems to be gray in your case. We could add an option to define a custom accent color 🤔

**Comment by mikemaccana** [comment]
TBH I think this is my prob, and I'd rather not add extra settings that don't need to be there!
