### ISSUE TITLE
How to configure fluent Terminal to open in current directory in Visual studio  with Open Command Line extension?

### ISSUE THREAD

**Issue by iAmBipinPaul** [felixse/FluentTerminal#324]
Here is the extension link
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.OpenCommandLine

**Comment by felixse** [comment]
![image](https://user-images.githubusercontent.com/30559812/56417090-1f847600-6293-11e9-9c46-22b5b17a174f.png)

**Comment by iAmBipinPaul** [comment]
Thanks @felixse 👍  !
