### ISSUE TITLE
How to have FluentTerminal use Ubuntu instead of WSL?

### ISSUE THREAD

**Issue by wolf99** [felixse/FluentTerminal#326]
The WSL profile that comes with FluentTerminal by default calls `C:\windows\system32\wsl.exe`
This operates a little differently to running (for e.g.) `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\ubuntu.exe`

I have tried selecting the latter as the "Shell executable location" for a new profile, but when clicking "open" in the file dialog, it results in the error:

    Open
    ubuntu.exe
    The file cannot be accessed by the system

How can I have FluentTerminal run a particular distro on WSL, rather than just WSL.exe?
(Or failing that, how can I at least set the WSL default working directory to ~ ?)

**Comment by skipmeister123** [comment]
The second one is easy: just use ~ as the argument, rather than the working 
directory 😄

**Comment by wolf99** [comment]
Hi @skipmeister123, unfortuntely this results in an error:

![image](https://user-images.githubusercontent.com/281700/56390554-35a71d80-6224-11e9-88a5-70d79bcbc82c.png)

**Comment by skipmeister123** [comment]
It should look something like this:

**Comment by felixse** [comment]
Here is how to select a specific distribution: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#run-a-specific-distribution
You would need to add this to the arguments. Or set ubuntu as default distribution once.

**Comment by wolf99** [comment]
Thanks. Combining the two answers here I have used `~ --distribution ubuntu` which seems to cover wht I need.
