### ISSUE TITLE
Small UI improvement on tab titles

### ISSUE THREAD

**Issue by neilsustc** [felixse/FluentTerminal#33]
This is a really nice app. Thanks so much.

How about adding more margin after the tab title?

![image](https://user-images.githubusercontent.com/7588612/40834651-fb834de8-65c3-11e8-9510-e4afbf10bcd7.png)

Example from VSCode

![image](https://user-images.githubusercontent.com/7588612/40834892-a1ec24d4-65c4-11e8-9d32-331ab6cc9bb7.png)

**Comment by skipmeister123** [comment]
I was thinking yesterday how a tab highlight would be useful. Like when
you're on a tab in the settings page.

Hans Kokx

**Comment by felixse** [comment]
Yes, a little margin would look good there 😃 

@skipmeister123 tabs are currently highlighted by using the windows accent color, did you maybe set your accent color to some grey tone?

**Comment by skipmeister123** [comment]
Of course i did! 😅

Hans Kokx

**Comment by skipmeister123** [comment]
Thinking more on this... what if we had something like this:
![image](https://user-images.githubusercontent.com/1911919/40926007-25ac6f4c-67e9-11e8-8ed6-1426d4e95992.png)

**Comment by felixse** [comment]
Margin should be better know. Also added a option to underline the selected tab like @skipmeister123  suggested

**Comment by neilsustc** [comment]
Thanks
