### ISSUE TITLE
Stuck on Windows 10 1903

### ISSUE THREAD

**Issue by qwqVictor** [felixse/FluentTerminal#333]
I installed the FluentTerminal on my MacBook Pro with Windows 10 1903 installed on Windows To Go. When I launched it, it looks like very well. But I couldn't type anything or open its settings, and it just stuck. The CPU usage ratio also raised high on one core, but other cores were idle.

Version: 0.4.1.0
Windows 10 Version: 1903
CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70 GHz
RAM: 8GB DDR3
GPU: Intel(R) Iris(TM) Graphics 6100

**Comment by qwqVictor** [comment]
And I've found that 0.3.1 could work.

**Comment by cybercatgurrl** [comment]
I'm on 1903 and I don't have this issue.

**Comment by qwqVictor** [comment]
Maybe it's a rare problem.
