### ISSUE TITLE
"Failed to register hotkey" message on every startup

### ISSUE THREAD

**Issue by moshen** [felixse/FluentTerminal#337]
I get this message when I start fluent terminal, and sometimes when I open a new tab, or when I change anything in the settings:

![image](https://user-images.githubusercontent.com/168513/56853115-5856c780-68f1-11e9-9ef6-221ff2a5b592.png)

I looked for a "Scroll" hotkey in the settings but couldn't find one.

**Comment by felixse** [comment]
Some other app has this already registered. Scroll is used for toggle window by default. If you edit or remove this keybinding in the settings the error should no longer appear

**Comment by moshen** [comment]
I can't find anything in the settings that says it's bound to Scroll.  Is there a default?

**Comment by moshen** [comment]
Reinstalled the latest version and saw "Toggle Window" was bound to scroll.  Deleted the binding and problem solved.
