### ISSUE TITLE
[Suggestion] Taskbar jump list

### ISSUE THREAD

**Issue by klaidliadon** [felixse/FluentTerminal#338]
It would be really nice to have taskbar jump list of the available profile/shells when right clocking the taskbar icon (like Conmenu).

**Comment by zuozishi** [comment]
Like this?
![image](https://user-images.githubusercontent.com/20531439/57053314-bb64a780-6cbf-11e9-9638-3b83cb1f8099.png)

**Comment by skipmeister123** [comment]
That would be nice.

**Comment by zuozishi** [comment]
@skipmeister123 
Dude, you replied very quickly.

**Comment by skipmeister123** [comment]
Dude, I'm always watching. 😳

**Comment by klaidliadon** [comment]
Is there going to be a new release soon?

**Comment by felixse** [comment]
Yes, just some more polishing. Maybe next week
