### ISSUE TITLE
How to set Fluent Terminal as the default opener for *.bat files ?

### ISSUE THREAD

**Issue by LemingVan** [felixse/FluentTerminal#339]
Since Fluent Terminal is so cool, is there any way to set Fluent Terminal as the default opener for *.bat files ?

**Comment by Tommasov** [comment]
I tried to change the default "open with" for .bat files with C:\Users\Tommaso\AppData\Local\Microsoft\WindowsApps\flute.exe but it's not working.

It says: "flute.exe, The file cannot be accessed by the system"

Same result with a shortcut.

**Comment by jacekard** [comment]
Hi, I also would like to start some processes in different tabs using .bat file.
Is it possible? I tried to invoke flute.exe with path to the executable, but with no luck.

**Comment by felixse** [comment]
try ` flute run "cmd /c  path-to-your.bat"`

**Comment by jasp402** [comment]
> try ` flute run "cmd /c path-to-your.bat"`

![image](https://user-images.githubusercontent.com/8978470/88447280-29324d00-cdf7-11ea-9629-9296ddcc041a.png)

after that the app quits unexpectedly

**Comment by 0xNeffarion** [comment]
Kinda old to the party but here is how you do it

Create a file named fluent.reg with the following contents:


```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\batfile\shell\open\command]
@="\"C:\\Users\\YOUR_USER\\AppData\\Local\\Microsoft\\WindowsApps\\flute.exe\" run \"%1\" %*"
```

**Remember to replace YOUR_USER with your windows username**  

Then just save the file and double click it to import

**Comment by LemingVan** [comment]
Hi @0xNeffarion ,

Thank you for your help!  I think I can close this issue now.
