### ISSUE TITLE
Run new profile from current shell directory

### ISSUE THREAD

**Issue by Cobertos** [felixse/FluentTerminal#340]
It would be really nice if opening a new tab had the option of using the current shell directory. ConEmu sort of supports this. It syncs it's `%CD%` with the current shell so that you can set a new profile's working directory to `%CD%` and have it open in the last navigated shell directory. 

For shells like Git bash, this can be handled externally using `PROMPT_COMMAND`, but for cmd as friends I think this has to be supported at the shell host level (unless there's a technique I'm not familiar with).

**Comment by AndrewKralovec** [comment]
Seems related to 
https://github.com/felixse/FluentTerminal/issues/202#issuecomment-485914598

**Comment by felixse** [comment]
Tracked in #202
