### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by zuozishi** [felixse/FluentTerminal#345]
I fork and try ...
![image](https://user-images.githubusercontent.com/20531439/56969938-b78a3580-6b98-11e9-93fc-76b046b74837.png)
![image](https://user-images.githubusercontent.com/20531439/56969986-cbce3280-6b98-11e9-8277-06642ae16c88.png)

**Comment by skipmeister123** [comment]
We should be using a translation file with strings.

**Comment by zuozishi** [comment]
![image](https://user-images.githubusercontent.com/20531439/56970470-c4f3ef80-6b99-11e9-81a0-08531a587750.png)

Strings file

**Comment by skipmeister123** [comment]
👍🏻

**Comment by zuozishi** [comment]
So, I finish it and pull request?

**Comment by fbigun** [comment]
Very good feature ！✌️

**Comment by zuozishi** [comment]
#347
