### ISSUE TITLE
Some Color codes output is abnormal

### ISSUE THREAD

**Issue by DukeFox** [felixse/FluentTerminal#346]
## FluentTerminal
![ft.png](https://i.loli.net/2019/05/01/5cc8e0fb5cf65.png)

## PowerShell
![ps.png](https://i.loli.net/2019/05/01/5cc8e0fa7afa3.png)

## Terminus
![tm.png](https://i.loli.net/2019/05/01/5cc8e0fb8efe2.png)

How to fix it?

**Comment by skipmeister123** [comment]
We have had issues in the past with Asian language support. I wonder if 
this is related?

**Comment by DukeFox** [comment]
> We have had issues in the past with Asian language support. I wonder if this is related?

It seem unrelated with the language environment . The problem did not appear in [Terminus](https://github.com/Eugeny/terminus) .

**Comment by DukeFox** [comment]
Turn off the WinPty option to use ConPty will fix this problem.
