### ISSUE TITLE
Tab scrollbar overlaps tabs

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#35]
![image](https://user-images.githubusercontent.com/1911919/40924659-d4e37b8a-67e5-11e8-8fc7-f2d269c66950.png)

**Comment by felixse** [comment]
Yeah, I knew this will come up eventually 😄 

I guess we need a custom template for the scrollviewer here, tried it once but didn't get it to scroll correctly.

I will give this another try once we have to more important issues solved, but I would also be more than happy if some XAML hero wants to have a try on this.

**Comment by skipmeister123** [comment]
A thought on a possible solution: skip the scroll bar entirely, and have new tabs on either end with a simple < or > to scroll.

--
Hans Kokx
On 6/4/2018 11:50:40 AM, Felix <notifications@github.com> wrote:
Yeah, I knew this will come up eventually 😄
I guess we need a custom template for the scrollviewer here, tried it once but didn't get it to scroll correctly.
I will give this another try once we have to more important issues solved, but I would also be more than happy if some XAML hero wants to have a try on this.

**Comment by felixse** [comment]
Yeah, thats what I tried to implement, but didn't get the buttons to actually scroll.

I don't think it's impossible, just needs more than I was willing to invest when I tried
