### ISSUE TITLE
Bring to front automatically when using VMWare

### ISSUE THREAD

**Issue by yoavst** [felixse/FluentTerminal#352]
When I'm using vmware, FluentTerminal keep bringing itself to front and I can't get it stopped. If VMware is closed, then it behaves normally.

Is there a way I can help providing information to fix this issue?

**Comment by felixse** [comment]
Wild guess: change the keybinding that is configured for 'Toggle Window' and see if still happens

**Comment by yoavst** [comment]
Seems to work, thanks, I'll update if it is still a problem.
