### ISSUE TITLE
Stop Ctrl+W closing the window?

### ISSUE THREAD

**Issue by Daniel15** [felixse/FluentTerminal#353]
Whenever I press Ctrl+W, the window closes. This is quite annoying as `nano` uses Ctrl+W to search. I've accidentally closed my SSH connection (in Fluent Terminal) a few times now because of this. :)

Is there a way to disable this?

**Comment by PakornVl** [comment]
Settings -> KeyBindings -> Close tab -> Edit or Delete

**Comment by Daniel15** [comment]
Great! Thank you :D
