### ISSUE TITLE
Microsoft's new modern Windows Terminal

### ISSUE THREAD

**Issue by TomerZeitune** [felixse/FluentTerminal#355]
Today Microsoft unveiled a new terminal for windows "Windows Terminal" 
 Which should be out in about a month. I think this product is somewhat similar to Fluent Terminal but has a few advantages mainly the fact that it's from Microsoft. You can read some quick details here: https://www.theverge.com/2019/5/6/18527870/microsoft-windows-terminal-command-line-tool

I am wondering what this announcement means to the future of Fluent Terminal.

**Comment by spookyUnknownUser** [comment]
I just saw this, windows terminal looks like pretty much the perfect version of fluent terminal. I've loved my time with Fluent Terminal, it has stood out as an extremely well designed terminal if you don't want to use electron but don't mind not having your terminal written in rust. 

Press F to pay respects.

**Comment by felixse** [comment]
Well, lets see 😄
I don't know where this is going. If Microsoft delivers the perfect Terminal I'm happy to move on to new endeavors. If there is still a case for Fluent Terminal we just keep on improving it (maybe even adopt their renderer 😈)

**Comment by TomerZeitune** [comment]
Well, their project is surprisingly open sourced. 
You can try it here: https://github.com/Microsoft/Terminal.  
For official details from Microsoft:
https://devblogs.microsoft.com/commandline/introducing-windows-terminal

**Comment by Tommasov** [comment]
I tried the beta version but it's far behind compared to Fluent

**Comment by atrauzzi** [comment]
For people who have managed to try it out, is it worth enumerating the ways where fluent stands out and also anything it could benefit from or crib from the new terminal?

**Comment by chmielciu** [comment]
> For people who have managed to try it out, is it worth enumerating the ways where fluent stands out and also anything it could benefit from or crib from the new terminal?

No. I mean it works but lacks so many features and integrations with the system. 
It's not that bad in terms of critical bugs, but still in real life it has rather no utility.

At least it was the case for end of May when I built and tested it.
