### ISSUE TITLE
Is there any way to add shell arguments?

### ISSUE THREAD

**Issue by NDelt** [felixse/FluentTerminal#356]
For example, in VS Code, I can add shell arguments `["/K", "chcp 65001"]` for setting terminal's code page to 65001.

Can I add/use argument options like this in Fluent Terminal?

**Comment by ericcornelissen** [comment]
If you go to Settings (either <kbd>Ctrl</kbd>+<kbd>,</kbd> or via the hamburger menu) then "Profiles" from the side menu and select the profile you want to change and click "Edit", then in the "Arguments" input you can add the shell arguments you want to have.

Does that help @NDelt?

**Comment by NDelt** [comment]
@ericcornelissen Sorry for the late reply. It works fine. Thanks!
