### ISSUE TITLE
CLI refreshing errors and gets stuck

### ISSUE THREAD

**Issue by cybercatgurrl** [felixse/FluentTerminal#358]
Programs that redraw the screen a lot seem to get stuck and stop updating. This is evident when using vim under Windows (not WSL). The built-in Windows Command line and Powershell tools do not have this issue. It makes vim unusable. I really love Fluent Terminal and would hate to be forced to use something else.

The error comes up when moving up and down documents in vim. It just doesn't draw the new lines that are supposed to be coming in.

Edit: I tried gtop an npm package like htop but improved and it shows the same refreshing issues.

**Comment by felixse** [comment]
Did you experience this with the released version or current master? https://github.com/felixse/FluentTerminal/pull/299 might help, but not quite sure.
