### ISSUE TITLE
Please add support of light color schemes and a demo theme

### ISSUE THREAD

**Issue by ihodev** [felixse/FluentTerminal#36]
I've tried to play with colors, but it seems the app doesn't like the light color scheme (many controls aren't visible).

**Comment by ihodev** [comment]
![Settings](https://drive.google.com/uc?id=1k3fkEx1OWcfwWKRj7emFXAEgL8xwc7mD)
![App](https://drive.google.com/uc?id=1rcoNNktdCmApmkz-D6A9Tnp-w2xhZsMu)

**Comment by felixse** [comment]
We are using the dark theme be default right now, but it should be no problem to write some logic that switches between light and dark theme based on the background color of the theme

**Comment by felixse** [comment]
Should be working fine now, also added the 'Tomorrow' theme of Chris Kempson as a demo

**Comment by ihodev** [comment]
Should I build it? Or you'll prepare the release in the near future?

**Comment by felixse** [comment]
I will create a new release this week after adding some scrollback related features, but you can also clone and build it in the meanwhile

**Comment by ihodev** [comment]
Man, you are awesome! Downloading the latest release . . .

**Comment by ihodev** [comment]
![](https://drive.google.com/uc?id=1OxvqL1qI3sJerK4uXWJY7Z-lib_qOtDf)

What am I doing wrong?

**Comment by felixse** [comment]
😨 
Does it say anything about which file is missing?
What version of Windows 10 are you using? 32 or 64 bit?

**Comment by ihodev** [comment]
I've tested only on this one

![Windows 10](https://drive.google.com/uc?id=1TiJkL9Ax25yP_pFksgMGEG7R2X4z_YLp)

**Comment by ihodev** [comment]
How can I test this? Please, describe ;)

**Comment by felixse** [comment]
Error seems to be very similar to this: https://stackoverflow.com/questions/50218607/error-attempting-sideload-install-of-desktop-bridge-app-the-system-cannot-find

Did you try installing it again in the meantime?

**Comment by felixse** [comment]
Maybe also try the solution that was provide here: https://github.com/trufflesuite/ganache/issues/605

**Comment by felixse** [comment]
@ihodev Did anything of this work for you?

**Comment by ihodev** [comment]
@felixse Absolutely, thank you a lot 😉
