### ISSUE TITLE
Opacity option doesn't work

### ISSUE THREAD

**Issue by NDelt** [felixse/FluentTerminal#369]
![opa](https://user-images.githubusercontent.com/46282492/57766223-f3e59600-7741-11e9-933e-2a770dd783ed.PNG)

![opa2](https://user-images.githubusercontent.com/46282492/57766227-f647f000-7741-11e9-96cf-fe10698f56ec.PNG)

I set `background opacity` to 0.4500 but nothing has changed.

**Comment by Djdany95** [comment]
Same here, as i can see in the code, it nevers sets the opacity but the option is there in "TerminalOptions.cs"

**Comment by felixse** [comment]
Opacity is handled in UWP, not in xterm.
Did you maybe disable transparency effects in Windows Settings? Also note that transparency is only allowed for the active window

**Comment by Djdany95** [comment]
Oh my bad, yes it's working 😅
Can you close this issue?

**Comment by felixse** [comment]
Let's wait for @NDelt, but nice to hear it's working for you 😃

**Comment by NDelt** [comment]
Oh yes. I forgot about Windows Settings. Thanks.
