### ISSUE TITLE
Buffer corruption when window resized

### ISSUE THREAD

**Issue by mjs** [felixse/FluentTerminal#373]
This is with 5ed24f85cf500aff6462d57b5c759a4e5e1cbae7. `FluentTerminal.Client/node_modules` was deleted and `npm i` run to ensure that xterm.js was up to date.

1. Start a WSL session (using WinPty)
2. Run `htop`  For example:
![image](https://user-images.githubusercontent.com/14993/58067636-1d8b3b00-7be2-11e9-9f07-64ee48aeebb7.png)
3. Narrow the window by dragging the right edge in.
4. Output in buffer now disappears. For example:
![image](https://user-images.githubusercontent.com/14993/58067710-75c23d00-7be2-11e9-831f-1ebd90f19432.png)

I have not found a way to recover from this. Making the window wider doesn't help. Ctrl-Alt-L has no effect.

When the session is using ConPty, extensive buffer corruption is seen instead of the output disappearing. For example:
![image](https://user-images.githubusercontent.com/14993/58067791-d5b8e380-7be2-11e9-8596-614d5cef1787.png)

Again, I have found no way to recover from this.

**Comment by jackluo923** [comment]
There's even more problem if you perform similar things in tmux. I.e. opening vim in tmux, resize and sometimes the window will completely screw up. 
![image](https://user-images.githubusercontent.com/8986643/58345957-9e874400-7e27-11e9-8d0b-dc55a9ec9e65.png)

**Comment by mjs** [comment]
Seems related to this: https://github.com/xtermjs/xterm.js/issues/1914

**Comment by mjs** [comment]
I have been digging into this today and one thing that does help is applying some rate limiting on resize events like this:

- when a window resize event is received, cache the new terminal size but don't pass the event on. Start a timer instead (for say, 500ms)
- if further resize events are received before the timer goes off, cache the new terminal size and extend the timer
- eventually the resize events stop coming, the timer goes off and a single resize event for the final terminal size is sent and the terminal adjusts to the new size

This greatly - but not completely - reduces the likelihood of the problems described in this issue from happening. It seems that the longer I make the resize timeout, the less likely it is for corruption issues to happen.

I'd like to dig a bit further but if there's interest I can turn this resize deboucing hack into a proper solution and propose a PR.

**Comment by Riebart** [comment]
What if you wait for the mouse drag to end, then send the resize event instead of using timers? This way you would be guaranteed to get exactly one resize event per user resize operation.

**Comment by jackluo923** [comment]
@Riebart What you are referring to is called "debouncing". I am pretty sure that's what @mjs is describing, but in a slightly different way.

**Comment by Riebart** [comment]
Yes, I am well aware of what I am describing.

Specifically I am suggesting a deterministic way to ensure exactly one resize event is sent to xterm and either ConPTY or WinPTY, as opposed to the heuristic method they had hacked together.

His heuristic hack has mostly resolved the issues, and my question is to whether a more deterministic approach would fully resolve the issue.

**Comment by felixse** [comment]
I think debouncing is fine, afaik this is also recommended by the xterm.js developers. Here is something you could use: https://github.com/felixse/FluentTerminal/blob/master/FluentTerminal.App/Utilities/DebouncedAction.cs

**Comment by mjs** [comment]
@Riebart I see what you are saying: catch the drag start and end events and only send a resize event when the drag ends. This certainly would be cleaner than guessing with a timer.

I've done some digging into this approach and I don't see a way to do it. The UWP Window class is the source of the resize changes and it doesn't seem to expose events that let us intercept the drag begin and end. It only emits SizeChanged events as the window size is changed. I'd be happy to learn of a way around this.

For now I'm going to pursue the debouncing approach.

**Comment by Riebart** [comment]
Ah, shucks. Well, thanks for taking a look! I've built and moved to the newest version, so I'll see if I can lend any data to help work on the issue.

**Comment by mjs** [comment]
@Riebart #394 is the PR for debouncing resize events
