### ISSUE TITLE
Themes do not work in wsl or bash

### ISSUE THREAD

**Issue by kubet** [felixse/FluentTerminal#377]
![image](https://user-images.githubusercontent.com/41026612/58241977-3fa1cc00-7d4e-11e9-8795-c953d93bcbd0.png)
![image](https://user-images.githubusercontent.com/41026612/58241999-4defe800-7d4e-11e9-88bb-bfe2daca1013.png)
Themes only work in cmd and PowerShell profile, the only way I could get them to work is if I type bash in cmd or PowerShell.
**OS:** Windows 10 1903
**FluentTerminal:** 0.4.1.0
**Env:** SHELL=/bin/bash, TERM=xterm-256color with zsh

**Comment by felixse** [comment]
Did you maybe configure a theme for your wsl profile? those overwrite the default theme

**Comment by kubet** [comment]
Changing the theme in profile seems to be working.
