### ISSUE TITLE
Scrollback management

### ISSUE THREAD

**Issue by Riebart** [felixse/FluentTerminal#38]
Paired with #25 it would be nice to have some scrollback management options, such as clearing the scrollback buffer or select-all to copy/paste into somewhere else. Yes, technically you can get this with tmux or something else, but it's way more convenient to have it as part of the terminal emulator itself than a child process.

Also seems like it might be a simple one to implement, just a bit of interaction with the xterm buffer itself.

**Comment by skipmeister123** [comment]
Personally, I'd very much rather rely on my terminal emulator than learn
all the tmux commands. I'm lazy. I support any functionality that brings
features from tmux to the emulator itself.

Hans Kokx

**Comment by felixse** [comment]
Should be no big problem, xterm.js has a .clear() and a .selectAll() method
