### ISSUE TITLE
Bug when prompt's offset is not zero

### ISSUE THREAD

**Issue by eagleoflqj** [felixse/FluentTerminal#381]
Reproduce (ssh to linux, or wsl):
```sh
echo abc >a
truncate --size 3 a # eliminate the LF of a
cat a
```
since there's no LF, the prompt appears in the same line with abc: 
```
abcuser@desktop:~#
```
suppose the terminal's size is width*height, and the length of prompt is n (here is 16 because there's a space after :~#), now type 'a' (width-n) times, and the terminal is like this:
```
abcuser@desktop:~# aaaaaaaaaaaa
aaa
```
now the cursor is at the start of the second line, not after the last 'a', so if you type 'b', it will overlap the 'a' of the second line, like below:
```
abcuser@desktop:~# aaaaaaaaaaaa
baa
```
Maybe you can take offset into account.

**Comment by felixse** [comment]
I think this i more likely an issue with bash. We only display what the shell is sending us, we have no influence on how it determines in which line a prompt should be written
