### ISSUE TITLE
Support scoop 

### ISSUE THREAD

**Issue by TheZoker** [felixse/FluentTerminal#383]
Apart from allowing to install FluentTerminal via [chocolatey](https://chocolatey.org/), is it also possible to support [scoop](https://scoop.sh/)?

**Comment by felixse** [comment]
The Chocolatey is not maintained by me directly. If someone wants to offer a scoop package feel free to step in 😃
We might also switch to a msi package soon, so maybe better wait until this is released

**Comment by klaidliadon** [comment]
Hi, I have a working bucket for the application.

https://github.com/lukesampson/scoop-extras/pull/2883

I don't think they will accept it because I am doing some operations (enabling sideloading and install certificate) before installing the app.

**Comment by TheZoker** [comment]
So it seems, that scoop won't this :/ 

@felixse Is msi support still planed? I think this would solve the scoop issue. 
Are there any plans, to publish this to the MS store?

**Comment by felixse** [comment]
MSI support is nothing I'm working actively on, but I'm open for PRs in that direction. My goal right now is to get this into the Store finally.

**Comment by issaclin32** [comment]
@klaidliadon If [extras bucket](https://github.com/lukesampson/scoop-extras) does not accept it, you can try to add the package to the [nonportable bucket](https://github.com/oltolm/scoop-nonportable), their criteria is not that strict.

I am not saying that *extras bucket* is being too strict. (I do appreciate the "no-harm" policy of *Scoop*.)

But we can first add the non-portable package as a work-around before we can find a way to meet the criteria of the *extras bucket*.

**Comment by Restia666Ashdoll** [comment]
Well here it goes
https://github.com/TheRandomLabs/scoop-nonportable/pull/93

**Comment by Restia666Ashdoll** [comment]
So, its merged. Unlike Chocolatey, this does not require elevated PowerShell(it uses Scoop's sudo command)
https://github.com/TheRandomLabs/scoop-nonportable/blob/master/bucket/fluent-terminal-np.json
```
scoop bucket add nonportable
scoop install fluent-terminal-np
```
@felixse  Please add this to Readme.

**Comment by Restia666Ashdoll** [comment]
For those who dont use Scoop the complete set of steps are
1. Install Scoop
`iwr -useb get.scoop.sh | iex`
2. Intstall 7zip and Git(to add buckets)
`scoop install 7zip git`
3. Add non-portable bucket and install fluent terminal
```
scoop bucket add nonportable
scoop install fluent-terminal-np
```

**Comment by TheRandomLabs** [comment]
I've removed the use of `sudo` as it was being used multiple times during installation and uninstallation, causing multiple prompts to pop up. Other manifests in scoop-nonportable just require elevation instead, so I've done it with this manifest as well. Let me know if you have a better solution. :)

**Comment by TheRandomLabs** [comment]
I'll also note that because I'm still on 1803, #555 caused `Install.ps1` to not execute correctly. Removing `-ForceUpdateFromAnyVersion` seemed to cause installation to occur normally.

**Comment by Restia666Ashdoll** [comment]
@TheRandomLabs  If you are not using sudo then you can also change `"powershell /c 'Get-AppxPackage -Name *FluentTerminal* | Remove-AppxPackage -AllUsers'"` in uninstaller script to simply `"Get-AppxPackage -Name *FluentTerminal* | Remove-AppxPackage -AllUsers"` , since that was just a workaround for sudo command not working on Remove-AppxPackage.

**Comment by TheRandomLabs** [comment]
Ah, thanks.
