### ISSUE TITLE
Disable horizontal line wrap

### ISSUE THREAD

**Issue by adhikasp** [felixse/FluentTerminal#385]
Hi

Is there any way (or any plan) to disable horizontal line wrap as a feature?
So the text will overflow to the right side and a horizontal scroll bar to slide the terminal window.

**Comment by felixse** [comment]
No plans to add this in the moment, sorry.
Also keep in mind that we use [xterm.js](https://github.com/xtermjs/xterm.js) as a renderer, so anything in this direction needs to be implemented there.
