### ISSUE TITLE
"Select All" will highlight complete window

### ISSUE THREAD

**Issue by MaxBelohoubek** [felixse/FluentTerminal#388]
When pressing CTRL+A the whole window is selected instead of all text/current command. After copying, things like the prompt will be copied also. I can't find an option to control this behavior. 
Is it intended to be like this? I'm used to selecting and copying the current line from all terminals I have used so far.

**Comment by felixse** [comment]
Tried a few terminals on Windows and macOS. So far only conEmu behaved like this. What terminals are you referring to?

**Comment by MaxBelohoubek** [comment]
Windows PowerShell (also PowerShell Core) and Hyper are the ones I remember right now.

**Comment by dsugiyama** [comment]
I think "Ctrl-A to select current line" is PSReadline's keybinding. To use it in FluentTerminal, you need to disable Ctrl-A keybinding in FluentTerminal settings.
Open Settings -> Keybindings and delete the "Select all" entry.

**Comment by felixse** [comment]
In the next version the default keybinding for select will be `Ctrl + Shift + A`, this will restore the PSReadline keybinding. Make sure to reset your keybindings once you updated
