### ISSUE TITLE
Direct SSH shell targets

### ISSUE THREAD

**Issue by Riebart** [felixse/FluentTerminal#39]
It would be handy, but not necessary, to support SSH targets as profile shells using the nodejs SSH client modules. This would be useful for working on remote machines, as well as working around #9 on Windows 10 1803 and newer by running the WSL sshd, and connecting over SSH (thereby eliminating the fact that the Windows console host currently doesn't pass control sequences around quite right).

There's a lot of features more important than this, but throwing it into the hat anyway.

**Comment by skipmeister123** [comment]
I handily agree. For work, I spend most of my time SSH'd to various
servers. Having them as custom profiles would be useful... But is that
currently impossible? I can run bash with arguments. Could one be ssh?

Hans Kokx

**Comment by Riebart** [comment]
A perfectly valid point. It does work, but adds a required that you've got an SSH client kicking around. Specifically, if you're using the WSL ssh, it doesn't fix the 256-color issue (because you're invoking it through the WSL console host).

The advantage to using the ssh2 nodejs module (or similar) directly is that you'd be able to use this without the installing a separate SSH client. The terminal could also handle graceful reconnecting for you across network changes and sleep/wakeup cycles.

The arguments are a perfectly functional way of addressing this for now, in any event.

**Comment by skipmeister123** [comment]
A very valid point; I tend to agree. The end goal is a profile to connect
to a SSH host with ease, and this sounds like a fair mechanism to do so.

Hans Kokx

**Comment by felixse** [comment]
This would be a nice feature for later on, when we have all the basics implemented.
I would prefer using something like https://github.com/sshnet/SSH.NET since the javascript part of the application might go away once https://github.com/darrenstarr/VtNetCore.UWP is ready for adoption
