### ISSUE TITLE
WSL blank terminal have to restart WSL and Fluent terminal

### ISSUE THREAD

**Issue by antoinebou13** [felixse/FluentTerminal#392]
Hello,
Love your terminal
I use it with vmd, powershell, git bash cli and WSL ubuntu 18.04

My default profile is my WSL and when i open a new tabs after a while i get this bug 

![image](https://user-images.githubusercontent.com/13888068/58816430-88cc0880-85f7-11e9-97b4-a00f47665834.png)

Also this tabs is impossible to close or interact with
my fix current is to close fluent terminal and my WSL with cmd admin

```
net stop LxssManager
net start LxssManager
```

Thank !

**Comment by felixse** [comment]
this looks more like a wsl problem. how is the builtin shell behaving when this occurs?

**Comment by antoinebou13** [comment]
You are right !
I never saw this occur with powershell or cmd, so i guess this only occur with WSL. 

My other question or issue is
Can i force close the tabs with the task manager or with a command ?

Maybe it related to only to the WSL
https://github.com/Microsoft/WSL/issues/808
https://github.com/Microsoft/WSL/issues/2352

Thank !

**Comment by felixse** [comment]
The empty tabs cannot be closed?
No other way besides restarting the terminal right now, sorry 😞

**Comment by antoinebou13** [comment]
😢

**Comment by antoinebou13** [comment]
![image](https://user-images.githubusercontent.com/13888068/58912284-b2fcf380-86e7-11e9-9e7b-a7225af0a1b0.png)

**Comment by mycatdoitbetter** [comment]
Same thing here!

**Comment by nicohouillon** [comment]
I also face this ,was there any fix ? I think especially in 7.4, I was running 7.1 and it happened less but when I updated it to 7.4, right away my first WSL  tab failed  to respond after a few minutes and any other new tabs were blank .
