### ISSUE TITLE
Terminal unresponsive since xterm.js UTF-8 change 

### ISSUE THREAD

**Issue by mjs** [felixse/FluentTerminal#393]
I noticed today that no terminals work with current master. Regardless of the terminal profile, all terminals are blank and seem to accept no input.

I've isolated de07e277f1eb6528b401f6c4d9bbc79555 as the cause. If I build FT with the parent of this commit (5c52810149a8606b0e0c23e65bb531df051dd551), the terminal works again.

**Comment by felixse** [comment]
did you also run `npm install` and `npm run build`? I did some changes to the websocket communication

**Comment by mjs** [comment]
I *thought* I did but I'll try again.

**Comment by mjs** [comment]
Gah! That was it. Looking in my shell history I think I ran `npm install` but not `npm run build`.

Sorry for the noise.
