### ISSUE TITLE
Use xterm.js as Git Submodule

### ISSUE THREAD

**Issue by x1unix** [felixse/FluentTerminal#4]
I recommend to use xterm.js component (and also rest of the components such as `Client` as Git submodules.

This allows to work and update the components independently and also improves code organization.

Good luck!

**Comment by felixse** [comment]
Hi,
yeah I know putting a patched xterm.js in there is a bit crappy, but I will be able to remove it once xterm.js 3.1.0 will be released (planned for next week). As for the rest of the components: They are all pretty tightly coupled, so I don't think there is a need for updating them separately. Nevertheless thank you for your suggestions 👍

**Comment by x1unix** [comment]
@felixse, thank you for the feedback! Do you know the way how can Win32 apps use UWP UI? Afaik UWP doesn't have access to win32 and can't start processes ( except the url handlers) so thats the reason why you use nodejs workaround, but the `explorer` is regular win32 app but it utilizes UWP components.

**Comment by manuelelucchi** [comment]
@x1unix since redstone 4 you can use windows.Ui.composition on win32 programs and with rs5 you should use also windows.ui.xaml. But nothing more for now. The best solution is an uwp that calls win32 (there is a large subset of win32 api that can be called from uwp)

**Comment by felixse** [comment]
Yes, the only thing we can do with the current state of UWP is using FullTrustProcessLauncher to start a win32 program and then rely on IPC.
