### ISSUE TITLE
Problems navigating file managers like midnight commander

### ISSUE THREAD

**Issue by chmielciu** [felixse/FluentTerminal#405]
I've had this issue since I started using FT couple of versions back, but it still persists on currently latest stable 0.4.1.0.

The issue occurs while navigating Midnight Commander or Far manager using up and down arrows and looks like this:
![dBdmwu1glo](https://user-images.githubusercontent.com/11930016/59509610-d2e3a280-8eb1-11e9-9d75-a61ea8cb4b1f.gif)

Its the case in every shell whether its wsl (first tab on gif), cmd/cmder (second tab on gif), powershell and every file manager i tried (couple of mc versions and far for windows) . Note that mc in wsl and cmd on gif are separate versions: native for linux in wsl and native for windows in cmder.  WinPty option doesn't change this behaviour. 
There seems to be some specific aspect ratio or window size that stops those glitches. But I can't really pinpoint if there is any pattern behind it as it feels rather random (there is no specific window size which guarantees no glitches - glitches just stop sometimes when resizing window on random). 

I tested it on most of the other terminal emulators on windows 10 and it seems that Fluent Terminal is the only one that does this.

**Comment by felixse** [comment]
We did some changes that might help with glitches on full screen terminal apps. There will be an update soon, in the meantime you can also try build from source

**Comment by chmielciu** [comment]
Just built from current master and can confirm that all glitches are gone now. 

Thanks a lot.
