### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#42]
There should be an updater mechanism, that doesn't require manual steps.  If getting into the Windows Store isn't possible, perhaps [WinSparkle](https://winsparkle.org/) is a solution?

**Comment by felixse** [comment]
We would need an installer first if we want to use WinSparkle. I am still hoping that we can get in the Windows Store some time, so I would prefer not to invest much time into this.

How about checking for updates on startup and just showing a notification instead?

**Comment by skipmeister123** [comment]
That'd be fine. Maybe a link to the releases page.

Hans Kokx
