### ISSUE TITLE
Copy multiline from WSL does not copy line breaks

### ISSUE THREAD

**Issue by DavidCDreher** [felixse/FluentTerminal#420]
When copying multiple lines from WSL inside Tmux and pasting into another Windows App (Notepad, Teams, Browser). All lines are pasted as one line. Interestingly sometimes at least for shorter bits of only a couple of lines it seems to work but unfortunately not for longer outputs.
I'm on on 0.4.1 on Windows 10 1809 with WinPty on always.

Steps to reproduce:
 - Open WSL and create a Tmux session
 - generate a multiline output, for example a Python Traceback 
 - copy it (I used copy on selection)
 - paste into another App

Besides that very annoying issue: Fluent Terminal is awesome! A great piece of work!

**Comment by MaxRis** [comment]
This should be totally related to https://github.com/microsoft/terminal/issues/405
