### ISSUE TITLE
My terminal is not open

### ISSUE THREAD

**Issue by a543124159** [felixse/FluentTerminal#425]
My terminal could not be opened, and there was a false dead state. Can't open it. What's the problem?

Below is the picture I uploaded. Could you tell me?

无法显示命令行
Unable to display command line
![捕获](https://user-images.githubusercontent.com/28872056/60480104-df8e3600-9cba-11e9-87ae-fb54d66cf98b.PNG)

**Comment by mjs** [comment]
What happens if you hit Enter?

**Comment by a543124159** [comment]
> 如果按Enter键会发生什么？

任何东西都没有发生，全是空白

**Comment by Amanocino** [comment]
I had meet the same problem too.

**Comment by zck918** [comment]
same problem!

**Comment by felixse** [comment]
Does this still occur with the latest update (0.5.1.0)?

**Comment by zck918** [comment]
the problem still exists...

**Comment by felixse** [comment]
can you [enable debug logging](https://github.com/felixse/FluentTerminal/wiki/Logging) and post some logs?

**Comment by zck918** [comment]
after restarting my computer, the problem disappeared surprisingly... : )

**Comment by felixse** [comment]
@a543124159 do you still have this issue?
