### ISSUE TITLE
Old profile prevents me from launching after 0.5 update

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#427]
![image](https://user-images.githubusercontent.com/1911919/60547021-a8d11380-9cec-11e9-8c5a-5ca4087f2f4b.png)

**Comment by skipmeister123** [comment]
I can't actually change the settings, since the app closes as soon as I click ok.

**Comment by felixse** [comment]
You should be able to force it to open with `flute new --profile cmd`. There seems to be some problem with WSL in the packaged version, I'm looking into it

**Comment by felixse** [comment]
Occurs only when installed from the released package, not if build from source (debug or release). Pulled the update for now and will investigate this tomorrow.

**Comment by felixse** [comment]
Should be fixed now (0.5.1.0)

**Comment by skipmeister123** [comment]
Confirmed.
