### ISSUE TITLE
Latest version to Choco

### ISSUE THREAD

**Issue by satvikpendem** [felixse/FluentTerminal#431]
Could you add the latest version to choco? It's currently at 0.4.1.0.

**Comment by kpchand** [comment]
+1

Excited to try out the new SSH profiles and other features.

**Comment by felixse** [comment]
@pgalbraith Can you please update this? You can also add me as a maintainer for future releases

**Comment by pgalbraith** [comment]
It's in the queue awaiting moderation, with any luck this time they flag it as a trusted package and the wait won't be nearly as long after that. Felix yes please I would love to add one or two more maintainers so I'm not the only one :-).  Please drop me a line with your chocolatey user name.

**Comment by felixse** [comment]
Just signed up, username is felixse

**Comment by jackluo923** [comment]
@felixse It seems there a problem newest build on choco. When settings->profiles menu is accessed, fluent terminal crashes without error. Is this happening on your computer?

**Comment by pgalbraith** [comment]
@felixse added you as a maintainer on Chocolatey and the GitHub repo I use to maintain the package.

**Comment by pgalbraith** [comment]
Chocolatey is now up to date at version 0.5.3.0.  They've also upgraded it to trusted status so there won't be the long delays any more waiting for moderator approval.

**Comment by jameshclrk** [comment]
@pgalbraith and @felixse Is it possible to get 0.6.0.0 on Chocolatey as well?
