### ISSUE TITLE
FluentTerminal is crashing when i open "profiles tab"

### ISSUE THREAD

**Issue by TheWAVs** [felixse/FluentTerminal#435]
For some odd reason, my current installation of FluentTerminal 0.5.1.0 _**is suddenly crashing**_ when i try to setting my Terminal shortcut profiles.

**Proof:**

![OW4EOjjhZa](https://user-images.githubusercontent.com/10777531/60772695-b3f6bb80-a0bf-11e9-8169-2479e6a9a880.gif)

**_Windows:_** **v1803**, **comp. 17134.860**

The previously version of FluentTerminal it had never experienced this issue.

**Comment by felixse** [comment]
can you [enable debug logging](https://github.com/felixse/FluentTerminal/wiki/Logging) and post some logs?

**Comment by TheWAVs** [comment]
> can you [enable debug logging](https://github.com/felixse/FluentTerminal/wiki/Logging) and post some logs?

Of course:


2019-07-07 13:54:18.624 -05:00 [FTL] Initialized
2019-07-07 13:54:26.108 -05:00 [ERR] Unhandled Exception
Windows.UI.Xaml.Markup.XamlParseException: No se pudo encontrar el texto asociado a este código de error.

Unable to resolve property 'Text' while processing properties for Uid 'LineEndingModeOnPaste'. [Line: 0 Position: 0]
2019-07-07 13:54:56.919 -05:00 [FTL] Initialized
2019-07-07 13:55:31.014 -05:00 [FTL] Initialized
2019-07-07 13:55:54.874 -05:00 [ERR] Unhandled Exception
Windows.UI.Xaml.Markup.XamlParseException: No se pudo encontrar el texto asociado a este código de error.

Unable to resolve property 'Text' while processing properties for Uid 'LineEndingModeOnPaste'. [Line: 0 Position: 0]
2019-07-07 14:00:41.170 -05:00 [FTL] Initialized
2019-07-07 14:05:04.890 -05:00 [ERR] Unhandled Exception
Windows.UI.Xaml.Markup.XamlParseException: No se pudo encontrar el texto asociado a este código de error.

Unable to resolve property 'Text' while processing properties for Uid 'LineEndingModeOnPaste'. [Line: 0 Position: 0]
2019-07-07 14:18:51.726 -05:00 [FTL] Initialized
2019-07-07 14:21:13.062 -05:00 [ERR] Unhandled Exception
Windows.UI.Xaml.Markup.XamlParseException: No se pudo encontrar el texto asociado a este código de error.

Unable to resolve property 'Text' while processing properties for Uid 'LineEndingModeOnPaste'. [Line: 0 Position: 0]
2019-07-07 14:28:38.065 -05:00 [FTL] Initialized
2019-07-07 14:28:41.767 -05:00 [ERR] Unhandled Exception
Windows.UI.Xaml.Markup.XamlParseException: No se pudo encontrar el texto asociado a este código de error.

Unable to resolve property 'Text' while processing properties for Uid 'LineEndingModeOnPaste'. [Line: 0 Position: 0]
2019-07-07 14:29:09.106 -05:00 [FTL] Initialized

**Comment by felixse** [comment]
Seems like some translation is missing. You should be able to fix this by switching to english for now. I will sort this out in the next update

**Comment by TheWAVs** [comment]
> Seems like some translation is missing. You should be able to fix this by switching to english for now. I will sort this out in the next update

the issue still exists ):

**Proof:**

![y2QDW04rpD](https://user-images.githubusercontent.com/10777531/60773066-261dcf00-a0c5-11e9-90f3-c3b53760e397.gif)

**Comment by felixse** [comment]
Still the same error in the logfile?

**Comment by TheWAVs** [comment]
> Still the same error in the logfile?

Yes:

2019-07-07 14:46:42.093 -05:00 [FTL] Initialized
2019-07-07 14:46:46.208 -05:00 [ERR] Unhandled Exception
Windows.UI.Xaml.Markup.XamlParseException: No se pudo encontrar el texto asociado a este código de error.

Unable to resolve property 'Text' while processing properties for Uid 'LineEndingModeOnPaste'. [Line: 0 Position: 0]

**Comment by felixse** [comment]
Alright, I will try to reproduce this tomorrow. In the meantime you should be able to edit your profiles with via cli with `flute settings export` and `flute settings import`

**Comment by MaxRis** [comment]
It might be that your system default language should be `English (United States)`. In this case it might will not look for translation at all and use the value from `xaml` file.
The issue should be not only with `LineEndingModeOnPaste` setting, but with others recently added as well.

**Comment by wolf99** [comment]
I am seeing the same issue as soon as I updated to 0.5.1.0
App is set to English per default, but system language is English (United Kingdom).

**Comment by felixse** [comment]
Just released a new version with the fix for this.
