### ISSUE TITLE
Can i export setting to a file and then import it after i reinstall FluentTerminal or OS ?

### ISSUE THREAD

**Issue by netifork** [felixse/FluentTerminal#439]
Like the title , can i export all settings of FluentTerminal to a file and import it when i need ?

Thanks !

**Comment by MaxRis** [comment]
yes, via cli. Please see https://github.com/felixse/FluentTerminal/issues/435#issuecomment-509025830

**Comment by netifork** [comment]
![image](https://user-images.githubusercontent.com/39062685/60911323-1660df00-a2ad-11e9-8e9f-c7e30e160a07.png)

I have try `flute settings export` and `flute settings import` but it just show setting window and i dont see anything is exported.

Do i miss arguments like a path or something in that cli ?

**Comment by MaxRis** [comment]
Oh, sorry, it should be typed as

`flute settings -export` and `flute settings -import`

https://github.com/jumptrading/FluentTerminal/issues/130 is related to this

**Comment by netifork** [comment]
It will be better and easier if it have Export / Import buttons in setting window.

Tks for your working , this is a best terminal i have ever used on windows :D
