### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by kpchand** [felixse/FluentTerminal#441]
I want to sync my settings so I have a backup in case of an issue.
I cannot seem to find it in %appdata%/roaming. I also searched "fluent" in C:\ but no results returned.
Where is it located so I may backup it?

This was also asked in the following thread: https://github.com/felixse/FluentTerminal/issues/181

**Comment by mjs** [comment]
To find FluentTerminal's data directory, try running something like this in Powershell:

```
dir ${env:USERPROFILE}\AppData -recurse -Directory -Include *FluentTerminal* | select fullname
```

On my machine it was at 
```
%USERPROFILE%\AppData\Local\Packages\53621FSApps.FluentTerminal_87x1pks76srcp
```

The settings are in `Settings\settings.dat` off that.
