### ISSUE TITLE
Black background color is overridden by terminal background color

### ISSUE THREAD

**Issue by Azumgi** [felixse/FluentTerminal#447]
But it feels like it's not drawn at all. If you make terminal transparent, there's nothing there.
Black foreground, on the other hand, has user-defined black color as it should.
![color_glitch](https://user-images.githubusercontent.com/35058624/61034694-64b9cf00-a3ce-11e9-9c32-9d72a220f89e.jpg)
Switching between WinPTY and ConPTY does not make any difference.

Fluent Terminal version: 0.5.1.0
OS: Win10 1903
Shell: WSL Arch

How to reproduce:
```bash
curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/ | bash
```

EDIT: This behavior also persists in other terminal emulators, such as Terminus and Alacritty. I assumed this is a bug because I can see black color in Windows Console, but then it struck me that I have the 5th color set as a background in here:
![Untitled-4](https://user-images.githubusercontent.com/35058624/61075166-0d454e80-a422-11e9-904f-d01f6d01e376.jpg)
So, this is not an issue, I suppose? I'm not sure what the correct behavior is. If it's intended, just close this issue.

**Comment by felixse** [comment]
I think this is ok that way.

**Comment by cgthayer** [comment]
@Dreomite Did you find a way to fix?  I have the same issue.  Thanks

**Comment by Dreomite** [comment]
Nope, I didn't. I tried lots of Windows terminal emulators and none of them could set a separate terminal background color, so I assumed it's Windows TTY limitation.

I'm not sure what is the current state of things since I moved to Linux a year ago.
