### ISSUE TITLE
Double pasting when using keyboard

### ISSUE THREAD

**Issue by ohall1** [felixse/FluentTerminal#451]
When using the keyboard shortcuts to paste it will double paste what is in the clipboard both for standard paste and paste with no line endings.

Works fine when pasting from the right click menu.

Version 0.5.2.0

**Comment by ttttmr** [comment]
I have the same issue. The previous version is normal (0.4.1.0)

**Comment by XiaoXX0522** [comment]
I also have the same issue. I think up to 0.5.1.0 it worked fine.
