### ISSUE TITLE
Passwords for SSH connections

### ISSUE THREAD

**Issue by yoavst** [felixse/FluentTerminal#453]
Is it possible to use password instead of identity files? I would like to connect a server which I don't have permission to add an ssh key, but I do have a password to login.

**Comment by mjs** [comment]
This is already supported. Supplying an identity file is completely optional. If the SSH server supports password authentication then you should get prompted for the password after connecting.

**Comment by yoavst** [comment]
For me it Doesn't work but It may be a problem with the specific server.
However, would it be possible to support pre-filled password? So I would be able not to enter the password everytime.

**Comment by skipmeister123** [comment]
There are some pretty serious security implications for that, which would violate the policies of companies who own computers which FT is being used at or servers being logged in to.  It is an incredibly bad idea, and I would encourage you to find another way.

**Comment by mjs** [comment]
The preferred way to access hosts via SSH without passwords is to use keys. The identity file UI control lets you select a SSH key file.

Alternatively, FT is using the OpenSSH client that comes with Windows under the hood so you can set up key based access there as well.

These instructions are written with Linux in mind but should work for OpenSSH on windows too.

https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2

**Comment by yoavst** [comment]
OK, closing this issue.
