### ISSUE TITLE
Unexpected slience when initialization 

### ISSUE THREAD

**Issue by GrandArth** [felixse/FluentTerminal#455]
When i launch fluent terminal for the first time( rather than open the terminal from the existed toolbar icon), the sound of the music palyer/game/video player stopped.

**Comment by MaxRis** [comment]
Does sound stop for few seconds and then return back?

**Comment by GrandArth** [comment]
> 
> 
> Does sound stop for few seconds and then return back?

Exactly

**Comment by mjs** [comment]
This is required to suppress terminal beeps (new feature) which is a bit tricky to do. As you've noted, it only happens when FluentTerminal is first started (i.e. when the system tray process starts).

If you don't want this (and don't mind beeps from terminal sessions) then disable the "Mute terminal beeps" option on the General settings page.

**Comment by MaxRis** [comment]
@mjs the problem, is that current logic mutes audio device for any state of "Mute terminal" settings option. It's the most convenient way to be sure that required muting state is applied.

to disable muting of audio device we need another one Settings option that will turn off current muting logic completely, or I need to think better about alternatives.

Based on users reaction so far, I would vote to remove muting audio device logic completely and let it play beep sound. Hopefully, it will happen only once per OS session.

**Comment by GrandArth** [comment]
@mjs "Mute terminal beeps" dosen't actually work.
I turned it off and on and tried several times, the launching silence is still there.
The normal beeps are gone (when you backspace into nothing).
(v5.3.0)

**Comment by mjs** [comment]
@MaxRis has recently merged #468 which avoids the silencing of audio on launch and also makes terminal beep muting more reliable. This will be in the next release of FT.

Note that not all kinds of beeps can be muted. Vim for example seems to generate beeps via it's own audio session, outside of the terminal beep mechanism. There's nothing that FT can do about that.

**Comment by GrandArth** [comment]
Thx for letting me know.
