### ISSUE TITLE
FluentTerminal won't work with VPN

### ISSUE THREAD

**Issue by sinadarvi** [felixse/FluentTerminal#460]
Recently when starting FluentTerminal while my VPN is on, FT will come up but stuck in blinking courser screen, and won't load powershell or any other. but when I force to close it and try again without VPN, terminal comes up successfully and ready for use. even trying for going to setting page or even trying to close the terminal with closing icon, will Endup to crash.

![image](https://user-images.githubusercontent.com/13999444/61427402-47878200-a933-11e9-9c8a-8531d535d5c8.png)

**Comment by skipmeister123** [comment]
My guess is that it's unable to complete the check for a new version.  This 
process should probably be non-blocking.

**Comment by sinadarvi** [comment]
I don't think so! because I remember I saw the update notification last time opened this with VPN. I even checked Recourse Monitor > Network > Network Activity, and I looked for IP address when FT comes up, and I saw `lb-140-82-118-6-ams.github.com` and trying this with a browser was useless.

![image](https://user-images.githubusercontent.com/13999444/61459314-b68bc780-a981-11e9-8f5f-5f9f70667161.png)

I don't know! maybe it is new version checking problem!

**Comment by eagleoflqj** [comment]
Can't work with OpenVPN either. I can see the notification 'Update available'. The version is the latest in chocolatey: 0.5.1.0.

**Comment by eagleoflqj** [comment]
When I canceled the proxy setting in IE's Internet Option, FluentTerminal worked. I think as an offline app, it should work in any network environment.

**Comment by skipmeister123** [comment]
Agreed. This should be a non-blocking event.

**Comment by felixse** [comment]
If you see the update notification the version check already succeeded (which is also done in the SystemTray process, not the App itself) The problem here is more probably the WebSocket communication between the App and the WebView. The VPN must interfere with it in some way

**Comment by sinadarvi** [comment]
so @felixse, how can I solve this problem? VPN is just the normal windows PTPP connection. I even try to listen to HTTP request going out from pc with Wireshark, but when I launch Wireshark and then launch the FT, same happens! with closing Wireshark, and launching FT again, it works normally!

**Comment by muxw** [comment]
I also encountered this problem, when I open the global proxy for shadowsocksr, I can't open a new window.

**Comment by xhxgit** [comment]
> I also encountered this problem, when I open the global proxy for shadowsocksr, I can't open a new window.

Before the author (may) fix this, I'm just wondering, in which case do you need it to be `Global`

**Comment by pangjian** [comment]
I add an exclude ip address list to my proxy config. Add "local*;127.0.0.1" works for me. like this


![批注 2019-07-22 105806](https://user-images.githubusercontent.com/5206136/61603313-b20c2b00-ac6f-11e9-933e-59c99454b6cb.png)

**Comment by yulei900609** [comment]
I also encountered this problem.

**Comment by sinadarvi** [comment]
as @pangjian said, by excluding `127.0.0.1` so it won't throw the VPN the problem temporary solved. first, get your getaway with `ipconfig` command, then execute this: `route add 127.0.0.1 <getaway ip>`.

**Comment by felixse** [comment]
Thanks for sharing your solution @pangjian 
There is not much we can do here right now, but I haved linked this discussion to our FAQ
