### ISSUE TITLE
Visual Studio 2019?

### ISSUE THREAD

**Issue by warpdesign** [felixse/FluentTerminal#466]
The wiki recommends to install VS Community 2017 but current version is VS 2019: is it possible to build Fluent Terminal using VS 2019?

It also would be great to provide links to download earlier builds (like [vs 2017 community](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=15)) in the wiki.

**Comment by MaxRis** [comment]
> is it possible to build Fluent Terminal using VS 2019?

VS 2019 works great for me

**Comment by felixse** [comment]
Thanks for pointing out, I have edited the wiki page so that no particular version of Visual Studio is mentioned
