### ISSUE TITLE
Microsoft is doing something...

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#47]
It looks like they're doing exactly what we're trying to do here.  [See for yourself.](https://blogs.msdn.microsoft.com/commandline/2018/06/20/windows-command-line-backgrounder/)

**Comment by skipmeister123** [comment]
Oh, it looks like it's just [Sets](https://blogs.msdn.microsoft.com/commandline/2018/04/13/tabbed-console-starts-here/)

**Comment by felixse** [comment]
Nevermind, looks like a good read 😄

**Comment by Riebart** [comment]
Yeah, this looks to be a super cool feature, and I look forward to having tabs/split pants/a better terminal (a.k.a FluentTerminal) as one of the tabs in my tab-set. 😸
