### ISSUE TITLE
$env:TERM default value

### ISSUE THREAD

**Issue by takase1121** [felixse/FluentTerminal#470]
Whenever I start PowerShell in FluentTerminal, the environment variable `$env:TERM` will be set to `xterm-256color`. This causes me some problems because my `micro` editor will not work. It kept showing me `No screens available` because it assumed that the terminal is xterm compatible.

**Comment by felixse** [comment]
I think we should make this configurable, along with the option to specify other env variables for a profile

**Comment by takase1121** [comment]
This became more of an issue when my attempt resetting this value in `$PROFILE` script doesn't work. I hope this feature got implemented soon.
