### ISSUE TITLE
Different powershell settings in different profiles do not work (default is used)

### ISSUE THREAD

**Issue by JFSeibert** [felixse/FluentTerminal#474]
I just tried to use a second powershell with different setting, mainly just to open it in my develop folder.
But using the shortcut I've set (ctrl + alt + 4) did not work. It always opens the _preset_ powershell profile.
![image](https://user-images.githubusercontent.com/2338414/62602087-33f88700-b8f3-11e9-8d79-ad9ea12f236e.png)
even setting it as default profile does not work, though on startup (freshly started fluent terminal) it opens the correct profile, when using shortcut it still fails.

This happens on v 0.5.3.0

**Comment by JFSeibert** [comment]
update: using "ctrl + shift + t" opens profile with my settings, only my custom set shortcut does not.

**Comment by felixse** [comment]
It should work if you remove the existing keybinding and create a new one. The problem was that the keybinding was duplicated along with the profile and still contained the old profile id. 

I made a change so that keybindings no longer get duplicated as well.
