### ISSUE TITLE
The fluent terminal couldn't load

### ISSUE THREAD

**Issue by lyjzsyzlt** [felixse/FluentTerminal#487]
when i start the fluent terminal ,it looks like this. it didn't work by restarting the terminal. i restart the win10 system ,but it also didn't work
![](https://user-images.githubusercontent.com/30644064/63067125-0c7f6b00-bf40-11e9-9099-e2c390962187.png)

**Comment by felixse** [comment]
Are you using a VPN?

**Comment by lyjzsyzlt** [comment]
> Are you using a VPN?
i'm not using the VPN when it didn't work.  but it worked after i used the VPN.  but it works, too when i start the terminal today, but i don't use the VPN this time. i don't know the connections between the fluent terminal and VPN. (it can surf the internet all the time)

**Comment by Raibows** [comment]
> Are you using a VPN?

Yes,I can't open it  when I using a VPN. But why ? and how to solve this problem ?

**Comment by BostonLobster** [comment]
> Are you using a VPN?

I also can't open fluet terminal when I using a socks proxy software (ShadowsocksR-win-4.9.0). Could you explain why this happens? Any suggestion to solve it?

**Comment by felixse** [comment]
Fluent Terminal is using a private WebSocket connection to communicate between the App and the WebView. Proxies seem to somehow interfere with that.
