### ISSUE TITLE
Can't kill the fluent terminal

### ISSUE THREAD

**Issue by Raibows** [felixse/FluentTerminal#488]
It seemed like no response when I try to close the terminal.
![image](https://user-images.githubusercontent.com/37944786/63079900-36ea1c00-bf72-11e9-9317-e47d95eba1f8.png)
But when I try to exit it on windows task bar, it works.
My windows system version is: Windows 10 Pro,1903.
Fluent terminal version is: 0.5.3.0

**Comment by jpergler** [comment]
The same happened to me, I had multiple tabs and when clicking close I was not able to close any of the tab. Nor I was able to close the whole terminal. It didn't work when clicking close button in the corner nor when trying to close on taskbar via context menu. I had to kill the process.

I haven't got the repro steps though. :-(

But the same configuration – Windows 10 Pro, 1903, and Fluent terminal version 0.5.3.0.

**Comment by jpergler** [comment]
Now I got the same as I mention and also when I add new tab it freezes in this state. All I can do is just switch tabs, create new tab (but it ends with this) and go to settings. I can't type any command and I'm not able close tab or the whole app.

![image](https://user-images.githubusercontent.com/1771792/63092281-8a07a300-bf61-11e9-8a25-6958fa8d9cfd.png)

**Comment by MaxRis** [comment]
You need to restart FluentTerminal.Tray process. If tray process started to work incorrectly everything will freeze.

**Comment by jpergler** [comment]
Ok thanks for the tip but how the tray process starts to work incorrectly, that is the question then.

**Comment by MaxRis** [comment]
Turning on "debug" logging mode might help to catch something usable in Tray process's log file.

Logs directory - C:\Users\%USERNAME%\AppData\Local\Packages\53621FSApps.FluentTerminal_87x1pks76srcp\LocalCache\Logs\

Some more info is there - https://github.com/felixse/FluentTerminal/wiki/Logging

**Comment by Raibows** [comment]
> Now I got the same as I mention and also when I add new tab it freezes in this state. All I can do is just switch tabs, create new tab (but it ends with this) and go to settings. I can't type any command and I'm not able close tab or the whole app.
> 
> ![image](https://user-images.githubusercontent.com/1771792/63092281-8a07a300-bf61-11e9-8a25-6958fa8d9cfd.png)

I have to say it works well up to now when I proposed this issue. It's very strange and amazing.
Even don't rebot my computer, just forced kill it some times.

**Comment by Raibows** [comment]
> You need to restart FluentTerminal.Tray process. If tray process started to work incorrectly everything will freeze.

Thanks for your help, it works well now when I just forced killed it some times.
