### ISSUE TITLE
version

### ISSUE THREAD

**Issue by FJduFou** [felixse/FluentTerminal#499]
Hello,
I would like to know, what is the current version and the changes that have been made to it?
I have a little idea to make it a little more aesthetic, and if you had the history of the versions with their changes.
thank you in advance

**Comment by felixse** [comment]
You can see the history here: https://github.com/felixse/FluentTerminal/releases
The next version will probably be 0.5.4.0 and will include changes since the 0.5.3.0 tag (commit: 90c299d)

What kind of idea do you have?

**Comment by FJduFou** [comment]
[#500](https://github.com/felixse/FluentTerminal/pull/500) ^^
