### ISSUE TITLE
Picker with previous chosen folders

### ISSUE THREAD

**Issue by manuelelucchi** [felixse/FluentTerminal#5]
It would be really cool to have near the settings button or in another place a picker to select the folder to go without write it explicitly. Obviously the user will have to add these folders before with the file picker
Regards,
Manuele

**Comment by felixse** [comment]
I don't want to make this a feature creep before it has all the basic features.  Do you think this would still be a usecase if there is a explorer integration like requested in #2?

**Comment by manuelelucchi** [comment]
If you manage to achieve #2 the it would not be necessary, but i think we would have to wait until Redstone 5. We'll see

**Comment by felixse** [comment]
#2 is absolutely possible with RS3, I will see if I can provide something in the next days.

**Comment by manuelelucchi** [comment]
Awesome!

**Comment by felixse** [comment]
Not needed now that #2 is fixed.
