### ISSUE TITLE
Any ways to run mintty or Windows Terminal inside FluentTerminal?

### ISSUE THREAD

**Issue by leasunhy** [felixse/FluentTerminal#509]
I'm asking this because Xterm.js has several drawbacks:

- Slow! I experience severe key lags in neovim (WSL). The problem becomes more outstanding when the vim color scheme has a solid background (e.g. solarized).
- Many small bugs such as unwanted characters in tmux...

I really love the design of FluentTerminal, but the buggy Xterm.js is keeping me from using it as a productivity tool...

So, is there any way to run mintty or Windows Terminal inside Fluent? If currently there is no ways to do so but it's feasible by changing some code, how can I implement this?

Thanks in advance!

**Comment by felixse** [comment]
Not really, sorry.
We are limited to something in a WebView or something written in UWP right now.
I'm optimistic that things will get better once the new chromium based WebView is available

**Comment by jerch** [comment]
@leasunhy Please open an upstream issue, telling others about "buggy xterm.js" without proper error/bug description is not very helpful/constructive.

**Comment by felixse** [comment]
Nothing we can do here right now. If you can point out some specific issues with xterm.js please post them to their repository.
