### ISSUE TITLE
How to solve the problem of disconnecting for a little while?

### ISSUE THREAD

**Issue by lyjzsyzlt** [felixse/FluentTerminal#520]

**Comment by skipmeister123** [comment]
Don't suppose you could be more specific? Personally, I find a phone call 
or a hand written letter helps to keep the connection alive.

**Comment by lyjzsyzlt** [comment]
i&nbsp;start&nbsp;a&nbsp;terminal,&nbsp;it&nbsp;will&nbsp;be&nbsp;disconnected&nbsp;after&nbsp;5&nbsp;minutes&nbsp;or&nbsp;10&nbsp;minutes&nbsp;due&nbsp;to&nbsp;not&nbsp;using&nbsp;it.&nbsp;how&nbsp;to&nbsp;keep&nbsp;it&nbsp;alive?


---Original---

**Comment by skipmeister123** [comment]
Can I assume you mean an SSH connection?

**Comment by lyjzsyzlt** [comment]
yes,it&nbsp;is&nbsp;ssh&nbsp;connection


---Original---

**Comment by skipmeister123** [comment]
That wouldn't be a FluentTerminal problem. You'll want to either adjust the 
SSH server settings or add a keepalive stanza to your .ssh/config

**Comment by lyjzsyzlt** [comment]
thanks,&nbsp;i&nbsp;will&nbsp;take&nbsp;your&nbsp;adverise&nbsp;and&nbsp;have&nbsp;a&nbsp;try.&nbsp;
ps.&nbsp;the&nbsp;same&nbsp;opreation,&nbsp;the&nbsp;same&nbsp;ssh&nbsp;server,&nbsp;there&nbsp;also&nbsp;are&nbsp;no&nbsp;difference&nbsp;of&nbsp;config&nbsp;file,&nbsp;this&nbsp;problem&nbsp;is&nbsp;not&nbsp;happened&nbsp;on&nbsp;the&nbsp;other&nbsp;PC.



---Original---

**Comment by MaxRis** [comment]
@lyjzsyzlt you also can try to use Mobile Shell (mosh) connection profile (CTRL+SHIFT+Y shortcut). You need to have `mosh` installed on your remote machine and connection ports opened.

**Comment by lyjzsyzlt** [comment]
thanks,&nbsp;i&nbsp;will&nbsp;have&nbsp;a&nbsp;try


---Original---
