### ISSUE TITLE
My fluent terminal don't work，No cursor！

### ISSUE THREAD

**Issue by lcs1998** [felixse/FluentTerminal#524]
![image](https://user-images.githubusercontent.com/40483898/65382404-11052380-dd37-11e9-8774-72368f03062b.png)
My software is the latest version, and my windows' version is the lastest too.

**Comment by felixse** [comment]
Are you using a VPN?

**Comment by lcs1998** [comment]
> Are you using a VPN?

Does this have anything to do with VPN?

**Comment by felixse** [comment]
There is a known issue in 0.5.3.0 where using a VPN might cause problems with the communication between the App process and the WebView. It's already fixed on master and will be shipped with the next release within the next few days.

**Comment by lcs1998** [comment]
> There is a known issue in 0.5.3.0 where using a VPN might cause problems with the communication between the App process and the WebView. It's already fixed on master and will be shipped with the next release within the next few days.

Thank you very much. I have used VPN before, which may be caused by this problem

**Comment by felixse** [comment]
Can you please update to 0.6.0.0 and try it again?

**Comment by lcs1998** [comment]
Thank you very much! It has been used for three days. Now the software is working normally.

**Comment by felixse** [comment]
I'm glad we got this working now 😄
