### ISSUE TITLE
Set language is invalid

### ISSUE THREAD

**Issue by guobing1993** [felixse/FluentTerminal#525]
version : 0.6.0.0

**Comment by DestinyHunter** [comment]
I had the same problem.

**Comment by guobing1993** [comment]
> I had the same problem.

https://poeditor.com/join/project/TfKNIt826z

**Comment by guobing1993** [comment]
@DestinyHunter 
https://poeditor.com/join/project/TfKNIt826z

**Comment by felixse** [comment]
Quick update on this: There is some problem with packaging right now which caused missing translations in the release. I'm quite positive I know how to fix it, but something else is causing problems with creating a package righ now which I couldn't figure out yet.
