### ISSUE TITLE
Copy link location

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#531]
Now that links are clickable, it'd be nice if we could right click and copy the link location.

**Comment by jenia90** [comment]
I would like to help out with it. Any tip where would be a good place to start?

**Comment by felixse** [comment]
In `FluentTerminal.Client/src/index.ts` pass an `ILinkMatcherOptions` to the WebLinksAddon. Implement the callbacks for enter/leave in this options object and then somehow get this down to the App using the `TerminalBridge`. There already is some logic to determine whether the copy menu item is enabled, this would be quite similar.

**Comment by jenia90** [comment]
I came across a problem -- the UWP app is probably stopping the middle/right mouse click events from propagating to xterm and thus the addon doesn't get notified of the event. Any suggestions where should I look in order to propagate the event down to xterm?

**Comment by MaxRis** [comment]
Most of all WebView itself "eats" all events and you should catch them directly in JS code:

"As indicated in the Events table on the WebView class page, web view doesn’t support most of the user input events inherited from UIElement, such as KeyDown, KeyUp, and PointerPressed. Instead, you can use InvokeScriptAsync with the JavaScript eval function to use the HTML event handlers, and to use window.external.notify from the HTML event handler to notify the application using WebView.ScriptNotify."

It's from https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/web-view

**Comment by jenia90** [comment]
Upon right clicking a link do we want the link to be selected and a context menu shown or just straight copy it? 

Also, any ideas why the right functionality (opening a menu or copying the link) works only once and in order to get it working again I have to fire some other event, like selecting something or hitting a random key? Is there some kind of cooldown period after link hover? Can't find anything on this issue online.

**Comment by felixse** [comment]
I would expect it to display a context menu with a "copy link" item. 

No idea, sorry. Didn't actually look into this yet
