### ISSUE TITLE
Context menu white corners glitch.

### ISSUE THREAD

**Issue by Hackmastr** [felixse/FluentTerminal#532]
**How to reproduce?**

Start up Fluent Terminal, right click on a tab.

**Screenshot:**
![image](https://user-images.githubusercontent.com/9281515/65674205-749b9380-e04c-11e9-9be5-b429a9638a6e.png)

**System:**
Fluent Terminal: 0.6.0.0
Windows 10 Pro 1809.

**Comment by felixse** [comment]
Seeing the same on my 1809 machine. Might be a bug in WinUI. Might be worth creating an issue upstream

**Comment by felixse** [comment]
Created an upstream issue here: https://github.com/microsoft/microsoft-ui-xaml/issues/1468
