### ISSUE TITLE
altgr+2 not working properly

### ISSUE THREAD

**Issue by fle108** [felixse/FluentTerminal#534]
hi, I've downloaded v0.6 , however , in every environment (wsl,cmd or powershell) when I hit altgr+2 to bring '~' terminal open a new tab.
I deleted keybinds but now it prints 2 in place of ~

**Comment by DavidCDreher** [comment]
Maybe related: I have a modified registry, such that my capslock key is CTRL. This works for for every app I use, except FluentTerminal.

**Comment by marem-bzh** [comment]
I actually have the same problem as @fle108 here, altgr+2 opens a new tab.
I'm using a french azerty keyboard

**Comment by m-thorsen** [comment]
Many ISO layouts use altgr+numbers for common characters, on Norwegian layout it's "@"

Isn't it possible to listen for Ctrl+Alt without also catching AltGr?

**Comment by felixse** [comment]
Will be part of the next update

Fixed by https://github.com/felixse/FluentTerminal/commit/0dc1a1cd5d702d87c6deddf55945607af355062a
