### ISSUE TITLE
Kotlin-compiler support

### ISSUE THREAD

**Issue by alexmww** [felixse/FluentTerminal#536]
I've tried to add profile with kotlin-compiler as shell executable, but got broken output.

![image](https://user-images.githubusercontent.com/32086218/66059137-bacd8700-e565-11e9-8488-7190cfa1f7c9.png)

Same happens if run from PowerShell inside FluentTerminal

![image](https://user-images.githubusercontent.com/32086218/66059226-dfc1fa00-e565-11e9-9ace-cc5029cd79fd.png)

In regulag powershell everething works fine:

![image](https://user-images.githubusercontent.com/32086218/66059398-2879b300-e566-11e9-8cb1-0f1a16f26099.png)

**Comment by kpchand** [comment]
I get the same juggled output when using bitbucket.

**Comment by alexmww** [comment]
Works as expected in 0.7.5.0
