### ISSUE TITLE
does not support maven arguments

### ISSUE THREAD

**Issue by imloama** [felixse/FluentTerminal#538]
when i use maven cli like 
```
maven clean package -Dmaven.test.skip=true 
```
I got error `Unknown lifecycle phase ".test.skip=true".`

It works in CMD.

Fluent Terminal version 0.6.0.0

**Comment by felixse** [comment]
Does it work when using Fluent Terminal with the CMD profile? Fluent Terminal is using PowerShell as a default. Did you get the same error with the stock PowerShell?

**Comment by imloama** [comment]
Thanks, you are right. I got the same error in PowerShell。
