### ISSUE TITLE
Can not define Environment Variables names in uppercase

### ISSUE THREAD

**Issue by jmparis** [felixse/FluentTerminal#540]
The new feature added in the profiles: Environment variables has a flaw.
It's not possible to define a variable in uppercase.

Example:
USER     john
PATH    /c/msys64/usr/bin

both definitions are saved, and then pass to the shell as
user   john
path   /c/msys64/usr/bin

**Comment by felixse** [comment]
Might be caused/fixed by: https://stackoverflow.com/questions/24143149/keep-casing-when-serializing-dictionaries
