### ISSUE TITLE
WSL 2 support

### ISSUE THREAD

**Issue by soniquete0** [felixse/FluentTerminal#546]
Did anyone figure out how to get the Fluent Terminal working with WSL2 since ti changed from win folder structure to .vhdx ?

**Comment by soniquete0** [comment]
Managed to solve it.
The working directory path in my case was
`\\wsl$\Ubuntu\home\username`

**Comment by auraherrera** [comment]
Just to add more info, you have to write the exact distro name, in my case:
`\\wsl$\\Ubuntu-18.04\\home\\username`

**Comment by pztrn** [comment]
Looks like this issue should be reopened as this will work only for default distribution.

My case: I have set up two custom distributions using Ubuntu 20.04 standart distribution, export it and import with custom name. Currently I can't do something like:

```
wsl -d mydistro
```

Fluent terminal just gives no output at all.

**Comment by skipmeister123** [comment]
It works with WSL2 for me....

**Comment by pztrn** [comment]
@skipmeister123 then what I'm doing wrong?

![image](https://user-images.githubusercontent.com/869402/96746855-0bb65480-13e1-11eb-8212-83f8b216131c.png)

**Comment by skipmeister123** [comment]
I'm fairly certain your working directory should just be ~ (or maybe ~pztrn).

**Comment by pztrn** [comment]
This is true, but if I specify ``~`` - WSL using `/mnt/c/Users/pztrn` which isn't what I want. Hint from @soniquete0 works, actually, but **only** for default distribution (when I'm launching WSL with just ``wsl.exe``, without additional parameters).

My case is that Fluent Terminal is unable to launch WSL2 with custom-named distributions. I definitely have them:

```
PS C:\Users\pztrn> wsl --list --all -q
personal
work
```

Then I'm specifying command line like on my screenshot - as you can see, Fluent Terminal produces no output.

**Comment by skipmeister123** [comment]
Oh, duh... I see your problem. 😅
move "-d personal" to the arguments section.

**Comment by pztrn** [comment]
😅oops, I'm so blind... Thanks :)

**Comment by skipmeister123** [comment]
You're good!  Glad we could sort it out.
