### ISSUE TITLE
SSH Error

### ISSUE THREAD

**Issue by Saafo** [felixse/FluentTerminal#549]
![image](https://user-images.githubusercontent.com/46736350/66801360-67870b80-ef4b-11e9-888d-de1e7b6f38a3.png)  
I'm not sure the meaning of "Could not create directory...".  
My user Name is Chinese, I don't know whether it matters.

**Comment by felixse** [comment]
Looks like an openssh issue to me. @MaxRis any ideas?

**Comment by maxhora** [comment]
I've tried to google for relevant errors and check OpenSSH Windows port source code if it depends on value of %USERNAME%, but was not able to find anything interesting so far.
Have tried to create new user with name in Chinese and Fluent for some reasons on 1st my machine was able to start only PowerShell.exe (cmd.exe and ssh.exe sessions were silent after start), on 2nd machine all shells are silent after the start - no output at all. 😨

**Comment by maxhora** [comment]
Since at the screenshot it's possible to see `'` around file path, the issue might be related to https://github.com/felixse/FluentTerminal/issues/685

**Comment by Saafo** [comment]
Oh... I had left Windows for a long time, so I can't help you solving this problem any more... orz
