### ISSUE TITLE
Keybindings for "previous tab" and "next tab" not working

### ISSUE THREAD

**Issue by janpfeifer** [felixse/FluentTerminal#554]
Freshly installed (yesterday) Windows 10 + Choco + FluentTerminal + WSL + Ubuntu18.01.

The default "Control Tab" doesn't change tabs, and neither if I set up something else. But I still suspect an issue with the "device" between the screen and the keyboard :)

Any pointers would be most welcome!

**Comment by felixse** [comment]
maybe something in your shell config handling ctrl+tab?

**Comment by janpfeifer** [comment]
Thanks! But I think that was not it.

But a bit more trying ... and it turns out if I close and reopen the terminal it then works.

But once I change the settings, even if to restore the defaults, the "next tab" / "previous tab" stop working here.

**Comment by felixse** [comment]
Not sure what is going on here, but I cannot reproduce it and nobody else reported this. I'm closing this now
