### ISSUE TITLE
Prerequisites are outdated

### ISSUE THREAD

**Issue by kiritofeng** [felixse/FluentTerminal#555]
While installing on Windows version 1803, I encountered the following error while running `Install.ps1` from v0.6.1

```
Add-AppxPackage : A parameter cannot be found that matches parameter name 'ForceUpdateFromAnyVersion'.
At C:\Users\<redacted>\Downloads\FluentTerminal.Package_0.6.1.0_Test\Install.ps1:452 char:137
+ ... ackages.FullName -ForceApplicationShutdown -ForceUpdateFromAnyVersion
+                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
  + CategoryInfo          : InvalidArgument: (:) [Add-AppxPackage], ParameterBindingException
  + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageComm
     and
Error: Could not install the app.
```

This was fixed by updating to Windows 1903, suggesting that the minimum version of Windows required is at least 1809, rather than the Fall Creators Update as indicated from the README.

**Comment by kiritofeng** [comment]
As a side note, the `Install.ps1` bundled with v0.6.0 does work on Windows 1803

**Comment by dbhorst** [comment]
Same problem here with Windows 10 1803. I'm not able to upgrade, because it's a company notebook.

Chocolatey v0.10.15

> C:\WINDOWS\system32>choco install -y fluent-terminal
> Chocolatey v0.10.15
> Installing the following packages:
> fluent-terminal
> By installing you accept licenses for the packages.
> Progress: Downloading fluent-terminal 0.6.1.0... 100%
> 
> fluent-terminal v0.6.1.0 [Approved]
> fluent-terminal package files install completed. Performing other installation steps.
> Running on: Windows 10 Enterprise, (Enterprise), Windows Kernel: 10.0.17134
> Enabling App Sideloading
> Der Vorgang wurde erfolgreich beendet.
> 
> Extracting C:\ProgramData\chocolatey\lib\fluent-terminal\tools\FluentTerminal.App_0.6.1.0_Test.zip to C:\ProgramData\chocolatey\lib\fluent-terminal\install...
> C:\ProgramData\chocolatey\lib\fluent-terminal\install
> Found bundle: C:\ProgramData\chocolatey\lib\fluent-terminal\install\FluentTerminal.Package_0.6.1.0_x86_x64.appxbundle
> 
> Installing app...
> Found dependency package(s):
> C:\ProgramData\chocolatey\lib\fluent-terminal\install\Dependencies\x86\Microsoft.NET.Native.Framework.2.2.appx
> C:\ProgramData\chocolatey\lib\fluent-terminal\install\Dependencies\x86\Microsoft.NET.Native.Runtime.2.2.appx
> C:\ProgramData\chocolatey\lib\fluent-terminal\install\Dependencies\x86\Microsoft.UI.Xaml.2.2.appx
> C:\ProgramData\chocolatey\lib\fluent-terminal\install\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx
> C:\ProgramData\chocolatey\lib\fluent-terminal\install\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx
> C:\ProgramData\chocolatey\lib\fluent-terminal\install\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx
> C:\ProgramData\chocolatey\lib\fluent-terminal\install\Dependencies\x64\Microsoft.UI.Xaml.2.2.appx
> C:\ProgramData\chocolatey\lib\fluent-terminal\install\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
> A parameter cannot be found that matches parameter name 'ForceUpdateFromAnyVersion'.
> Error: Could not install the app.
> The install of fluent-terminal was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\fluent-terminal\tools\chocolateyinstall.ps1'.
>  See log for details.
> 
> Chocolatey installed 0/1 packages. 1 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
>  \- fluent-terminal (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\fluent-terminal\tools\chocolateyinstall.ps1'.
>  See log for details.
