### ISSUE TITLE
Text selected with keyboard cannot be copied from context menu

### ISSUE THREAD

**Issue by TailyFair** [felixse/FluentTerminal#556]
Version: 0.6.1.0

**Issue:**
In mouse context menu Copy function is not available if text was selected using keyboard.

**How to reproduce:**
- Write text in input
- Using keyboard (SHIFT + Arrow keys) select text
- Using mouse, press right button on selected text
- Copy function is not available

![image](https://user-images.githubusercontent.com/27275873/67205784-1b3f3e00-f419-11e9-8d60-c719cbcb3d43.png)

**Expected:**
- Text that was selected using keyboard should be available to copy using mouse context menu.

**Comment by felixse** [comment]
The text selection with (ctrl +) shift + arrows you see in PowerShell is something that is provided by the PSReadline module. It appears like a selection but technically is not (that's also why it looks a bit different). I'm afraid we have no way to detect whether something is selected there.
