### ISSUE TITLE
Changing terminal options crashes app

### ISSUE THREAD

**Issue by jenia90** [felixse/FluentTerminal#559]
While working on implementing the Font Weight feature #527 I've come across a bug that when changing terminal options an InvalidCastException is thrown when calling `RaisePropertyChanged(nameof(BackgroundOpacity));` in `TerminalViewModel.cs\OnTerminalOptionsChanged`. 

If i comment the line out everything works as expected. Is this line needed? If not I can remove it when submitting a PR for #527.

**Comment by IgnusG** [comment]
Changing the background opacity crashes the app for me (it keeps he changed opacity though). Is this related?

**Comment by jenia90** [comment]
Yeah, every terminal option you change ends with a crash, but since storing of TerminalOptions occurs prior to the problematic line you see it applied next time you launch the app.

Best regards,
Jenia

________________________________

**Comment by felixse** [comment]
Can no longer reproduce this
