### ISSUE TITLE
Issue after installing 0.1.12

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#56]
![image](https://user-images.githubusercontent.com/1911919/42943851-fae3233e-8b31-11e8-81c2-7c30505546df.png)

**Comment by skipmeister123** [comment]
I installed the nodeps package, if it makes a difference

**Comment by felixse** [comment]
Can you try the package with dependencies?

**Comment by felixse** [comment]
Have you tried any other shell profile?

**Comment by skipmeister123** [comment]
It just errors out as soon as I open the app.  I can't even get to the settings. Trying to do so kills the app.  I wonder if this is because I had my default profile set to my custom Ubuntu profile, which was then replaced?

--
Hans Kokx
On 7/19/2018 11:02:02 AM, Felix <notifications@github.com> wrote:
Have you tried any other shell profile?

**Comment by felixse** [comment]
Strange. The new WSL should not override your custom one, just another entry in the list. Must be something else. Can you try uinstalling and then reinstalling it? This should reset your settings

**Comment by skipmeister123** [comment]
I did that a couple times. I'm not 100% sure it reset all my settings
though.

Hans Kokx

**Comment by felixse** [comment]
Do you see anything in Windows Event Log?

**Comment by skipmeister123** [comment]
You're in luck.

Faulting application name: FluentTerminal.App.exe, version: 1.0.0.0, time stamp: 0x5b5067c9
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.17134.81, time stamp: 0x4f4899f8
Exception code: 0xc000027b
Fault offset: 0x00000000006a4e02
Faulting process id: 0x41a0
Faulting application start time: 0x01d41f718eb8a6ae
Faulting application path: C:\Program Files\WindowsApps\53621FSApps.FluentTerminal_0.1.12.0_x64__87x1pks76srcp\FluentTerminal.App.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 1103188d-cc36-4adc-b3cd-4c29b820524c
Faulting package full name: 53621FSApps.FluentTerminal_0.1.12.0_x64__87x1pks76srcp
Faulting package-relative application ID: App

--
Hans Kokx
On 7/19/2018 12:52:57 PM, Felix <notifications@github.com> wrote:
Do you see anything in Windows Event Log?

**Comment by skipmeister123** [comment]
On a different machine, I renamed my Ubuntu profile to "My Profile", and installed 0.1.13.  I got the following message:
![image](https://user-images.githubusercontent.com/1911919/42967549-99c90662-8b6e-11e8-806c-fe4a6e19bba0.png)


The program FluentTerminal.SystemTray.exe version 1.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 5814
 Start Time: 01d41af041e26cd2
 Termination Time: 4294967295
 Application Path: C:\Program Files\WindowsApps\53621FSApps.FluentTerminal_0.1.11.0_x64__87x1pks76srcp\Win32\FluentTerminal.SystemTray.exe
 Report Id: 45f5231b-2e05-4e03-bd1a-35761eeff969
 Faulting package full name: 53621FSApps.FluentTerminal_0.1.11.0_x64__87x1pks76srcp
 Faulting package-relative application ID: App

**Comment by felixse** [comment]
Ok, I can reproduce your problem now, seems to something about having a custom profile and updating to 0.1.12.

**Comment by skipmeister123** [comment]
Excellent news. :)

--
Hans Kokx
On 7/19/2018 4:21:09 PM, Felix <notifications@github.com> wrote:
Ok, I can reproduce your problem now, seems to something about having a custom profile and updating to 0.1.12.

**Comment by felixse** [comment]
Just released 0.1.14, this should fix your issue 😅

**Comment by skipmeister123** [comment]
Yes; good. That works.
