### ISSUE TITLE
Edit built-in profile arguments

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#57]
I need to edit the built-in profile arguments.

For example, when opening WSL, I need to provide the argument "~" to automatically cd to my WSL $HOME.

**Comment by felixse** [comment]
Plan is to make directory and arguments editable and restorable. But for now you can just create a custom one with your arguments

**Comment by fle108** [comment]
hi, which argument for wsl home do I have to put ?
I tried "~" ; $home; /home/user; but it doesn't work : \

**Comment by skipmeister123** [comment]
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/felixse/FluentTerminal/issues/57?email_source=notifications\u0026email_token=AAOSY35YFLOTTVRCY3ZADQLQMI6KZA5CNFSM4FK4UDA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD76SFZI#issuecomment-536683237",
"url": "https://github.com/felixse/FluentTerminal/issues/57?email_source=notifications\u0026email_token=AAOSY35YFLOTTVRCY3ZADQLQMI6KZA5CNFSM4FK4UDA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD76SFZI#issuecomment-536683237",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by fle108** [comment]
ok sorry my, I found... just "~" in argument line and not in working dir line.... thank you ;)

**Comment by skipmeister123** [comment]
Glad it worked out :) It's not intuitive.
