### ISSUE TITLE
Cannot grab title bar to move window

### ISSUE THREAD

**Issue by joshball** [felixse/FluentTerminal#570]
Running 0.6.1.0
The title bar is setup so that you cannot grab and move the window except for a small area to the left of the three buttons on the right, 
![image](https://user-images.githubusercontent.com/127526/68334819-9864e700-0098-11ea-8342-84cf49aeecb4.png)

Any reason for this? It goes against all (most?) windows apps. 
If so, can we at least make the area you can grab a different color?

Thanks!

**Comment by felixse** [comment]
That's not intended. The complete title bar (except the button on the left) should be grabable.
Does this happen all the time?
