### ISSUE TITLE
Tabs on bottom

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#58]
When I put the tabs on the bottom, they only move to the bottom when there's more than one tab.  I'd prefer to have them always on the bottom.

**Comment by felixse** [comment]
We don't really have tabs when there is only one tab, just a title and a add button.
I'm thinking about moving the add button to the new 'hamburger menu' and showing the title of the current tab when tabs are on bottom. And then finally add a always show tabs option.
Guess this should make everyone happy.

**Comment by skipmeister123** [comment]
Please don't move the new tab button.  It should absolutely be next to the tabs.  I think that a single tab should act as a tab, instead of as a title... at least when tabs are on the bottom.  That's my 2 cents.

--
Hans Kokx
On 7/24/2018 2:13:26 AM, Felix <notifications@github.com> wrote:
We don't really have tabs when there is only one tab, just a title and a add button.
I'm thinking about moving the add button to the new 'hamburger menu' and showing the title of the current tab when tabs are on bottom. And then finally add a always show tabs option.
Guess this should make everyone happy.

**Comment by felixse** [comment]
Yes, it will totally stay in the tab bar, I just want to remove it when there is only one tab. Right now the title looks a bit cramped between the menu and the add tab button

**Comment by skipmeister123** [comment]
How about the option for "always show tabs, even when there is only one"?  That might make everybody happy.

--
Hans Kokx
On 7/25/2018 1:54:16 AM, Felix <notifications@github.com> wrote:
Yes, it will totally stay in the tab bar, I just want to remove it when there is only one tab. Right now the title looks a bit cramped between the menu and the add tab button

**Comment by felixse** [comment]
yes, that's also an integral part of the 'make everyone happy' package 😄
