### ISSUE TITLE
Can not activate Anaconda virtual  environment

### ISSUE THREAD

**Issue by lyjzsyzlt** [felixse/FluentTerminal#587]
I found that the fluent terminal could not atviate anaconda environment. For example, after i input the command ```activate py36```, it did not switch to “py36” environment, it is still in base envirnoment. But this command works in CMD
![image](https://user-images.githubusercontent.com/30644064/69331552-ef211200-0c8f-11ea-93a3-dc088640cb29.png)

**Comment by K-JW** [comment]
This is a bug of Conda or PowerShell,  you can refs. [this](https://github.com/conda/conda/issues/8428)

**Comment by lyjzsyzlt** [comment]
ok,&nbsp;thanks&nbsp;*^O^*


---Original---
