### ISSUE TITLE
Select to copy should deselect text after it's been copied

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#59]
In order to maintain parity with other terminal emulators

**Comment by felixse** [comment]
Yeah, makes sense to keep parity. Didn't think about this since I don't use this. Only problem I see is that we might need to disable copy on select in search mode, since xterm.js is using selects to highlight the matches

**Comment by skipmeister123** [comment]
That sounds like a fair compromise in behavior.

--
Hans Kokx
On 7/24/2018 2:06:50 AM, Felix <notifications@github.com> wrote:
Yeah, makes sense to keep parity. Didn't think about this since I don't use this. Only problem I see is that we might need to disable copy on select in search mode, since xterm.js is using selects to highlight the matches

**Comment by IgnusG** [comment]
I was actually just about to create an issue against this behavior.

Currently the selection is not even displayed when double clicking a word - this misleads the user (they don't know how much or even if they selected something). The prompt `Text copied` is helpful but again displays once and if selecting quickly just stays there - difficult to see if the prompt refreshed or just waiting for timeout to disappear.
The selection also disappear far too quickly after selecting the text with the mouse regularly - no time to check if the selection was indeed correct.

I would at least suggest a timeout for the selection to disappear after maybe 1~2 seconds or make this configurable (disappear or stay).

Terminus for example keeps the selection on the screen. Linux terminals also work similar to this.
