### ISSUE TITLE
Scoop, sudo and more not being recognized by fluent-terminal but work fine in Powershell?

### ISSUE THREAD

**Issue by taimoorgit** [felixse/FluentTerminal#590]
![image](https://user-images.githubusercontent.com/37668804/69502770-fd19a180-0ee0-11ea-82bb-707b138fcf6e.png)

I very recently installed `scoop`, `sudo` and other tools. These tools work fine in PowerShell, but are nowhere to be seen in Fluent Terminal. How can I fix this?

**Comment by taimoorgit** [comment]
So it turns out that after installing packages from `pip`, PowerShell or whatever you have to restart your PC. Kind of sucks. Feel free to close this ticket if needed!

**Comment by felixse** [comment]
It should be enough to close the system tray component of Fluent Terminal. Some more details why this is necessary is explained here: https://github.com/felixse/FluentTerminal/issues/131
