### ISSUE TITLE
Fluent Terminal cannot be opened

### ISSUE THREAD

**Issue by sunch4se** [felixse/FluentTerminal#596]
FluentTerminal was successfully installed via choco:
"2019-11-27 08:08:21,678 13032 [INFO ] -  The install of fluent-terminal was successful.
2019-11-27 08:08:21,687 13032 [INFO ] -   Software installed to 'C:\ProgramData\chocolatey\lib\fluent-terminal\install'"

The folder "C:\ProgramData\chocolatey\lib\fluent-terminal\install" is not created though, flute.exe does not start and "fluent terminal" cannot be found in the windows start menu.

**Comment by Ronkiro** [comment]
Did you use admin rights while installing?
