### ISSUE TITLE
Default profile not retained

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#61]
For whatever reason, my default profile isn't retained between launches all the time.  I created a custom profile for WSL, and set it as default.  Many times, when I launch the app, I get a PowerShell instead of my custom WSL.

Forgive my ignorance, but do the settings living in roaming mean that the default profile is shared across my devices?  If I create a custom profile on multiple devices (because, for whatever reason, it didn't sync?), and set the custom profile as my default: if the profile ID doesn't match across devices, will that cause it to revert to the "default" default?

**Comment by felixse** [comment]
Yes, that might exactly be the reason. We store everything except the profiles in roaming, but the default profile should also be stored in local of course
