### ISSUE TITLE
Closing one window exited the program

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#62]
I had two windows open.  When I closed one of them, all my windows closed and the program quit.

**Comment by felixse** [comment]
Do you know any steps to reproduce this, or did it only happen once? I had no luck reproducing it

**Comment by skipmeister123** [comment]
It only happened once for me.  I haven't tried to reproduce it.

--
Hans Kokx
On 7/31/2018 4:36:22 PM, Felix <notifications@github.com> wrote:
Do you know any steps to reproduce this, or did it only happen once? I had no luck reproducing it

**Comment by skipmeister123** [comment]
I still don't know a reliable way to reproduce this, but it's happened several times to me. It doesn't appear to close *all* the windows - I had 3 open, closed one, another one closed itself, and one stayed open.
