### ISSUE TITLE
When clicking the menu button in top-left corner to access Settings, Fluent crashes

### ISSUE THREAD

**Issue by yoSlick** [felixse/FluentTerminal#629]

**Comment by felixse** [comment]
What version of Windows 10 are using?

**Comment by MDormann** [comment]
I have the same problem with Windows 10 1803.

Edition                       Windows 10 Enterprise
Version                      1803
Betriebssystembuild   17134.1184

**Comment by bk1285** [comment]
Confirmed with

- Windows 10 Enterprise 1709
- Build 16299.1625

**Comment by bk1285** [comment]
Is there any log-file, I can provide to you?

**Comment by felixse** [comment]
Someone with 1803 could try to debug this. I think it might be quite obvious once the environment is set up. Else I will try to find a 1803 image I can put on a VM

**Comment by felixse** [comment]
tracked in #528
