### ISSUE TITLE
How do i enable the default (?) styles?

### ISSUE THREAD

**Issue by Ronkiro** [felixse/FluentTerminal#634]
Basically i got the terminal as this:

![image](https://user-images.githubusercontent.com/27526023/71483212-84f71200-27e5-11ea-8c3d-ee12a5a8f1e4.png)

It doesn't shows the arts and styles as shown in the SS'

![image](https://user-images.githubusercontent.com/27526023/71483256-afe16600-27e5-11ea-85e3-9a0795111fae.png)

Do i need to enable anything to do so?

**Comment by felixse** [comment]
I have described my config for the screenshot [here](https://github.com/felixse/FluentTerminal/wiki/FAQ#how-can-i-achieve-the-look-of-the-terminal-in-the-readme)
