### ISSUE TITLE
Add Scoop to readme

### ISSUE THREAD

**Issue by Restia666Ashdoll** [felixse/FluentTerminal#637]
Fluent Terminal is now available on scoop. 
https://github.com/TheRandomLabs/scoop-nonportable/blob/master/bucket/fluent-terminal-np.json
So, please add this to readme
- Install [Scoop](https://scoop.sh/)
- Install 7zip and git (to add buckets) - `scoop install 7zip git`
- From an elevated/admin shell, execute
```
 scoop bucket add nonportable
 scoop install fluent-terminal-np
```

**Comment by Restia666Ashdoll** [comment]
Also https://github.com/felixse/FluentTerminal/issues/383 can be closed

**Comment by felixse** [comment]
Done. Thanks for for bringing this to scoop 👍
