### ISSUE TITLE
Tab title should show profile's name, instead of shell path

### ISSUE THREAD

**Issue by shinywong** [felixse/FluentTerminal#639]
I think it would be better to show the profile's name in the title of Tabs. The shell exe location is often too long and truncated, and it is unnecessary to know the path.

**Comment by felixse** [comment]
Sounds like a good idea

**Comment by Ronkiro** [comment]
What about a new field to add a custom name to the tab? If empty, the default would be profile's name.

**Comment by BasixKOR** [comment]
@Ronkiro You can do that by right-click the tab and click 'Edit Title'.
