### ISSUE TITLE
cannot install because of HRESULT: 0x80073CF9

### ISSUE THREAD

**Issue by QuarterHeaven** [felixse/FluentTerminal#645]
On Windows 10  1904.1 I cant install it. I've tried all methods to fix it but failed. Can anybody help me?
![4}{ (A0_U}A8H {O9GU9VE3](https://user-images.githubusercontent.com/41909950/71765852-5a6b2e80-2f34-11ea-9f80-7dda88bd94e1.png)

**Comment by felixse** [comment]
I don't know what exactly this is, but if you search for it there are some guides on how to fix it. I'm closing this since it's more of a Windows 10 problem rather than Fluent Terminal
