### ISSUE TITLE
Block select

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#65]
I'd like to be able to block-select text from the console.  My first attempt was by holding the middle mouse button and dragging a box around where I wanted to select. Obviously that didn't work.  Then I tried to hold alt and drag around where I wanted to select.  That didn't work either.  Finally, I went digging through the settings only to realize I was being silly, and you just couldn't do it at all.  I think we should add that.

**Comment by felixse** [comment]
This should actually be possible with the newest version, it was added in xterm.js 3.5.0 (https://github.com/xtermjs/xterm.js/releases/tag/3.5.0)

**Comment by felixse** [comment]
Did alt + select work for you with the latest version?

**Comment by skipmeister123** [comment]
Yes; it works.  I hadn't tried it until now -- but that does explain why my cursor kept changing to a cross every time I alt-tabbed to the window.

--
Hans Kokx
On 8/17/2018 1:54:46 AM, Felix <notifications@github.com> wrote:
Did alt + select work for you with the latest version?

**Comment by felixse** [comment]
I noticed this too, seems to be a [xterm.js feature](https://github.com/xtermjs/xterm.js/blob/38debf77f8c18a2ec01883d0b1184021b0de62a1/src/xterm.css#L142)

Should we overwrite it?
