### ISSUE TITLE
Unable to start debugging

### ISSUE THREAD

**Issue by floatas** [felixse/FluentTerminal#653]
I followed (https://github.com/felixse/FluentTerminal/wiki/How-to-set-up-a-development-environment). However when I start debugging x64 "Local Machine" on "FluentTerminal.App" nothing happens, Build starts and finishes with few dependency warnings, but project doesn't start.
Am I missing something ? How to start debugging ?

**Comment by floatas** [comment]
No problem thanks. Can confirm that running Package project works for me.
Can't comment on other steps in current (outdated) instructions, since I had most of it already preinstalled.

**Comment by floatas** [comment]
Feel free to close this issue now or when documentation is updated.

**Comment by usernamedd** [comment]
In fact , the same issue hits me , and I can not find usefule info from https://github.com/felixse/FluentTerminal/wiki/How-to-set-up-a-development-environment. It does not tell how to debug.
