### ISSUE TITLE
Hope it could have default terminal feature

### ISSUE THREAD

**Issue by GloryAlex** [felixse/FluentTerminal#654]
I love this terminal. However, I can't use it as a default terminal to replace default windows terminal. Hope it could replace default windows terminal, like the ConEmu.

**Comment by felixse** [comment]
ConEmu's default terminal feature is rather hacky afaik and I don't think we can pull this off easily.
I hope Microsoft will provide an API for this in the future as mentioned [here](https://github.com/microsoft/Terminal/issues/492) which we can also use then

**Comment by GloryAlex** [comment]
Thank you. I hope so.
