### ISSUE TITLE
The text be bluer and bugger

### ISSUE THREAD

**Issue by KevinZonda** [felixse/FluentTerminal#655]
What's wrong with my FluentTerminal? I just install and run, then... :(

My Windows version is Windows10 Enterprise LTSB 1809(17763.107) and FluentTerminal 0.6.1.0

![Sample](https://user-images.githubusercontent.com/33132228/72948947-c4535700-3dc1-11ea-842d-1589b56669c9.png)

**Comment by felixse** [comment]
Looks like you have overridden your powershell colors. Have a look at this issue: https://github.com/felixse/FluentTerminal/issues/90

**Comment by KevinZonda** [comment]
> 
> 
> Looks like you have overridden your powershell colors. Have a look at this issue: #90

I solved it by removing the following things in reg about Consoles(CMD & Powershell).

In `HKEY_USERS`, all items called Console. Like `\HKEY_USERS\S-1-5-18\Console`.
In `HKEY_CURRENT_USER\Console`, all subkeys which is related to cmd and powershell.

**Comment by KevinZonda** [comment]
Thanks a lot!
