### ISSUE TITLE
Text is bold even though "Settings > Terminal > Bold text" is off

### ISSUE THREAD

**Issue by igorgatis** [felixse/FluentTerminal#657]
The screenshot below show differences between FluentTerminal and ConEmu. It is bolder in FluentTerminal even though "Bold text" is off:

![image](https://user-images.githubusercontent.com/1269388/73026159-aad8fc00-3e0f-11ea-8933-abda34a98c05.png)

Why and how to fix?

**Comment by felixse** [comment]
Bold would look more bold, guess this is due to different font renderings (Edge WebView vs whatever ConEmu uses)

**Comment by igorgatis** [comment]
Any chance of adding advanced font settings knobs?

**Comment by felixse** [comment]
Do you have anything in mind? We have size, boldness and family. I'm afraid there is nothing else we can customize.

**Comment by Esfera5** [comment]
https://github.com/felixse/FluentTerminal/blob/21631f5cca744a1e30ea7c339f0526626a906ecc/FluentTerminal.Client/src/index.ts#L264

Perhaps allowing different values for these thresholds.

I failed to compile fluent terminal on my machine otheriwse I'd test whether chaning these values make any difference. I'm using Consolas font, in case you want to give it a try.

**Comment by igorgatis** [comment]
#560 fixed it. Thanks!
