### ISSUE TITLE
can't use keyboard shortcut start ssh profile

### ISSUE THREAD

**Issue by onlyJinx** [felixse/FluentTerminal#658]
Hi,

why i can't use the keyboard shortcut start ssh profile? i have changed to other keyboard shortcut but it still can't work.

![无标题](https://user-images.githubusercontent.com/21324835/73137574-a4a78180-4094-11ea-9363-87272ec0560e.png)

**Comment by felixse** [comment]
I can reproduce this with the current release (0.6.1.0) but it seems fixed on master. I got the keybinding working by completely restarting Fluent Terminal (right click on the tray symbol and click on quit)

**Comment by onlyJinx** [comment]
Yes, this problem has been solved after I tried to restart the computer, thank you!
