### ISSUE TITLE
Where are custom profiles stored or is it possible to save profiles in the first place?

### ISSUE THREAD

**Issue by nurky** [felixse/FluentTerminal#663]
I have set up my profiles awhile ago, and wanted to do a Windows reset but I could not find any "Save Profile" options inside the FluentTerminal.

Has this option been implemented yet?

**Comment by felixse** [comment]
You can use the CLI to export and import settings including profiles. Have a look here: https://github.com/felixse/FluentTerminal/wiki/Command-Line-Arguments#settings

**Comment by nurky** [comment]
@felixse I've set it up 😄 

Thank you 🥇
