### ISSUE TITLE
Display issue with symbols on different keyboard layouts

### ISSUE THREAD

**Issue by fasetto** [felixse/FluentTerminal#667]
I'm trying to type ~ symbol via turkish keyboard layout. Fluent Terminal doesn't display that.
When I try to cd into home directory it works, but its invisible.
**AltGr + ü** = ~ in turkish layout.

**Comment by felixse** [comment]
What shell are you experiencing this with?

**Comment by fasetto** [comment]
Never mind. Its not an issue related to your app.
Closing this.
