### ISSUE TITLE
BufferedReader causes issues with ConPty and PowerShell

### ISSUE THREAD

**Issue by felixse** [felixse/FluentTerminal#669]
![8d2xmHQPBl](https://user-images.githubusercontent.com/30559812/75281972-85754e80-5810-11ea-9293-85e7e8b72592.gif)

Experiencing this with this exact combination. If I switch to WinPty or revert changes in ConPtySession that introduced the BufferedReader its behaving normally.

Output log:
[20200225084737086_Powershell.log](https://github.com/felixse/FluentTerminal/files/4251861/20200225084737086_Powershell.log)

**Comment by vasiby** [comment]
Started to see something similar since xterm 4.2.0, even if I build 0.6.1 tag with the latest xterm, have to build it using npm ci, because npm install will download the latest xterm and cause this buffer issue

**Comment by felixse** [comment]
not sure if this is the same problem. Do you experience this with ConPty or WinPty?

**Comment by vasiby** [comment]
ConPTY and oh-my-posh module in powershell, only 0.6.1 branch is  stable with xterm 4.0.1.

**Comment by peske** [comment]
I cannot reproduce this one, but I'm using standard prompt (`PS C:\Users\fatdragon>`). Can you check with the regular prompt? Can you send me your prompt function so that I can check?

**Comment by felixse** [comment]
Same issues without my profile. What version of powershell are you testing this with? I'm on 7.0

**Comment by peske** [comment]
Oh, I have it. It happens only for ConPTY, right?
