### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by brullsker** [felixse/FluentTerminal#67]
Are there any plans to translate the app into more languages?

**Comment by felixse** [comment]
It's not like there are plans, but if we find some contributors we could totally do that.
So if we find some people I can set up a POEditor project and add x:uids to our controls.
I can provide german translations.

**Comment by BaRRaKudaRain** [comment]
What about Russian translation?

**Comment by felixse** [comment]
I don't speak Russian, so someone would need to volunteer for the translation

**Comment by felixse** [comment]
Once everything is prepared for i18n, I will open a project on https://poeditor.com and add you as a contributor, thanks for your help 👍

**Comment by ericcornelissen** [comment]
I'm interested in providing a Dutch translation as well 🙂

**Comment by felixse** [comment]
Localisation is now supported. You can contribute to existing languages or add a new one here:
https://poeditor.com/join/project/TfKNIt826z

**Comment by BaRRaKudaRain** [comment]
It's good. Time to work! :)

-----Original Message-----

**Comment by spencerwooo** [comment]
![image](https://user-images.githubusercontent.com/32114380/57577748-6d665580-74b0-11e9-9100-15609a8544bf.png)

@felixse Where exactly does the term "Identity File Path" appear in Flute? I'm not sure how to translate this into Chinese.

BTW, Chinese translation is almost done with just this one term left. 🍻

**Comment by felixse** [comment]
@spencerwooo In the new ssh tab dialog (alt+t by default)
Thanks for your help 👍

**Comment by spencerwooo** [comment]
@felixse Hmmm, is it the path to the ssh private key? I translated it like so, I hope I didn't misunderstand it.

**Comment by mjs** [comment]
@spencerwooo it is the private key file, but it's often referred to as the identity file. See here: https://man.openbsd.org/ssh#i

**Comment by Djdany95** [comment]
Hey! I can help with the spanish translation :D
