### ISSUE TITLE
Alt modifier not passing through to WSL Bash terminal

### ISSUE THREAD

**Issue by EternalDeiwos** [felixse/FluentTerminal#670]
Title pretty much says it all. 

I use a terminal window manager called byobu (based on tmux) that has Alt+LArrow / Alt+RArrow bound to switch between windows and I can't use it. Other key bindings (such as shift and ctrl) function as expected.

**Comment by felixse** [comment]
I can reproduce this. Same happens with the terminal integrated in vscode. This indicates that's its a problem with either byobu or xterm.js (the component Fluent Terminal and a lot of other terminals like vscode use to render). I'm afraid I cannot help you with that, I suggest you create an issue in the xterm.js repository or ask in the byobu repository

**Comment by 75re** [comment]
> Title pretty much says it all.
> 
> I use a terminal window manager called byobu (based on tmux) that has Alt+LArrow / Alt+RArrow bound to switch between windows and I can't use it. Other key bindings (such as shift and ctrl) function as expected.

I've been struggling with this problem,too. Have you found the solution?
