### ISSUE TITLE
Ability to tell if current terminal is FluentTerminal?

### ISSUE THREAD

**Issue by rythos42** [felixse/FluentTerminal#674]
I have some Powershell scripts that open more Fluent tabs, but because of other developers I work with I had to make the script take a parameter, which I now have to type whenever I use the scripts.

Is there an environment variable that I could read to tell if the current terminal is FluentTerminal? (or some other method)

Thanks!

**Comment by felixse** [comment]
TERM_PROGRAM is set to the value `FluentTerminal`

**Comment by rythos42** [comment]
Thanks, works perfect!
