### ISSUE TITLE
URL detection fails when an @ is in the URL

### ISSUE THREAD

**Issue by mrrcollins** [felixse/FluentTerminal#679]
Just found this, Medium urls with an @ stop right before the @:
`https://medium.com/@jessevondoom/introducing-substation-cd9612d04f82`

![image](https://user-images.githubusercontent.com/2685729/77055436-44073780-69a7-11ea-9659-ebfacb15c56c.png)

**Comment by felixse** [comment]
Fixed with latest xterm.js
