### ISSUE TITLE
Add SSH jump point while setting up SSH-Profiles

### ISSUE THREAD

**Issue by IsCoelacanth** [felixse/FluentTerminal#683]
there's no option to add a jump point when setting up a SSH profile.
Am I missing something or is this option not available yet?

**Comment by felixse** [comment]
like this? https://wiki.gentoo.org/wiki/SSH_jump_host

Not supported in the profile gui right now, but you could try it with the quick launch dialog (it supports ssh commands)

**Comment by IsCoelacanth** [comment]
I keep getting this when I try to start it from the quick launch dialog. doesn't happen when I don't mention DynamicJumps or specify a port. 

command `ssh -p #### -J jump@jumppoint target@targetpoint`

```
CreateProcessW failed error:2
posix_spawn: No such file or directory
```

**Comment by maxhora** [comment]
@IsCoelacanth  Seems a [known issue](https://serverfault.com/a/956614) related to OpenSSH itself,

Could you please try to run above command in the quick launch dialog with full path to ssh.exe like below:

`C:\Windows\System32\OpenSSH\ssh.exe -p #### -J jump@jumppoint target@targetpoint`

**Comment by IsCoelacanth** [comment]
hey @maxhora that gave a new error/pop-up 
![image](https://user-images.githubusercontent.com/21973459/78428548-f3275c80-7691-11ea-93ce-68668e698d4d.png)

**Comment by maxhora** [comment]
@IsCoelacanth please check the correct full path to `ssh.exe` at your machine with `where ssh` and try to use it. Probably, the location of `ssh.exe` is different on your machine.

**Comment by IsCoelacanth** [comment]
@maxhora I've verified it, it's the same path, and there's not other install of SSH anywhere as well.

right now as a workaround I'm using a wsl shell and its ssh to use jumps, be a lot better if I didn't have to.

**Comment by maxhora** [comment]
@IsCoelacanth have you tried to run the same command in standard `cmd.exe` shell window, not in Fluent?

**Comment by IsCoelacanth** [comment]
yeah, getting the same `CreateProcessW failed error:2 posix_spawn: No such file or directory` error. Looks like openssh doesn't work with ports and Jumps, normal SSH without specifying ports and jump seems to work.

**Comment by maxhora** [comment]
@IsCoelacanth thanks for checking, closing the issue as it is not related to Fluent.
Please check following discussion https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777 to get it fixed locally (hopefully)
