### ISSUE TITLE
All profiles are gone after updating to 0.7.0.0

### ISSUE THREAD

**Issue by re3lex** [felixse/FluentTerminal#684]
Hi,
Just downloaded zip file with latest release (0.7.0.0), run update.ps1 as per readme.txt,
After update all my saved profiles are disappeared :(.
How to restore them?

**Comment by dual-oo** [comment]
I can confirm that

**Comment by felixse** [comment]
I'm afraid there is no way to restore them if the new version is already installed. Do you see them in the config.json the update script copied to it's directory?

**Comment by re3lex** [comment]
Can you please tell where to find that directory?

**Comment by felixse** [comment]
Next to the update.ps1, probably in your downloads folder

**Comment by re3lex** [comment]
Yeah, I see `config.json` inside installer folder.
Can I just put it back to `LOCALAPPDATA\Packages\53621FSApps.FluentTerminal_87x1pks76srcp\LocalState` folder?

**Comment by felixse** [comment]
if the profiles array in it contains your profiles. Run `flute settings —import` afterwards

**Comment by re3lex** [comment]
hmm. Looks like that file doesn't contain my profiles.
So did I lose all my profiles?

**Comment by felixse** [comment]
Yes, if they are not in there they are lost. Sorry!

**Comment by re3lex** [comment]
Sad...

I think it is good idea to warn user about such breaking behavior next time.

**Comment by IamIpanda** [comment]
me too. Could you please hint that in release notes?
The config path window disappears too soon.

**Comment by felixse** [comment]
This was not expected. Profiles where serialized fine in my tests. I will add a note to the release.
Did you only lose profiles or also settings?

**Comment by re3lex** [comment]
Anything. Update behaves like  clean installation.

**Comment by MostHated** [comment]
If I have not yet updated, how can I back up the settings first?

**Comment by felixse** [comment]
You could try backing up http://localappdata/Packages/53621FSApps.FluentTerminal_87x1pks76srcp/Settings/Settings.dat and then restoring it after the update.
but I think taking some screenshots is the safest way

**Comment by monkeyking** [comment]
the config.json collect nothing..
All setting were lost..
But fortunately i remember them

**Comment by creckord** [comment]
My update from v0.6.1.0 to v0.7.1.0 via Chocolatey also lost all settings - roughly a half day's work :'-( Well, teaches me to be more diligent with my backups... Anyway, the reason why I'm commenting here:

1) I'm wondering if this is actually fixed in newer versions, or if folks updating from 0.6.x to e.g. 0.7.1 might run into the same...

2) I think the notice from the release page should be repeated on the Chocolatey page, and maybe even in the install script - I don't think many folks will read the GitHub page before a `cup all`

3) I might have a bit of a lead and a suggestion or two:

My problem with the choco update actually started with an error: 
```
ERROR: The term 'flute' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
``´
That should probably have given me pause. But with some digging, I found that the issue was that indeed flute.exe was nowhere in my PATH or in that used by the update script. So I located it and put it in the PATH. And I think this might be a possible source of the problem: The one I put in the PATH wasn't the one in `%localappdata%/Microsoft/WindowsApps/53621FSApps.FluentTerminal_87x1pks76srcp` but one directly in `%localappdata%/Microsoft/WindowsApps`. And that one happened to just silently and without an error indication or exit code do nothing when called with `flute settings --export`. I later reverted the update and checked again, and always that one didn't work, while the other did. With 0.7, both seem to do the job.

So maybe people running into this issue also had their PATH mixed up somehow?

As for the suggestions:
1. Make the updater fail if it doesn't successfully export a non-empty config.
2. Back up the exported config in the update script somewhere so that it will exist after the update in case something goes wrong
(3. Already mentioned: Maybe put the warning on the Choco page, and/or into the Choco script)
4. A bit unrelated, but I would have actually made a backup of my setup once I was happy with it originally, but didn't find the option - would be nice to have something in the Settings UI to export it.

**Comment by mycanaletto** [comment]
Same problem with 0.7.7.0

Luckily I had a backup, but the directory changed and I restored the whole directory: 

`C:\Users\Lionel\AppData\Local\Packages\53621FSApps.FluentTerminal_ce3nnjsf22cn4`
