### ISSUE TITLE
Tab titles do not use profile name

### ISSUE THREAD

**Issue by TKlie** [felixse/FluentTerminal#687]
The release notes of the 0.7.0.0 release indicate, that `The profile name is now used as the default tab title`.

However, I only see the profile name as the tab title for a split second upon opening a new tab. Immediately afterwards it it overwritten by the `Shell executable location` again.

**Comment by felixse** [comment]
That's because the shell is updating it's title. You should be able to configure this in your shell profile (like bashrc or powershell profile).

**Comment by TKlie** [comment]
I see, is this a default behavior I need to disable for every shell?
Because I checked all profile locations according to the MS docs and there are no custom profile configurations for PowerShell on my machine (and this also happens for CMD and ZSH (WSL) for which also do not have custom titles configured).

**Comment by felixse** [comment]
just noticed there is a problem with ConPty, I will try to fix this with 0.7.1.0
