### ISSUE TITLE
Lost features in 0.7

### ISSUE THREAD

**Issue by IamIpanda** [felixse/FluentTerminal#688]
I DO need following functions:

- New tab for SSH profile
- Configurable New tab

I have 20+ profiles and not possible to set keybindings for them 1-by-1.

And now, a tab with background color in not active status won't show its color.

Are they removed from 0.7, or will be added in future?
Also, I ran into some trouble when rolling back to 0.6.

**Comment by vasiby** [comment]
+1, please revert ctrl+shift+t as it behaved before

**Comment by felixse** [comment]
Tab color is clearly a regression,  I will fix this with 0.7.1.0 soon.
What are you missing in the new dialog? The new is basically the same with more options

**Comment by vasiby** [comment]
In the previous version there was a dialog where I could select what profile will be opened in the new tab, in 0.7 is automatically opens a new default profile profile without letting me choose

**Comment by felixse** [comment]
The new dialog (quick launch, ctrl + shift + t by default) can do the same. just type the first letter or anything from your profile's name and it will open a dropdown with matching profiles

**Comment by dyakovk** [comment]
Feature `Open Terminal in this folder` in Context Menu also disappeared in this version

**Comment by IamIpanda** [comment]
> The new dialog (quick launch, ctrl + shift + t by default) can do the same. just type the first letter or anything from your profile's name and it will open a dropdown with matching profiles

Thank you. I will close this issue after missing tab color fixed.
