### ISSUE TITLE
Add loopack websocket back as option for performance (at compile-time)

### ISSUE THREAD

**Issue by Riebart** [felixse/FluentTerminal#69]
So, I noticed it in use almost immediately, and testing confirms: The AppServiceConnection removes the need for the loopback exemption, but it is definitely less performant.

It's a wee bit janky in larger terminals with full-screen ncurses interfaces (think `htop` on a busy server in a large terminal on a high DPI screen), and spammy output (output from `apt` is verbose) is definitely slower (about a third to half the 'speed', so only about 1k lines/second, as opposed to 2-3k.).

I mean, in most use cases this isn't an issue, and having it in the Store is worth more, but there's some use cases where that's something you may want.

Definitely low priority, and might be easy to add in, given that the desired logic already exists in the history. 😸

**Comment by felixse** [comment]
Well, lets see how the store certification ends. Right now its rejected, and I'm trying to get some more information. If we won't make it in the store I would return to the websocket communication and aim for a good installer solution (includes install cert, enable loopback) instead

**Comment by felixse** [comment]
I don't think this will make a comeback, especially because of the VPN issues.
