### ISSUE TITLE
The letter 'r' display problem.

### ISSUE THREAD

**Issue by BaRRaKudaRain** [felixse/FluentTerminal#695]
![Untitled](https://user-images.githubusercontent.com/29839832/78370452-8326b280-757b-11ea-913f-30675ec022eb.png)

How to fix this issue?

**Comment by felixse** [comment]
looks like an issue with your font. Which are you using?

**Comment by BaRRaKudaRain** [comment]
Default one.

**Comment by felixse** [comment]
That's strange. Did you install or configured anything that might have an impact on font rendering?

**Comment by BaRRaKudaRain** [comment]
Hmmmm... Fonts packages in WSL?

**Comment by felixse** [comment]
No idea what's going  here, but I don't think this is something Fluent Terminal is causing. Maybe configuring another font helps 😕
