### ISSUE TITLE
Powershell Core UWP

### ISSUE THREAD

**Issue by KoleckOLP** [felixse/FluentTerminal#696]
Is there a way to use powershell core in this terminal? I have installed the UWP version of Powershell 6 and I'm able to use it in Windows Terminal. But I don't know how to add it to Fluent Terminal
Here is it launch from the start menu:
![pwsh_SvmFJ8pgAV](https://user-images.githubusercontent.com/22729896/78453174-4c8e8c00-7690-11ea-8413-bff388b7111b.png)
Here is it running in wt.exe Windows Terminal (Preview):
![WindowsTerminal_97xLNga5Ur](https://user-images.githubusercontent.com/22729896/78453176-4f897c80-7690-11ea-9579-8e8bece3e1e1.png)
Here are the settings for it in Windows Terminal I don't think it says much:
![Code_tHY5v7DMkH](https://user-images.githubusercontent.com/22729896/78453187-5ca66b80-7690-11ea-86db-01e434dce00d.png)

**Comment by felixse** [comment]
Sure, just create a new profile with this path: `C:\Program Files\PowerShell\7\pwsh.exe`

**Comment by KoleckOLP** [comment]
Thanks, I could have figured that out on my own, sorry. 
``C:\Program Files\PowerShell\6\pwsh.exe``
