### ISSUE TITLE
text is pasted into terminal when typing "@"

### ISSUE THREAD

**Issue by zsbolyoczki** [felixse/FluentTerminal#699]
Hungarian QWERTY 102 keyboard layout, "@" is mapped by default to "ALTGR + V" but "ALTGR + V" pastes the content of the clipboard instead of typing a "@" character.

Fluent terminal version: 0.7.0.0

**Comment by zsbolyoczki** [comment]
I think I have found the reason of this behaviour.

In "Keybindings / Paste" is set to "CTRL SHIFT V" which is somehow translated to "ALTGR - V" (which I need for typing "@").

I don't know if this is a bug or a feature.

Also "New quick launch window" has to be deleted because "CTRL ALT N" was translated to "ALTGR - N" wihich stands for "}" sign on Hungarian 102 layout.

**Comment by felixse** [comment]
I think "paste without newlines" (ctrl + alt + v) is the problem here. I will see if I can improve the key detection for altgr, but in the meanwhile you can remove or edit this particular keybinding

**Comment by zsbolyoczki** [comment]
Thank you (I have removed the unused keybindings to mitigate side effects).
