### ISSUE TITLE
The File Explorer Integration doesn't work

### ISSUE THREAD

**Issue by manuelelucchi** [felixse/FluentTerminal#7]
I don't know if i forgot something but when i open Fluent Terminal in a folder/desktop with the contextual menu it will remain in the splashscreen forever
Regards,
Manuele

**Comment by felixse** [comment]
Hi,
are you using the released version? The explorer integration only works with the version on master right now.

**Comment by felixse** [comment]
Please check if this is still occuring to you with the 0.1.5.0 release

**Comment by manuelelucchi** [comment]
Now it works, perfect! Also the customization is awesome!

**Comment by felixse** [comment]
Thank you 👍
