### ISSUE TITLE
not returning to prompt

### ISSUE THREAD

**Issue by zsbolyoczki** [felixse/FluentTerminal#700]
Quite frequently FT doesn't return (to) prompt.
i.e:
```
$ cat /etc/*relea*
line1
line2
line3
```
FT displays the the whole file content and I have to press Enter to get the prompt back. It's not a server issue because other terminals don't do this.

**Comment by zsbolyoczki** [comment]
It seems tha this happens is the output is more than 1 line, like ```git commit -m "foo"```. But not happens everytime.

**Comment by felixse** [comment]
Please check if the profile has "Use smart buffer" enabled and test if it works better without it. There are some situations where this might cause screen corruptions.

**Comment by zsbolyoczki** [comment]
I have just tested it and didn't help.
I have also enabled/disabled ConPty but it also didn't help.

**Comment by kennymckormick** [comment]
I just met the same problem. For me, turn off  "Use smart buffer"  solve the problem.

**Comment by mearleycf** [comment]
Agreed, I was having this issue as well, and turning off Smart Buffer for the WSL profile worked.
