### ISSUE TITLE
How to connect using SSH Profile?

### ISSUE THREAD

**Issue by re3lex** [felixse/FluentTerminal#702]
Before 0.7.0.0 there was shortcut Ctrl+Shift+U to open new SSH tab using saved SSH profile.
Shortcut is not working after update and I even cannot find any way to start SSH connection using SSH profile.

**Comment by felixse** [comment]
All profiles can new be started form the quick launch dialog (ctrl+alt+t by default). Just type some part of the profiles name and select it from the autocomplete

**Comment by re3lex** [comment]
oh, missed that. Thanks!
