### ISSUE TITLE
ssh keep alive support?

### ISSUE THREAD

**Issue by Naolador** [felixse/FluentTerminal#703]
My ssh session drops after several minutes of idle. Many ssh clients support keep alive function. How can I enable this function in Fluent terminal?

**Comment by skipmeister123** [comment]
This is really something you should be setting in your `.ssh/config`

```
TCPKeepAlive yes
ServerAliveInterval 60
```

**Comment by Naolador** [comment]
> This is really something you should be setting in your `.ssh/config`
> 
> ```
> TCPKeepAlive yes
> ServerAliveInterval 60
> ```

I know that will work. However, it's nearly impossible to alter these settings across all servers. ssh clients such as Putty supports this function by enabling the keepalive options.

**Comment by peske** [comment]
It can be accomplished in two ways:

1. In `.ssh/config`, as sugested by @skipmeister123;
2. By specifying the configuration options in command line parameters, by using `-o`:
```
ssh -o TCPKeepAlive=yes -o ServerAliveInterval=60 $HOST
```
In `.ssh/config` you can set this either for some or for all connections (servers). In FT you can use `-o` on per connection basis. To avoid typing these options again and again you can create profile.

Although it is possible to put such option in FT UI (which would result in adding the appropriate `-o` options to the command), I don't think that it would be a good approach. FT is terminal app intended for many different tools other than `ssh`, and adding all the options for all the tools would make it way too complex.

@felixse , I believe that this one can be closed.
