### ISSUE TITLE
Part of command output disappear

### ISSUE THREAD

**Issue by JingBh** [felixse/FluentTerminal#704]
*Forgive my bad English...*

My Windows language is Simplified Chinese (简体中文), when I run some command (for example, `ipconfig`) in **CMD** in Fluent Terminal, part of the command's output will disappear.

![截图](https://user-images.githubusercontent.com/26338708/78620699-4b897480-78b3-11ea-9a40-adf17dce885f.png)
See this picture, the left side is Fluent Terminal, the right side is native `cmd.exe`.

The problem won't appear in older version of Fluent Terminal (like 6.0), also won't appert in **Powershell**.

**Comment by JingBh** [comment]
Update: I found disabling **smart buffer** fixes the problem.

**Comment by felixse** [comment]
Smart buffer is doing some dynamic buffer sizing and timing adjustments to improve the performance, but there are some cases where this causes errors. I would suggest turning it off for now while we collect the reports and decide on how to continue with smart buffer
