### ISSUE TITLE
Wrong/Confusing Keybindings?

### ISSUE THREAD

**Issue by flashmaster77** [felixse/FluentTerminal#705]
Hi, i just started using Fluent Terminal as replacement for Powershell and i quite like it. But what bothers me is that i cant type the '@' character, which is on 'Q' on the german qwertz layout, because ALTGR + Q opens new Quicklaunch Tab. Is there a way to remove or change that binding?

**Comment by felixse** [comment]
duplicate of #699, will be fixed with the next update

**Comment by felixse** [comment]
Also you can edit keybindings in the settings meanwhile
