### ISSUE TITLE
Output is confusing

### ISSUE THREAD

**Issue by asterwyx** [felixse/FluentTerminal#706]
When I execute a command with long output, the output is sometimes incomplete and the cursor indicator is mixed with the output.This happens in both windows powershell and wsl usually when the curosr indicator reaches the bottom of the terminal.
![46Y L$XW6KY5YYB)M89WWLK](https://user-images.githubusercontent.com/46272753/78733228-70dfb680-7977-11ea-93bf-171cbff936b2.png)
![ZQ4I2159S~POKML7 1R2QZD](https://user-images.githubusercontent.com/46272753/78733260-848b1d00-7977-11ea-98f4-b5008b40f8f1.png)

**Comment by felixse** [comment]
Please check if the profile has "Use smart buffer" enabled and test if it works better without it. There are some situations where this might cause screen corruptions.

**Comment by asterwyx** [comment]
@felixse Thank you! I've reinstalled it and had "Use smart buffer" disabled in my profiles. Now it works.
