### ISSUE TITLE
special characters of the themes disappear

### ISSUE THREAD

**Issue by cristianoso19** [felixse/FluentTerminal#708]
![2020-04-08 11_23_12-~_node_modules ‎- Fluent Terminal](https://user-images.githubusercontent.com/6619513/78808651-63342c00-798b-11ea-979b-f7cc0dbb475e.png)
oh my zsh theme, on ssh conection, pure theme for ohmyzsh, font all for powerline

**Comment by felixse** [comment]
Can you post some reference how it's supposed to look?

**Comment by cristianoso19** [comment]
![image](https://user-images.githubusercontent.com/6619513/79048295-c6b79700-7be1-11ea-9c01-12514ce450e6.png)
Shure, this is how this show in past version view the spaces and ">" character

**Comment by felixse** [comment]
ok, I see. Can you try disabling smart buffer in this profile?

**Comment by cristianoso19** [comment]
Ok, is that!!!, what means smart buffer?
