### ISSUE TITLE
There's not an Icon on the taskbar

### ISSUE THREAD

**Issue by asterwyx** [felixse/FluentTerminal#712]
![Annotation 2020-04-10 174700](https://user-images.githubusercontent.com/46272753/78982003-bce75280-7b53-11ea-924f-354a2a639d53.png)

**Comment by felixse** [comment]
There is also no background, did you install some tool for that? Whatever you did to your taskbar is probably causing this

**Comment by asterwyx** [comment]
Yes,I've installed TrancluentTB, a simple tool just for taskbar transparency.Just now I closed it but find no change.However, I've recovered it.The real reason is that I've created a shortcut in the "Management Tools" directory in order to set it a global keyboard shortcut.I removed this shortcut and it works fine now. But I don't know the deeper reason.

**Comment by felixse** [comment]
Ok, then we can close this. If you need a global shortcut you can also enable autostart for the System Tray and use the toggle window keybinding
