### ISSUE TITLE
Characters are showing at once place in the terminal

### ISSUE THREAD

**Issue by arunjoseph** [felixse/FluentTerminal#717]
Hello,
I have just recently updated to 0.0.7 and ever since update I am not able to type any characters it is being placed at one place itself in the terminal. I am using WSL and using the iterm profile.
For your reference, I have attached the screenshot
![FluentError](https://user-images.githubusercontent.com/1634000/79194889-fd441a80-7e4a-11ea-8397-2fc8ce3c7e03.jpg)

**Comment by felixse** [comment]
Can you try disabling Smart buffer for this profile?

**Comment by arunjoseph** [comment]
It is still the same

**Comment by peske** [comment]
@arunjoseph This one is quite strange. I cannot reproduce. Can you confirm that it still happens for you? Are you able to try on another PC?
