### ISSUE TITLE
Icon issue in "Search"

### ISSUE THREAD

**Issue by Loreno10** [felixse/FluentTerminal#721]
I am not sure if this is an error. When opening "Search" panel I see:
![image](https://user-images.githubusercontent.com/10273406/79219659-f4efdd80-7e52-11ea-9d11-bf2d898eed32.png)

I believe there should be some icon that is not displaying correctly?

**Comment by felixse** [comment]
There should be a search icon indeed. What version of Windows 10 are you using?

**Comment by Loreno10** [comment]
It's Windows 10 1809. I'm stuck on it on work laptop :\
