### ISSUE TITLE
Prompt corruption

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#723]
I don't even know where to begin with this hot mess.

![image](https://user-images.githubusercontent.com/1911919/79279148-62176900-7e7b-11ea-9595-e9804abe0b95.png)

**Comment by skipmeister123** [comment]
Ignore the error. :P

![image](https://user-images.githubusercontent.com/1911919/79279192-7491a280-7e7b-11ea-83a7-9f7f8148d6f9.png)

**Comment by skipmeister123** [comment]
Disabling ConPTY and smart buffer fixed the issue.  I don't know which was causing it, but I'm not going to mess with success.

**Comment by felixse** [comment]
The combination of ConPty and smart buffer. I think I will remove smart buffer with the next release, it's causing too much trouble
