### ISSUE TITLE
Dropped keyboard input

### ISSUE THREAD

**Issue by timadye** [felixse/FluentTerminal#724]
FluentTerminal very occasionally drops a character I type as keyboard input, leading to garbled commands. I did not see this behaviour with other programs or terminal emulators I've relied upon for many years (eg. MinTTY and mrxvt+X11).
Unfortunately I haven't noticed many patterns to identify the problem, but have observed the following:
   - mostly a single character is dropped, mostly at the start of a line.
   - often occurs soon after opening or switching to the window or tab. Occasionally something goes wrong (maybe the CPU is busy?) and lots of characters get dropped all the time.
   - I use Cygwin bash, WSL bash, and Cygwin OpenSSH remote sessions. I've seen this problem with them all.
   - if the first key is a special key (eg. Up arrow), then I get something garbled (eg. "[A" instead of Up"). I guess this means just the initial ESC (of ESC+[A, the code for Up) is dropped. I hope this is a clue 😄 
   - I am using FluentTerminal 0.7.0.0 on W10 1803, but also saw the issue with FluentTerminal 0.6.1.0.
   - I tried various settings, notably with and without ConPty, all to no avail. (Incidentally, I don't know when it's useful to use ConPty.)

Has anyone else seen this, or is it just me? Do you have any ideas for how I can help track it down - or even better a fix?

Thanks, Tim.

**Comment by vasiby** [comment]
I use Cygwin and Conpty, but it's important to turn off smartbuffer in the terminal profile settings

**Comment by timadye** [comment]
Thanks for the hint. I didn't try ConPty without Smartbuffer before, so I'll see if it's better like that.
I'll report back here...

**Comment by timadye** [comment]
... well that was quick. I still get dropped keyboard characters with both Cygwin and WSL.
Looking at the comments about Smart Buffer, it looks like that's applied to the output (eg. cat large file). My present issue is with keyboard input.
Thank you anyway for the advice: I'll keep Smartbuffer disabled to avoid other issues.

**Comment by timadye** [comment]
Hi @felixse ,
Thanks for the new release.
Unfortunately I still get occasional dropped characters on input with the new version. They are frequent enough to make the terminal unusable for intensive work, sometimes every command, but sometimes much more rarely.
I guess there's still a problem, probably with Windows-10 1803.
Can you reopen the issue, or should I submit a new one?
Thanks, Tim.
