### ISSUE TITLE
Silent execute flute.exe settings --export

### ISSUE THREAD

**Issue by gremo** [felixse/FluentTerminal#726]
Would be possible to silent execute the command for export/backup settings, without showing the UI?

I'm running this command before my automatic backup is persisted. Having to manually close the fluent windows is a pain... thanks.

**Comment by felixse** [comment]
Next update has a revamped settings import and export with auto closing windows. Should be released in a few days

**Comment by gremo** [comment]
Hi @felixse , can't wait for the new release. Thanks! Also I hope that the new version will fix the import bug (import doesn't work at all - at least for me) and the warning when using the SSH key (something like key not found... but it works anyway).

**Comment by gremo** [comment]
I found some Italian strings not translated... do you accept pull request? Maybe I'll be able to translate them, even if i'm mainly a web developer :)

**Comment by felixse** [comment]
Import and ssh file should both be fixed with the update. 

For translations please signup on [POEditor](https://poeditor.com/join/project/TfKNIt826z). That way it's easier to integrate
