### ISSUE TITLE
Esc key is ignored

### ISSUE THREAD

**Issue by zsbolyoczki** [felixse/FluentTerminal#727]
In vi/vim I have to press ESC several times to take effect (switch from edit mode to command mode). It seems that Esc is just not captured when it is pressed.

I have tested with other applications, with another keyboard and with an online keyboard tester tool as well.
In every test cases ESC was immediately captured.

Version 0.7.0.0

**Comment by lszymkowiak** [comment]
I have the same issue. After updating to version 0.7.3.0 ESC key stopped working.

**Comment by trueuto** [comment]
Open Fluent Termnal's settings, go to the "Keybindings" section, locate "orphaned" entry with Escape hot-key assigned to it and delete it.

**Comment by lszymkowiak** [comment]
Thanks, that helped :)

**Comment by felixse** [comment]
This should be fixed with 0.7.4.0
