### ISSUE TITLE
Visual glitch after cd

### ISSUE THREAD

**Issue by mayankvallah** [felixse/FluentTerminal#731]
When I cd to a directory after using ls,
![image](https://user-images.githubusercontent.com/62397838/79866119-e6c53280-83f9-11ea-9898-f10b8882681f.png)
This glitch appears. The username gets overwritten with keyboard input instead of being written the normal way.
Is there a way to fix this? I have tried changing font size, window size, themes but no help.
I'm on Windows 10 1909

**Comment by skipmeister123** [comment]
Try disabling smart buffer.

**Comment by mayankvallah** [comment]
> Try disabling smart buffer.

Thanks for such a prompt reply! I tried some commands and it seems to have fixed the problem. Disabling smart buffer is the solution :D

**Comment by skipmeister123** [comment]
There have been a lot of issues with it. I think Felix plans to remove it 
next release.

**Comment by getsueineko** [comment]
skipmeister123 thanks a lot! I had the same problem and your solution helped me out *THUMBS UP*

**Comment by peske** [comment]
Blame me. I'm the guy who created "smart buffer". I still don't understand why such things are happening, thus I cannot fix. If such things are happening often, we should probably remove it completely, despite the improvement of performances.
