### ISSUE TITLE
Console IO issues with Powershell and GPG4win (likely upstream issue)

### ISSUE THREAD

**Issue by Riebart** [felixse/FluentTerminal#74]
This is likely a winpty thing, and affects more than just gpg, but I'll note it here in case other are experiencing it:

When using Powershell and the `gpg2` binary from GPG4Win, there's issues with the gpg interactive stuff having issues with WriteConsole:

```
<snip…>
gpg/card>

Application ID ...: D1362304385780577533578519686858
Version ..........: 2.0
Manufacturer .....: Yubico
Serial number ....: 81862828
Name of cardholder: [not set]
Language prefs ...: [not set]
Sex ..............: [not set]
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: forced
Key attributes ...: 2048R 2048R 2048R
Max. PIN lengths .: 127 127 127
PIN retry counter : 3 3 3
Signature counter : 0
Signature key ....: [none]
Encryption key....: [none]gpg: Fatal: WriteConsole failed: 7 != 0
<snip…>
```

I'll note that we're using the latest release (custom compiled to get x86?) for winpty, which hopefully we can ditch come 1809's release, but if we can't then including winpty as a git submodule and building from `master` as part of first build is probably not the worst idea.

**Comment by felixse** [comment]
So it does work when using the conhost powershell? I don't know how winpty might cause this, since it's just translating a hidden conhost into named pipes, but who knows 🤷‍♂️

**Comment by felixse** [comment]
hmm, yeah strange 😅 

Let's just hope this will be solved by ConPty
