### ISSUE TITLE
Text not being output properly when reaching the end of the window

### ISSUE THREAD

**Issue by Ayrler** [felixse/FluentTerminal#750]
Text is not displayed properly whenever it reaches the end of the terminal window. This happens quite often but not always.    
The behavior is not tied to a specific terminal, I have tried both Powershell and CMD with out-of-the-box configuration and also cmder.

Here are screenshots of how it looks like:
1. Many lines are missing
![image](https://user-images.githubusercontent.com/21156699/81634344-1373d500-940f-11ea-8796-5bb1416a6448.png)
2. Prompt not being displayed in a new line and many lines are missing
![image](https://user-images.githubusercontent.com/21156699/81634439-52a22600-940f-11ea-8dd8-974531846e7a.png)

And here is how it should normally look like:
![image](https://user-images.githubusercontent.com/21156699/81634291-f4754300-940e-11ea-870c-8119cc06aed5.png)

The only way I have found so far to avoid this issue is to clear the terminal and start again at the top.

**Comment by skipmeister123** [comment]
Try disabling smart buffer.

**Comment by Ayrler** [comment]
@skipmeister123 disabling smart buffer seems to work so far. Thank you!
