### ISSUE TITLE
Remove Smart Buffer option

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#752]
We've seen nothing but problems with Smart Buffer.  It causes confusion, induces headaches, and doesn't work as well as it should. A list of (some) of the bugs filed because of Smart Buffer are as follows:

- #750
- #731 
- #724 
- #723 
- #717 
- #708 
- #706 
- #704 
- #700 

I propose that Smart Buffer is removed until it can be fixed by @peske

**Comment by felixse** [comment]
It's already removed on master, but I cannot release an update right now due to some build issues.  Hope those can be resolved soon

**Comment by peske** [comment]
What to say... I still cannot understand why such issues happen when bytes are sent in chunks, but not when the same bytes are sent one-by-one. And without understanding I cannot fix it. I've tried... But for now, I agree - it should be removed if it causes these issues.

**Comment by peske** [comment]
Also, according to @jerch, such buffering feature will be implemented upstream, in xterm.js, so we probably won't need it in FT. 
Source: https://github.com/jumptrading/FluentTerminal/issues/258#issuecomment-583904756

**Comment by jerch** [comment]
> What to say... I still cannot understand why such issues happen when bytes are sent in chunks, but not when the same bytes are sent one-by-one. And without understanding I cannot fix it. I've tried... But for now, I agree - it should be removed if it causes these issues.

Yes indeed, this should not be an issue, a PTY (and ConPty too) is just a byte stream by definition, a consumer should always come to the same final state, no matter how bytes were chunked up in between. So my guess would be, that FluentTerminal has some other state changes in place, that might mix up with band data state. In conjunction with xterm.js there are several places, were this can happen accidentally:
- onKey hooks with early writeback to the terminal itself --> breaks in-band state association
- any sync function of the xterm.js API (e.g. `term.reset`, forced buffer switches on terminal object, resize etc.).

Thats the reason why xterm.js should be "orchestrated" mainly `term.onData` and `term.write` calls, and direct API calls should be avoided. Ofc they cannot be avoided always...

Have you checked, that your prebuffered version really gives the same data to xterm.js in the end? If so, you most likely see side effects from other direct xterm.js API calls hidden in your C# --> JS binding to xterm.js.

> Also, according to @jerch, such buffering feature will be implemented upstream, in xterm.js, so we probably won't need it in FT.

We have implemented this as I described in that comment for our development server part. This cannot be part of xterm.js itself, as it is a frontend component only. You as embedder always have to do similar measures yourself, xterm.js cannot control your server part.

**Comment by jerch** [comment]
Another side note on this - imho ConPty itself is badly broken and tries to hard to mess around with WSL pty and old WinAPI console integration. Also see my comment here: https://github.com/alacritty/alacritty/issues/3707#issuecomment-627312335
