### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by umarmughal** [felixse/FluentTerminal#753]
I installed the app but it keeps crashing on startup, i never saw terminal .. Windows 10 64bit, any advise?

**Comment by felixse** [comment]
Do you see anything in Event Viewer? (look in Windows Logs -> Applications)

**Comment by umarmughal** [comment]
Fault bucket 1213392253880722249, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: 53621FSApps.FluentTerminal_0.7.0.0_x64__87x1pks76srcp
P2: praid:App
P3: 1.0.0.0
P4: 5e8083d0
P5: ucrtbase.dll
P6: 10.0.18362.815
P7: 32a6df9a
P8: c0000005
P9: 0000000000026e40
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE994.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF5F8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF657.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF665.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF695.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_53621FSApps.Flue_e018a1af2783e4beef763467c312d94bc61549b_804ecaa0_c7718afa-0e50-4500-b413-ef5f6499e544

Analysis symbol: 
Rechecking for solution: 0
Report Id: 26e8b748-02ee-4621-9594-808a6534e652
Report Status: 268435456
Hashed bucket: aad75332b39000dbe0d6d5d379c56349
Cab Guid: 0

**Comment by umarmughal** [comment]
I see this error in windows logs > applications .. anything else you need let me know, thanks

```
Fault bucket 1213392253880722249, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: 53621FSApps.FluentTerminal_0.7.0.0_x64__87x1pks76srcp
P2: praid:App
P3: 1.0.0.0
P4: 5e8083d0
P5: ucrtbase.dll
P6: 10.0.18362.815
P7: 32a6df9a
P8: c0000005
P9: 0000000000026e40
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE994.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF5F8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF657.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF665.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF695.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_53621FSApps.Flue_e018a1af2783e4beef763467c312d94bc61549b_804ecaa0_c7718afa-0e50-4500-b413-ef5f6499e544

Analysis symbol: 
Rechecking for solution: 0
Report Id: 26e8b748-02ee-4621-9594-808a6534e652
Report Status: 268435456
Hashed bucket: aad75332b39000dbe0d6d5d379c56349
Cab Guid: 0
```

**Comment by peske** [comment]
@umarmughal , what's the actual Windows version? (Settings -> System -> About) For example, in my case it's Windows 10 Enterprise, version **1909**.

**Comment by umarmughal** [comment]
Windows 10 Pro, Version 1909

**Comment by Jestar342** [comment]
I too see FT crash on load, I get as far as the blank window loads, then app crashes before I see any kind of content to it, and I have the following error in my system event log:

`The server 53621FSApps.FluentTerminal_0.7.0.0_x64__zzw7cgfsy6dd6!App did not register with DCOM within the required timeout.`

**Comment by peske** [comment]
@Jestar342 , @umarmughal , weird... I cannot reproduce on any machine, and logs you've provided aren't too helpful (at least not for me). Few more questions for you two guys:

1. Have you maybe played with enabling/disabling some Windows stuff? For example some people (including me) use some third-party tools to disable Cortana, telemetry, and some other useless Windows shit.
2. Can you please download [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) (by Microsoft), and try to get some crash logs there? It's very easy - no install, simply run exe as admin, select all available logs, and run FT.

Thanks!

**Comment by peske** [comment]
Actually try the following first:
Go to Settings->Update & Security->Troubleshoot, and start "Windows Store Apps" (probably the last at the bottom) troubleshooter, and see if it'll show something relevant.

**Comment by umarmughal** [comment]
Tried everything you said but no luck and nothing found .. installed app again and its still crashing on start, good is i can open app settings ... that's it

**Comment by felixse** [comment]
Can you [activate debug logging](https://github.com/felixse/FluentTerminal/wiki/Logging#activate-debug-logging) and post some logs?
