### ISSUE TITLE
Missing output - Inconsistent behavior 

### ISSUE THREAD

**Issue by xstrex** [felixse/FluentTerminal#755]
Running latest version: 0.7.0.0
Reset all terminal options to defaults.

I can't say I've ever seen this before, but the same command when run multiple times is simply missing information. Not sure how else to explain this. It's causing serious issues and I'm forced to use other term emulators because I'm missing critical information to do my job; making the current version unreliable to say the least. 

A picture speaks a 1,000 words..
![foobar](https://user-images.githubusercontent.com/12849470/82078347-3962d900-969e-11ea-9c36-17f07f5a510f.png)

**Comment by skipmeister123** [comment]
This is likely another case of Smart Buffer causing problems. Go ahead and 
turn it off.

**Comment by xstrex** [comment]
I think that helped, but didn't fix the problem:
![foobar2](https://user-images.githubusercontent.com/12849470/82083643-4c2ddb80-96a7-11ea-8945-4e6a35426c24.png)

**Comment by xstrex** [comment]
Correction, that did in fact fix the issue. Thanks for the quick response.
