### ISSUE TITLE
Password exposure possible via autocorrect suggestions while in use

### ISSUE THREAD

**Issue by ShadowEO** [felixse/FluentTerminal#76]
While using FluentTerminal, AutoCorrect will attempt to process the input and will display suggestions (until ESC is pressed) and if the user's password has been entered recently, it will show the password in the suggestions. The suggestions do not disappear when Enter has been pressed. Obviously this requires people to be looking over the user's shoulder or using a remote access solution to see the password, but I still don't think it should be appearing as autocorrect suggestions.

Is there a way to forcibly disable autocorrect suggestions for a text field under UWP? This might be a good idea.

(Other than that, this is a wonderful application! I've been looking for a UWP version of CMDer and this is the closest by far!! Thank you for the lovely work you've done on this!)

**Comment by felixse** [comment]
Didn't happen to me yet, I will play around with my settings this weekend to reproduce that.

**Comment by ShadowEO** [comment]
Some additional settings that I had turned on in Windows that produced the behavior:

Devices -> Typing -> Hardware Keyboard -> Show text suggestions as I type

**Comment by jonaskuske** [comment]
Also, the word suggestions appear at the far left edge of the screen rather than above the cursor.
Agree that forcefully disabling autocorrect within FluentTerminal would be a good idea, it is of little use there imo.

**Comment by felixse** [comment]
Can no longer reproduce this in the current version.
