### ISSUE TITLE
Duplicate tab should inherit the color

### ISSUE THREAD

**Issue by CaselIT** [felixse/FluentTerminal#761]
Currently if I have an open tab with a color and I duplicate it, the new tab starts without any color.

My workflow usually is to use colors to indicate which tabs are open in a particular folder, so I may have a group of tabs open on folder `/foo` that are blue and another group that are on folder `/bar` that are green. This would be very useful when opening a new tab.

Not sure if this should be default or just a config options

Thanks for this terminal, it's really great!

**Comment by maxhora** [comment]
that sounds like a regression

**Comment by CaselIT** [comment]
From memory a duplicate tab never kept the color. But I may be mistaken.
I'm using 0.7 now btw.
