### ISSUE TITLE
Context menu item wont get removed after wrong install

### ISSUE THREAD

**Issue by mutageneral** [felixse/FluentTerminal#766]
I tried to install Fluent Terminal with chocolatey but it gave me an error. Apparently, it doesn't work on the LTS 2016 version of windows but chocolatey never told me that.

Because it failed mid install, chocolatey does nothing when I try to remove it. 

**Now here is the problem**, I now got this context menu 
![image](https://user-images.githubusercontent.com/62779748/82744413-15f6f880-9d46-11ea-952b-254ca5ce3023.png)
And when I click on it:
![image](https://user-images.githubusercontent.com/62779748/82744415-2909c880-9d46-11ea-9270-46603d2649dd.png)

Now I am stuck with this and cant remove it :/
What if someone with chocolatey and LTS 2016 would have searched for "terminal" in choco and installed it to try it out out of curiosity without ever visiting the GitHub and end up stuck like this? Like, how could they have ever known? This should not happen. It should have a check right at the beginning and then stop the install if you are on the wrong version of windows...

**Comment by felixse** [comment]
Sorry to hear, maybe there is a way to add a minimum version to the chocolatey package.

Download and run this to uninstall the context menu extension: https://github.com/felixse/FluentTerminal/blob/master/Explorer%20Context%20Menu%20Integration/Uninstall.bat
