### ISSUE TITLE
.NET Version Error

### ISSUE THREAD

**Issue by scratchfive** [felixse/FluentTerminal#77]
Upon running, I receive an error stating that .NET version 4.7.1 is required. Version 4.7.2 is installed and in use and blocks any attempt and installing older versions. 
![fterror](https://user-images.githubusercontent.com/4142390/45260556-ed7b6f00-b3a7-11e8-9a75-c97ca32989ec.png)

EDIT: Perhaps [this](https://stackoverflow.com/questions/44237105/this-application-requires-one-of-the-following-versions-of-net-framework) thread may offer some insight

**Comment by scratchfive** [comment]
Yeah it's a bit odd. Re-enabling .NET doesn't change anything. This is the 1809 Insider's build by the way.

**Comment by felixse** [comment]
That's great, thanks for looking into this 😃
