### ISSUE TITLE
The install script bundled with version 0.7.1.0 does not work

### ISSUE THREAD

**Issue by TPXP** [felixse/FluentTerminal#770]
Hello!

When running the `Install.ps1` script, it crashes with the following output:
```
Found bundle: C:\ProgramData\chocolatey\lib\fluent-terminal\install\FluentTerminal.Package_0.7.1.0_x64.appxbundle

Before installing this app, you need to do the following:
        - Acquire a developer license
Error: Could not acquire a developer license. For more information, see http://go.microsoft.com/fwlink/?LinkID=252740.
```

Running with `-Force` does not help:
```
Found bundle: C:\ProgramData\chocolatey\lib\fluent-terminal\install\FluentTerminal.Package_0.7.1.0_x64.appxbundle

Before installing this app, you need to do the following:
        - Acquire a developer license
Acquiring a developer license requires user interaction.  Please rerun the script without the -Force parameter.
```

The [previous install script](https://github.com/felixse/FluentTerminal/blob/0.7.0.0/Install.ps1) worked great, also it supported downgrades out of the box, which does not seem to be the case for the new script, since `Add-AppxPackage` calls (in `Add-AppDevPackage.ps1`) do not have the `-ForceUpdateFromAnyVersion` flag (remember PR #535 ?).

Since we're talking about installation, I have a question regarding App Sideloading. I noticed you added what looks like a valid certificate to the zip file along version 0.7.1.0, do we still have to enable sideloading to install the app manually?

Thanks again for your great work, keep it up!

**Comment by felixse** [comment]
Yes, side loading should no longer be necessary due to the trusted code signing certificate. I added the default install script since the AppInstaller seems to ignore dependencies. In most cases you should be able to successfully install it by double clicking the appxbundle. I will try to remove the side loading from the install script for the next version

**Comment by MarkusFraKS** [comment]
Using the appxbundle is no option on Windows Server 2016 since there is no Windows Installer or easy access to the Microsoft Store. Thus we wanted to use the script which fails and causes scoop and chocolatey to fail, too.

**Comment by TPXP** [comment]
That's an interesting point, since WS 2016 [seems to have have support for the UWP platform](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/4d7ad6f4-24ea-4a1c-af76-690105674643/can-uwp-app-be-able-to-run-on-windows-server-2012-r2), it should be able to run Fluent Terminal. If you find a way around this issue (manual install perhaps?), I'll gladly update the Chocolatey package to use it!
