### ISSUE TITLE
Absolutely LOVE this app!

### ISSUE THREAD

**Issue by washicjr** [felixse/FluentTerminal#771]
A couple of feature request

1. The application isn't portable, which is okay. Having it in the Windows store has its benefits. However,  in lieu of it being portable, for a person that has multiple computers it would be nice if one could export my entire configuration. Or have it such that the configuration is read from a user definable location. Like a OneDrive sync location.. Just a thought.

2. It would be nice to be able to either get rid of the border entirely or have the color user definable so that it matches the theme that's in use by the profile

3. Instead of defaulting to 100% opacity when the application is not in focus it would be nice to have that user configurable. It would be nice if it could it to almost disappear when not in focus but not have to minimize the application just in case you need to monitor a long running script or something.

Thanks for this AWESOME terminal. I've tried Hyper, Terminus, Extraterm, and a few others before settling on this. It's ABSOLUTELY the best one of the bunch.

**Comment by skipmeister123** [comment]
> The application isn't portable, which is okay. Having it in the Windows 
> store has its benefits. However, in lieu of it being portable, for a person 
> that has multiple computers it would be nice if one could export my entire 
> configuration. Or have it such that the configuration is read from a user 
> definable location. Like a OneDrive sync location.. Just a thought.
These settings should be stored in your roaming profile.  I know that my 
settings sync. Make sure you're signed into the same Microsoft account on 
each machine.
> It would be nice to be able to either get rid of the border entirely or 
> have the color user definable so that it matches the theme that's in use by 
> the profile
Felix probably knows more about this, but I believe that's a Windows 
setting - it takes on your Windows highlighting color. I think?
> Instead of defaulting to 100% opacity when the application is not in focus 
> it would be nice to have that user configurable. It would be nice if it 
> could it to almost disappear when not in focus but not have to minimize the 
> application just in case you need to monitor a long running script or 
> something.
This might also be a limitation of Windows. Personally, I'd like to see it 
have the acrylic property applied when not in focus.
> Thanks for this AWESOME terminal. I've tried Hyper, Terminus, Extraterm, 
> and a few others before settling on this. It's ABSOLUTELY the best one of 
> the bunch.
It's really been a team effort. 🥰

**Comment by washicjr** [comment]
Yes, it does take on the Windows background by default. I do use Dopamine for my music player and its user configurable there. Not the biggest deal either way.

On the opacity when not in focus. Have you looked at ConsoleZ? It's a Github project that I used it years ago. It's pretty old but you were able to have different settings for opacity depending on focos. https://github.com/cbucher/console (https://link.getmailspring.com/link/CB6BD6FA-A149-44F5-83A5-45AF831A5870@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fcbucher%2Fconsole&recipient=cmVwbHkrQUcyVEdZSldQNkZKU0lLQzVHQ0lBRjU0M1FVTDdFVkJOSEhDS1hLMjRBQHJlcGx5LmdpdGh1Yi5jb20%3D)
Like I said... Just love this console...
Clarence Washington Jr.

**Comment by plastikfan** [comment]
> 
> The application isn't portable, which is okay. Having it in the Windows store has its benefits. However, in lieu of it being portable, for a person that has multiple computers it would be nice if one could export my entire configuration. Or have it such that the configuration is read from a user definable location. Like a OneDrive sync location. Just a thought.
> These settings should be stored in your roaming profile. I know that my settings sync. Make sure you're signed into the same Microsoft account on each machine.

Just to add my 2 pence worth, I too would like to see more portable settings as I frequently peform fresh installs of windows and have multiple local accounts (not linked to a microsoft account). I took a look at my roaming profile and I couldnt see where the config was. It would be great if there was a simply way to export and import the config settings, so I could easily apply one setup to multiple accounts. However, I did find a config.json file in my local profile at: 'C:\Users\Plastikfan\AppData\Local\Packages\53621FSApps.FluentTerminal_87x1pks76srcp\LocalState\config.json'. If I copy this file to a new account will this work, or is there anything in the config, which is user specific and break the app? The only thing that I can see that would need to be changed is the "LogDirectoryPath". Thanks.

**Comment by felixse** [comment]
> A couple of feature request
> 
> 1. The application isn't portable, which is okay. Having it in the Windows store has its benefits. However,  in lieu of it being portable, for a person that has multiple computers it would be nice if one could export my entire configuration. Or have it such that the configuration is read from a user definable location. Like a OneDrive sync location.. Just a thought.

With 0.7.1.0 the import and export settings CLI works a bit more user friendly since you no longer need to access the LocalState directory. the config.json is now exported to the pwd, and import accepts a path for the config.json. So it should be relatively easy to script this.

> 2. It would be nice to be able to either get rid of the border entirely or have the color user definable so that it matches the theme that's in use by the profile

This comes from the UWP AppWindow, so nothing we can influence with the current API. But if you update to a more recent Windows 10 version the colored border is no longer present (don't know exactly in which update the removed it).

> 3. Instead of defaulting to 100% opacity when the application is not in focus it would be nice to have that user configurable. It would be nice if it could it to almost disappear when not in focus but not have to minimize the application just in case you need to monitor a long running script or something.

Notepads found a way to achieve this, so this might be not too far away

> Thanks for this AWESOME terminal. I've tried Hyper, Terminus, Extraterm, and a few others before settling on this. It's ABSOLUTELY the best one of the bunch.

Thanks for the kind words 😃

**Comment by washicjr** [comment]
Thanks for the info! Where can I fin a CLI reference?

Sent from my mobile device. Please excuse the brevity, any typos, or any misspellings that may be found in this message.

Thank you.
________________________________

**Comment by plastikfan** [comment]
> 
> With 0.7.1.0 the import and export settings CLI works a bit more user friendly since you no longer need to access the LocalState directory. the config.json is now exported to the pwd, and import accepts a path for the config.json. So it should be relatively easy to script this.
> 
 @felixse Please can you tell me where the Import/Export is. The only import/export I can see is with the themes which is only looking for .itermcolor, .flutecolor files and not the config.json file that you speak of, thanks.

**Comment by felixse** [comment]
It's a command line interface, not something in the settings window. Have a look [here](https://github.com/felixse/FluentTerminal/wiki/Command-Line-Arguments#settings)

**Comment by plastikfan** [comment]
Ah great, thanks
