### ISSUE TITLE
Enabled area for dragging the window is very limited 

### ISSUE THREAD

**Issue by paulovila** [felixse/FluentTerminal#780]
The drag behaviour for moving around the window should be the area were there are no tabs in the _TabBar_ area. 
At the moment, just a small portion of the _TabBar_ area is allowed to drag the window.
You should be able to  drag the window between the _New Tab_ button (```+```)  and the minimise window button.

**Comment by felixse** [comment]
That's actually how it should behave (and also does on my machines). Can you give some more information, like which version of Fluent Terminal and which Windows 10 update you are using?

**Comment by paulovila** [comment]
I notice that it works ok in my personal PCs, but in my office, where it's behaving like I mentioned, is Windows 10, but not the latest (I can't tell at the moment), the Fluent Terminal Version is 0.7.1.0. I think it has something to do with the fact that I installed **Powershell Core**.
First I added a new profile:
. Shell executable location: ```c:\Program Files\PowerShell\7\pwsh.exe```
. Working directory: ```c:\Repos```
. Theme: ```Xterm.js Default```

Then I installed the following modules:
 ```powershell
Install-Module posh-git -Scope CurrentUser
Install-Module oh-my-posh -Scope CurrentUser
Install-Module -Name PSReadLine -Scope CurrentUser -Force -SkipPublisherCheck
```
And then in the start-up ```$Profile``` as follows:
```powershell
Import-Module posh-git
Import-Module oh-my-posh
Set-Theme Paradox
```
Also changed the font to ```MesloLGM NF``` which I installed from Nerdfonts.com

**Comment by paulovila** [comment]
I couldn't reproduce it today in the office after the PC restarted, It may have been something transient, which makes it more mysterious, it's like if that unresponsive area were still holding the space of a tab that was previously there, as if those previous tabs didn't close properly...
