### ISSUE TITLE
List of ssh connections

### ISSUE THREAD

**Issue by Mystic8b** [felixse/FluentTerminal#783]
Greetings!
Please add the ability to open a list of connections, now as far as I understand it is possible to open a saved ssh connection only using hot keys?
Maybe there is already a similar issue, but I did not find it.

**Comment by felixse** [comment]
You can use Quick launch (Ctrl+Alt+T) by default. If you start typing the profile name it will suggest matching profiles

**Comment by Mystic8b** [comment]
I understand, but it's still not as convenient as if there was a complete list
Just as an idea, if you think this is not necessary - it’s sad, but what can you do.

**Comment by tomhundt** [comment]
Aha.  Thanks for explaining.  I will start using that.

In terms of UI design, I think of things like "Choose from this list of profiles" as a "typical user" (or "new user") feature, and things like "Start typing and it will autocomplete" as a power user one.  For example, look at the Start menu.  

Besides, sometimes one can't remember the name of a profile... or it's simply quicker to point and click than to type:  What if you have `production1` through `production20`...? By the time you hit the arrow key a million times to get to the one you want, you could have clicked it on a list a lot faster.  (And yes, I know if you typed `prod` and then went to the mouse you could still click it... but that defeats the purpose of not making the user have to switch back and forth.)

**Bonus:** If you display a list of profiles to choose from, it gives you the opportunity to display the associated shortcuts for them. ;-)

**Comment by felixse** [comment]
Next version will list all profiles in the new tab/window menu
