### ISSUE TITLE
Mouse doesn't work

### ISSUE THREAD

**Issue by Mystic8b** [felixse/FluentTerminal#785]
After a day of customization for myself, I got a really big problem - the mouse does not work in the midnight commander (and mcedit). I can’t scroll with the mouse, set the cursor, click on buttons like file, etc.
Please guys, this is very important.

**Comment by maxhora** [comment]
it is a known issue. As I know so far, a lot internals and externals like - ConPty, WinPty, ConHost, OpenSSH are not ready to support mouse events sequences.

**Comment by Mystic8b** [comment]
Disabling ConPty did nothing. Maybe there are some workarounds? I spent about an hour on google and found nothing. This is really a huge problem ((

**Comment by felixse** [comment]
There is no workaround available as far as I know. As Max said this is due to some limitations of the components we use.

Let's continue discussing this in #50

**Comment by Mystic8b** [comment]
But it's closed there)
The windows terminal used to have the same problem, but they somehow circumvented this ...
But okay, I think if it becomes possible, you will do it. Good luck to you.
