### ISSUE TITLE
Add option to limit tab width

### ISSUE THREAD

**Issue by vincentfiestada** [felixse/FluentTerminal#79]
When using WSL, the tab title becomes the currently running program and the directory. In many cases, this can cause the tab to become too wide and make navigating between multiple tabs unruly.

![image](https://user-images.githubusercontent.com/5321175/45593554-908d4380-b9bb-11e8-9a4b-dcbbc48f8956.png)

It would be really helpful to be able to set a maximum tab width. (This may also be a duplicate of #44 as, presumably, Edge-like tabs would address this issue)

**Comment by skipmeister123** [comment]
I solved this problem by limiting it in my .zshrc, but I agree that 
limiting the tab width is more ideal (especially since my solution also 
limits the window title width.)
--
Hans Kokx

**Comment by felixse** [comment]
Yes, good idea. We just need to set some max width and add a tooltip that contains the full title

**Comment by felixse** [comment]
The titlebar will continue to display the full text, but I don't think I can display different texts for title and tab, since xterm.js is only providing the one we are displaying right now. Do you have some additional info on this?

**Comment by skipmeister123** [comment]
https://superuser.com/questions/292652/change-iterm2-window-and-tab-titles-in-zsh
--
Hans Kokx
