### ISSUE TITLE
Ctrl+D hotkey

### ISSUE THREAD

**Issue by Mystic8b** [felixse/FluentTerminal#793]
I did not find a way to remove this hotkey (now it does disconnect). This is EOF on linux, so you definitely need to remove it.

**Comment by felixse** [comment]
This is nothing Fluent Terminal does, maybe this discussion might help you: https://unix.stackexchange.com/questions/110240/why-does-ctrl-d-eof-exit-the-shell

**Comment by Mystic8b** [comment]
In fluent terminal, this combination closes the connection (closes the tab / window)! Why did you close issue?

**Comment by felixse** [comment]
This is something your shell does. Fluent Terminal is just closing the tab or window because it's process returned. Have a look at the discussion I posted to find out why this might happen.

**Comment by Mystic8b** [comment]
oh sorry :D ty
