### ISSUE TITLE
Grave not working on German keyboard

### ISSUE THREAD

**Issue by HiImJulien** [felixse/FluentTerminal#794]
Hey there!

I use Fluent + WSL + Vim. Recently I discovered, that I cannot use the characters **`** and **´**.
Instead, I am greeted with an **Ý**.

This affects all profiles, being it WSL, Powershell, or CMD. This does not happen, when I use the default terminals (i.e. cmd.exe etc.).

**Comment by felixse** [comment]
Just tried it  but got ý in cmd.exe and Windows Terminal as well (when using the default German layout).
I'm using https://github.com/RAnders00/Deutsch-ohne-Tottasten to avoid these problems across all programs
