### ISSUE TITLE
Error: CreateProcess failed

### ISSUE THREAD

**Issue by naefl** [felixse/FluentTerminal#8]
Big Kudos for this project, so much faster and more beautiful than all other options. I'd love to help, although this goes beyond my dev skills. But I'll spread the word!

![image](https://user-images.githubusercontent.com/26996526/36207191-56510266-1195-11e8-8b76-a94505b21fc1.png)

This happened when trying to open it for the second time. Opening for the first time was flawless.

Huawei Matebook X i5 17093 insider, if that helps.

**Comment by felixse** [comment]
Hi,

did you maybe select 'custom' shell in the settings?

**Comment by naefl** [comment]
Yes. That was the mistake. Thanks &  Sorry for that!

**Comment by felixse** [comment]
No problem. I will try to make this error message a bit more helpful with the next release.
