### ISSUE TITLE
Ctrl-H does not send ^H, deletes single character instead.

### ISSUE THREAD

**Issue by Naomarik** [felixse/FluentTerminal#80]
I use CTRL-H to move left in tmux. If the current behavior is intended, anyway to set an option to toggle it?

**Comment by felixse** [comment]
[Apparently this intended by xterm.js ](https://github.com/xtermjs/xterm.js/blob/290c95ad71f8b1264139a7ed6f070c4741a8987e/src/InputHandler.ts#L512)

I don't think there is anything we can do about that from our side, maybe you want to open an issue at xterm.js?
