### ISSUE TITLE
Acrylic background doesn't work

### ISSUE THREAD

**Issue by takase1121** [felixse/FluentTerminal#801]
My settings:
![image](https://user-images.githubusercontent.com/20792268/84888538-014e1c00-b0ca-11ea-96f6-5fef281d68d3.png)
 
But acrylic doesn't seem to work:
![image](https://user-images.githubusercontent.com/20792268/84888588-12972880-b0ca-11ea-9c4a-4abdf7103b1e.png)

Fluent terminal v0.7.1.0
Windows 10 version 2004

**Comment by skipmeister123** [comment]
Do you have transparency enabled in the control panel?

**Comment by takase1121** [comment]
Oh... So I need to enable it. I disabled it. Now that it worked, is it possible to still get acrylic without enabling global transparency?

**Comment by skipmeister123** [comment]
Nope

**Comment by takase1121** [comment]
that's sad... With transparency effects on my taskbar looks like it has been drenched in water but at the same time I love the acrylic effect on the terminal. Anyways, closing this issue

**Comment by skipmeister123** [comment]
I use TaskbarX which has some options to change the background of the 
taskbar. I like the acrylic look, so I can't remember if it gives you an 
option to go solid, but I know it can do transparent... Maybe look and see 
if that will solve your issue? https://chrisandriessen.nl/taskbarx

**Comment by takase1121** [comment]
Sadly it doesn't solve my issue, but thanks to you now I have another cool piece of software. Thanks!

**Comment by takase1121** [comment]
Thank you @f00fcat, your suggestion works the best for me, I especially like the clear settings with a bit of tint
