### ISSUE TITLE
Improper line rendering while printing frequently appending outputs

### ISSUE THREAD

**Issue by xlm13x** [felixse/FluentTerminal#804]
While printing long files or tail of logs if the text prints too fast it is not able to render it properly. Lines are breaking unexpectedly and also the rendering seems choppy.

**Comment by skipmeister123** [comment]
Disable smart buffer and try again

**Comment by xlm13x** [comment]
Seems like smart buffer was the culprit, just noticed it was removed in the latest build. Closing the issue.
