### ISSUE TITLE
Windows showing media controls in taskbar popup.

### ISSUE THREAD

**Issue by xlm13x** [felixse/FluentTerminal#805]
![image](https://user-images.githubusercontent.com/1693053/85499162-b61e9680-b5fe-11ea-9543-c6546eeee886.png)

Not sure if this is something related to flute or my system has gone nuts.

**Comment by skipmeister123** [comment]
🤔 have you tried tapping any of those buttons? I wonder if the next button 
will cause your long running processes to finish sooner 😅

**Comment by xlm13x** [comment]
Unfortunately buttons are disabled :(

**Comment by skipmeister123** [comment]
Bummer! I was hoping it worked like a TURBO button or something! 🤣

For what it's worth, I have the buttons too.  No idea when that happened.

**Comment by skipmeister123** [comment]
You know what? I think it's a Windows issue.  Even my LastPass app has the media buttons. EVERYTHING has them.

**Comment by xlm13x** [comment]
I also doubted that but except flute, I am not able to see such media controls for any other app.

**Comment by skipmeister123** [comment]
After rebooting my computer, I don't see it for other apps anymore.  It's still there for FT.

**Comment by felixse** [comment]
Don't know what's going on here, but if Windows decides we need media buttons I won't argue 😀 

Probably just a Windows bug
