### ISSUE TITLE
Can I load fluent Terminal in mobaxterm? 

### ISSUE THREAD

**Issue by patelvi1** [felixse/FluentTerminal#810]
i am using licensed Mobaxterm and would like to use fluent terminal with it. Is it possible to use?

**Comment by felixse** [comment]
Fluent Terminal as well as mobaxterm are terminals, so those cannot load each other. If you want to have your shell in Mobaxterm to look like the screenshot in the readme have a look [here](https://github.com/felixse/FluentTerminal/wiki/FAQ#how-can-i-achieve-the-look-of-the-terminal-in-the-readme)
