### ISSUE TITLE
Integration with VS Native Command Prompt

### ISSUE THREAD

**Issue by aillynesc** [felixse/FluentTerminal#818]
I'm trying to attach the VS Native Command Prompt (Developer Command Prompt) as a shell executable location. I select the right VS Command Prompt but instead the C:\Windows\System32\cmd.exe is attached. Is there a way to use the VS command prompt, or the Fluent Terminal needs an integration for that?. 
Thank you.

**Comment by felixse** [comment]
You need to create a profile with `C:\Windows\System32\cmd.exe` as shell executable and the following arguments: `%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"`

**Comment by aillynesc** [comment]
Thank you. It works!!
