### ISSUE TITLE
PATH not appearing to work in Powershell, or CMD windows

### ISSUE THREAD

**Issue by ChristianVaughn** [felixse/FluentTerminal#834]
Recently installed nodeJS and npm, and I get this issue which usually happens when something isnt in the PATH
`npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
I am able to open a cmd or powershell window outside of FluentTerminal and use commands added to the PATH, but nothing added to my PATH is working in the FluentTerminal.

**Comment by skipmeister123** [comment]
The PATH (and other environment variables) are not updated until the tray process is exited.  You might be able to use `refreshenv` to force it, but ymmv.

**Comment by ChristianVaughn** [comment]
Ahh forgot about the tray process. Thanks for the answer, and sorry for the silly issue.
