### ISSUE TITLE
This is not an issue but I just want to ask or request for a better way to create a new tab.

### ISSUE THREAD

**Issue by BroJenuel** [felixse/FluentTerminal#843]
I want to request a feature that when making a new tab, atleast show choices of what profile to use. Thanks I hope this will come true, This will be very usefull.

**Comment by skipmeister123** [comment]
This is old behavior which was removed. Personally, I would advocate for 
the old behavior again.

**Comment by MisterJ936** [comment]
is Windows Terminal a new version of fluent terminal?

**Comment by felixse** [comment]
> This is old behavior which was removed. Personally, I would advocate for the old behavior again.

I will provide something similar with the next version

> is Windows Terminal a new version of fluent terminal?

No, they are 2 independent projects

**Comment by washicjr** [comment]
> I want to request a feature that when making a new tab, atleast show choices of what profile to use. Thanks I hope this will come true, This will be very usefull.

I could not agree more. It would be REALLY nice to have a way to choose from a list of all your configured profiles.

**Comment by felixse** [comment]
Next version will list all profiles in the new tab/window menu
