### ISSUE TITLE
[Question][Enhancement] Changed Background Color Based on Branch

### ISSUE THREAD

**Issue by daugaard47** [felixse/FluentTerminal#849]
I'm constantly switching between branches during the day. It would be nice to have a visual to represent what branch I'm on based on color to prevent pushing to the incorrect branch

I was wondering if there is a way to change the background color of my terminal based on the name of my branch?

**Example:**

1. Master branch = red background
2. develop branch = green
3. etc..

I'm using Powershell as my main profile and a cutom theme
![terminal](https://user-images.githubusercontent.com/3165203/94944725-a89f6500-04a7-11eb-8a25-ae735e6c77d1.jpg)
.

**Comment by skipmeister123** [comment]
I think that's something you'll have to do for yourself. It will require 
some logic changes to whatever script is rendering your prompt.
