### ISSUE TITLE
Is there a way to switch Admin/root on windows switch terminal permission "run as administrator"

### ISSUE THREAD

**Issue by antoinebou13** [felixse/FluentTerminal#853]
Love the app if there a way to switch permission to administrator it's would be nice like a shortcut.

**Comment by skipmeister123** [comment]
This question has been asked a few times before. Search around in the 
issues, and you'll find where I left instructions.

**Comment by felixse** [comment]
Please refer to https://github.com/felixse/FluentTerminal/issues/6 for some workarounds.
