### ISSUE TITLE
Acrylic background does not work.

### ISSUE THREAD

**Issue by Forgoys** [felixse/FluentTerminal#855]
I turn the "Use acrylic background" on:
![Snipaste_2020-10-15_11-56-35](https://user-images.githubusercontent.com/47031885/96075442-9973da80-0edd-11eb-9839-2df9fa3bc363.png)
But it does not work:
![Snipaste_2020-10-15_11-57-57](https://user-images.githubusercontent.com/47031885/96075485-b3adb880-0edd-11eb-9764-829b1b12e36c.png)

**Comment by felixse** [comment]
do you have transparency enabled in the windows settings?

**Comment by TiziG** [comment]
Had the same issue right after installing the App. Restarting Windows solved it for me.

**Comment by Forgoys** [comment]
The problem has been solved. If you use the battery and in energy-saving mode, the system will automatically turn off the acque effect. Turning off the energy-saving mode can solve the problem.
