### ISSUE TITLE
[Feature Request] X11 Support in SSH

### ISSUE THREAD

**Issue by qrqiuren** [felixse/FluentTerminal#858]
Hi developers,

Fluent Terminal is the most impressive SSH client running on Windows I used so far. I hope it can add X11 support in SSH. Sometimes I need some GUI tools to check the remote computer or have to run CAD tools in the remote server. If the Fluent Terminal has such a function, it would be much helpful.

**Comment by skipmeister123** [comment]
Probably not going to happen, because it doesn't need to.

Personally, I run Vcxsrv and enable X11 forwarding.  I have no problems 
running gui apps.

**Comment by qrqiuren** [comment]
> 
> Probably not going to happen, because it doesn't need to. Personally, I run Vcxsrv and enable X11 forwarding. I have no problems running gui apps.

Thank you. How can I enable X11 forwarding? I am running an X server, but X11 seems not work in Fluent Terminal. Should I make some settings?

**Comment by skipmeister123** [comment]
https://www.ssh.com/ssh/config/#enabling-x11-forwarding-and-agent-forwarding
