### ISSUE TITLE
FluentTerminal won't work on global variable.

### ISSUE THREAD

**Issue by iftkharhussain** [felixse/FluentTerminal#861]
I have just install FluentTerminal on window 10, it works fine as CMD but when i am trying to run my node project form it, it shows npm is undefined (npm is global variable)
i have tried to add another powershell 7 with new profile but same it does not work.

System info:
window 10Pro N 64bit (build 18362)
FluentTerminal version: 0.7.2.0

**Comment by iftkharhussain** [comment]
it works fine now, some hours ago it leads to error, may be it takes time to fetch the global variables.

**Comment by hanskokx** [comment]
You would need to kill the tray process to refresh the variables.

**Comment by iftkharhussain** [comment]
It works now, may be system restart was needed. Thanks you for your immediate response. 👍
