### ISSUE TITLE
[BUG] Fails to detect recently installed commands

### ISSUE THREAD

**Issue by angelhdz** [felixse/FluentTerminal#863]
Thanks for this elegant, modern and fluent app, but had my first issue.

I just installed Chocolatey. Closed all my FluentTerminal windows. Opened a new one. Can't find **choco** command, but when I open the CMD, it finds it.

Hope there is a fix. Thank you again!

![image](https://user-images.githubusercontent.com/10191085/98310666-f544f700-1fa3-11eb-88e0-de1be4e8dbcf.png)

**Comment by hanskokx** [comment]
You have to kill the tray process to refresh the variables. You could also 
try `refreshenv`, but I'm not 100% sure that works.
