### ISSUE TITLE
[BUG?] Black Window On Inactive/Focus Out

### ISSUE THREAD

**Issue by angelhdz** [felixse/FluentTerminal#864]
I have my window in a nice transparent color, but when the window loses focus, it turns all black. 
Can this be modified in the settings or is it a bug?

Thanks!

**Focus**
![image](https://user-images.githubusercontent.com/10191085/98312039-38ed3000-1fa7-11eb-8892-08b2f16ccee3.png)

**No Focus**

![image](https://user-images.githubusercontent.com/10191085/98312060-44405b80-1fa7-11eb-89a6-3e48d83ff745.png)

**Comment by hanskokx** [comment]
Sadly, it's a Windows thing.

**Comment by felixse** [comment]
duplicate of #30
