### ISSUE TITLE
How can i set my FluentTerminal like the screenshots in readme ?

### ISSUE THREAD

**Issue by Brannua** [felixse/FluentTerminal#866]
How can i set my FluentTerminal like the screenshots in readme ?

**Comment by hanskokx** [comment]
That info is available in the wiki, I do believe.

**Comment by felixse** [comment]
https://github.com/felixse/FluentTerminal/wiki/FAQ#how-can-i-achieve-the-look-of-the-terminal-in-the-readme

**Comment by altimmons** [comment]
its ZSH, Oh-my-zsh, Powerline, and Posh-Git.  
I also like to add Powerline10k / Powerline 9k, and NerdFonts (Though Powerline Fonts is the official)
Or some combination of the above.

**Comment by altimmons** [comment]
Assuming this is the same as Windows Terminal Preview- and I am not clear the differences yet -these are good sources

https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup
https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/powerline-in-powershell
https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/custom-schemes

https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/raspberry-ubuntu
https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/frosted-glass-theme
and my personal favorite:
https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/retro-command-prompt

I added a picture from Fallout I think of a retro phosphor monitor and it looks great. Colored output suffers though.

See also: 
https://github.com/ryanoasis/nerd-fonts

**Comment by hanskokx** [comment]
@felixse That retro theme makes me wonder why I got LASIK to begin with 🤣
