### ISSUE TITLE
Clarification of Purpose and Features

### ISSUE THREAD

**Issue by altimmons** [felixse/FluentTerminal#868]
This looks like a fork of Windows Terminal Preview.

Can you clarify on your intro page the salient differences or a statement of purpose (its to try out new ideas, its a subset of features, etc.) Maybe this is your personal repo and Windows Terminal is the work repo.

That would help me feel better this is a genuine Open Source Project and desire to try it out.  Otherwise, it seems to me to stick to what I see as the main branch.  

If it weren't for the 50 contributors, I would feel pretty certain this is malware or something.

**Comment by hanskokx** [comment]
I'll let Felix speak to this, but as a contributor, allow me to say: this 
project existed long before Windows Terminal was announced. 😊

**Comment by felixse** [comment]
As Hans said, this is predating Windows Terminal. I would say the biggest differences right now are A settings UI and builtin support for mosh
