### ISSUE TITLE
App crash when open setting the second time

### ISSUE THREAD

**Issue by ginkcode** [felixse/FluentTerminal#874]
Fluent Terminal always crash when open Setting windows the second time.

Version: 0.7.4.0
OS: Windows 10 20H2 19042.630

**Comment by mikabogumil** [comment]
Having same issue. Tried to reinstall / clear app data and it's still crashing.

**Comment by zhubanRuban** [comment]
Same here.
Steps to reproduce:
- launch the app
- open settings
- close settings
- open settings again - the app crashes

Version: 0.7.4.0
OS: Windows 10 20H2 19042.630

**Comment by zjxs1997** [comment]
same issue here.

**Comment by DoggoKt** [comment]
Can reproduce as well on the latest version.

**Comment by felixse** [comment]
Caused by https://github.com/microsoft/microsoft-ui-xaml/issues/3822
Downgrading to 2.4.3 mitigates this, I will publish an updated version soon

**Comment by valeriodigregorio** [comment]
Same issue, please release a new version, I lose every time the progress in my local and ssh remote shells

**Comment by felixse** [comment]
Update is released, should be processed by the Store within a few hours
