### ISSUE TITLE
Quick Launch profile

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#88]
I would like to be able to right click on the FT icon in my task bar, and choose to launch a specific profile.  Sometimes, I want to launch PowerShell over my default WSL.  To do that today, I need to launch FT with WSL, then Ctrl+Shift+T, choose the profile, and then Start.  This process could be streamlined to: Right click on FT icon, choose profile to launch a new instance with.

**Comment by Riebart** [comment]
This would be nice, using jump lists and the right-click options. This is likely linked to (and bound by) #87 and #81 is my guess.

**Comment by felixse** [comment]
Actually this is pretty easy to implement, UWP has a nice and easy API for the jumplist

**Comment by hrzafer** [comment]
> I would like to be able to right click on the FT icon in my task bar, and choose to launch a specific profile. Sometimes, I want to launch PowerShell over my default WSL. To do that today, I need to launch FT with WSL, then Ctrl+Shift+T, choose the profile, and then Start. This process could be streamlined to: Right click on FT icon, choose profile to launch a new instance with.

It would be nice if we were able to do this even not reaching the mouse. I think in a terminal environment ideally we should be able to do this kind of stuff with keyboard shortcuts.

**Comment by felixse** [comment]
Do you have any idea in mind? I don't think we should register too much global hotkeys. Maybe some kind of selection window?

**Comment by felixse** [comment]
This is resolved by the new quick launch feature
