### ISSUE TITLE
Feature-requests

### ISSUE THREAD

**Issue by ad-on-is** [felixse/FluentTerminal#89]
Wow... great app! Exact something I was looking for, when I switched from macOS where I used to have iTerm2 installed.

I already switched from conemu to FluentTerminal ;-)

There were some nifty features in iTerm2, that are really useful.

- Toggle shortcut for showing/hiding app
- Split-Tab, add a new tab at the left/right of the current tab
- Fixed window positioning and show on top of other apps, like, full-width-top, full-width-bottom, full-height-left, full-height-right

**Comment by samlehman617** [comment]
> Toggle shortcut for showing/hiding app

I'd really like this to have dropdown terminal functionality.  The option to have a hidden terminal (separate from the windowed terminals) is killer.  

I'd be willing to make a PR, but I know close to nothing about developing UWPs and this specific project structure.

**Comment by felixse** [comment]
> * Toggle shortcut for showing/hiding app

There is a keyboard shortcut (default: scroll lock) to show/hide the window. This will also spawn a new one if there is none (just the system tray needs to be running)

> * Split-Tab, add a new tab at the left/right of the current tab

This planned sometime in the future

> * Fixed window positioning and show on top of other apps, like, full-width-top, full-width-bottom, full-height-left, full-height-right

I don't know about the sizing and positioning yet, but at least for 'always on top' there is an [API we could use](https://blogs.msdn.microsoft.com/universal-windows-app-model/2017/02/11/compactoverlay-mode-aka-picture-in-picture/)

**Comment by ad-on-is** [comment]
Aaaaaah... sorry, I didn't see that toggle shortcut already exists... 
GREAT!!!! well, you my friend, made a developer very happy now ;-)

**Comment by sne11ius** [comment]
> A what? -- Hans Kokx

 Sorry, my bad - I mistyped "guake" :)
I meant "guake"-style, like in "full width", "always on top", "moving in/out from/to top of screen". See

- http://guake-project.org/
- http://cmder.net/

**Comment by skipmeister123** [comment]
Oh, yeah. I'm familiar with that 😅
--
Hans Kokx

**Comment by ad-on-is** [comment]
Prior to FT i used cmder, which was very buggy with the full-width settings and my dual monitor setup. Now, I position FT where I want it, and have a toggle-keybind set to ALT + < (german keyboard). So it's basically always at my fingertips 😉

**Comment by Riebart** [comment]
I think the typical name for this is "Quake-style", since it mimics the top-down terminal as used in Quake, and most other FPS video games since then.

**Comment by cicorias** [comment]
not sure if i'm missing it, but having a scroll back buffer would be great. that's really my only thing that i've yet to see as a significant gap.   Like in CMD properties. 

![image](https://user-images.githubusercontent.com/1080406/50731153-b174d280-112b-11e9-843b-3f07d433f826.png)

**Comment by Sharlaan** [comment]
+1 for Quake-style
+1 for split panes (FT is currently v 0.3.1 while roadmap states for 0.2.3 ?)

Also maybe i've missed something, but i could not find "Scroll lock" button on my laptop keyboard, so maybe a feature request to change the default keybinding to like CTRL + ² (the unused button between ESC and TAB)

Lastly, it would be great to add this awesome argonaut theme as the default for FT ?

**Comment by felixse** [comment]
This is a bit hard to track. Some of this is already implemented or adressed in other issues. If something is missing feel free to create a new issue (please one per feature request/bug)
