### ISSUE TITLE
Can't type tilde (~) in terminal.

### ISSUE THREAD

**Issue by mkprogz** [felixse/FluentTerminal#895]
I can't type tilde **(~)** in terminal. When i press **"SHIFT + ~"** i get "**À**" character. Polish layout keyboard. Every other characters are fine.

**Comment by pbousquets** [comment]
AltGr+4 combination for tilde in Spanish keyboard neither unless I type the 'space' key afterwards.

**Comment by felixse** [comment]
duplicate of #857
