### ISSUE TITLE
Powershell background not transparent on Windows 1809

### ISSUE THREAD

**Issue by JensMertelmeyer** [felixse/FluentTerminal#90]
I don't understand much of how cmd or PowerShell work behind the scenes. This might be related to issue #9 , I am not sure.

On a machine with Windows 1809 (Build 17763.1), PowerShell does not look correct while cmd.exe is ok.
![unbenannt](https://user-images.githubusercontent.com/1827784/46568841-0c8c0300-c94c-11e8-8398-b10a54fa9588.png)

The error output appears to be totally ok while user input and regular output look like they force a certain background colour and refuse to be transparent.

I cannot reproduce this on another machine with Windows 1803. I don't really understand the discussion in issue #9, I think Windows 1809 introduced some changes that might be causing this? How can I provide more information?

**Comment by skipmeister123** [comment]
I'm on 1809 and haven't seen this. Can you export your color scheme and 
post it here for testing? What are your windows settings? Do you have color 
title bars enabled?
--
Hans Kokx

**Comment by felixse** [comment]
No problem, thank you for posting your solution in case someone else has the same problem.
