### ISSUE TITLE
How to install Fluent Terminal without admin rights?

### ISSUE THREAD

**Issue by catcosmicice** [felixse/FluentTerminal#906]
Hi there!

I'm on a machine with no admin rights and I'd really like to try Fluent Terminal out, so is there a way I can install Fluent Terminal without admin rights?

**Edit**: I don't want to install it as a windows store app.

Thanks,
~ [cosmicice](https://github.com/catcosmicice)

**Comment by hanskokx** [comment]
It's available in the Microsoft Store.

**Comment by catcosmicice** [comment]
Sorry, but I've already said that I don't want it installed as a Windows/Microsoft Store App.

**Comment by felixse** [comment]
I'm afraid there is no other way besides the Microsoft Store that doesn't require admin rights.
