### ISSUE TITLE
Ctrl+C in Powershell and CMD profiles doesn't break current line, but does in WSL

### ISSUE THREAD

**Issue by ajruckman** [felixse/FluentTerminal#91]
Normally in Powershell and Command Prompt terminals, pressing `Ctrl+C` breaks what you've typed on the current line and goes to a new line, but this only works in WSL tabs in Fluent Terminal.

What happens in `powershell.exe`: https://i.imgur.com/rBWlAls.png
What happens in WSL tabs in Fluent Terminal: https://i.imgur.com/Dh7VDtG.png
What happens in Powershell tabs in Fluent Terminal: https://i.imgur.com/5hDFY4U.png

Maybe the Copy keybinding is interfering..?

Also, I really love this project. I feel like this is the terminal Windows 10 should have had from the beginning. If you have a PayPal I would love to donate what I can :)

**Comment by felixse** [comment]
Might by related to WinPTY, I expect this to become better once we support ConPTY. Does this cause any problem on your side? Copy keybinding should have no influence on this, it only listens for ctrl+c when something is selected

**Comment by ajruckman** [comment]
Not sure what you are asking, does what cause a problem on my side?

maybe relevant: https://github.com/zeit/hyper/issues/1121, https://github.com/Microsoft/node-pty/issues/216

**Comment by felixse** [comment]
Does the inconsistent line breaking cause any issue for you? From my perspective this is just a bit odd, but nothing that breaks anything 😅

**Comment by ajruckman** [comment]
I am very used to it, when I make a typo early in the line or realize I forgot to do something before what I started typing (like committing before pushing) I just do Ctrl+C and start over. And if it works in the native Windows terminals I think it should work here, right? The Hyper terminal issue I linked above is all about this so I think a lot of other people do it too: https://github.com/zeit/hyper/issues/1121#issuecomment-366262193

Here is a fix supposedly, to be released in WinPTY 0.4.4: https://github.com/rprichard/winpty/commit/c9ce3ad1e347d9535eef5c79927a82c9f8eb5f29

Since a new WinPTY version hasn't been released in over a year, maybe it would be worth it to just use the current code from master?

**Comment by ajruckman** [comment]
I got it working by building winpty from master: https://i.imgur.com/dVJm2PB.png

**Comment by JokerQyou** [comment]
In the latest FluentTerminal (0.4.1.0) this is still an issue. `Ctrl-C` does not break the current line. But by turnning off this option, it starts working again in new terminal windows.

![image](https://user-images.githubusercontent.com/1465267/56482602-9c178e80-64f7-11e9-9690-a351f199f151.png)
