### ISSUE TITLE
Signing

### ISSUE THREAD

**Issue by hanskokx** [felixse/FluentTerminal#920]
"If your software isn't signed, I'm not fking with it." --a coworker.

So, @felixse, I suggested a to a coworker that they ditch the M$ terminal and they said, "I'm not willing to f*ck with the M$ store -- if they're not willing to sign their app, f*k them."

So!

They're on Win10, but not willing to use the app store. They *are* willing to use the releases -- but not if they must install a signing cert.

What options do we have?

**Comment by felixse** [comment]
The releases on GitHub are signed with a Sectigo Code Signing Certificate
