### ISSUE TITLE
Fig

### ISSUE THREAD

**Issue by hanskokx** [felixse/FluentTerminal#921]
This is so pretty! When can we have it too? 🤣

https://github.com/withfig/autocomplete

![68747470733a2f2f6669672e696f2f676966732f64656d6f2d776974682d6865616465722e676966](https://user-images.githubusercontent.com/1911919/119670113-a018e780-be06-11eb-8add-ccd6bbf231d6.gif)

**Comment by felixse** [comment]
would love to try something like this but I don't have the time right now 😦
