### ISSUE TITLE
Is there a command to run terminal with the specify profile?

### ISSUE THREAD

**Issue by shlinux** [felixse/FluentTerminal#923]
Just like "flute.exe -p WSL" to run the terminal with the WSL profile ?

**Comment by felixse** [comment]
Yes,  please refer to: https://github.com/felixse/FluentTerminal/wiki/Command-Line-Arguments#new

**Comment by shlinux** [comment]
Thanks !
Then I can create a cascading context menu now.

`reg add "HKCU\Software\Classes\Directory\ContextMenus\FluentTerminal\shell\CMD\command" /d "\"%LOCALAPPDATA%\Microsoft\WindowsApps\flute.exe\" new \"%%V\" --profile \"CMD\"" /f
reg add "HKCU\Software\Classes\Directory\ContextMenus\FluentTerminal\shell\PowerShell\command" /d "\"%LOCALAPPDATA%\Microsoft\WindowsApps\flute.exe\" new \"%%V\" --profile \"Powershell\"" /f
reg add "HKCU\Software\Classes\Directory\ContextMenus\FluentTerminal\shell\WSL\command" /d "\"%LOCALAPPDATA%\Microsoft\WindowsApps\flute.exe\" new \"%%V\" --profile \"WSL\"" /f
reg add "HKCU\Software\Classes\Directory\shell\Open Fluent Terminal here" /v ExtendedSubCommandsKey /t REG_SZ /d "Directory\\ContextMenus\\FluentTerminal" /f
reg add "HKCU\Software\Classes\Directory\Background\shell\Open Fluent Terminal here" /v ExtendedSubCommandsKey /t REG_SZ /d "Directory\\ContextMenus\\FluentTerminal" /f
reg add "HKCU\Software\Classes\Drive\shell\Open Fluent Terminal here" /v ExtendedSubCommandsKey /t REG_SZ /d "Directory\\ContextMenus\\FluentTerminal" /f
reg add "HKCU\Software\Classes\LibraryFolder\Background\shell\Open Fluent Terminal here" /v ExtendedSubCommandsKey /t REG_SZ /d "Directory\\ContextMenus\\FluentTerminal" /f
`

**Comment by petersenna** [comment]
Is there something similar for an SSH profile? Trying the command line works fine for Powershell, WSL, and CMD, but it does not work for my "fedora" ssh profile.
