### ISSUE TITLE
Fluent Terminal not recognizing scoop commands

### ISSUE THREAD

**Issue by Cyberdroid1** [felixse/FluentTerminal#924]
Today, a few hours back, I installed scoop and sudo. And they worked properly under Fluent Terminal. But when I try to use these commands now in FT, they give an error. But Windows Powershell properly accepts these commands. 

I have not tweaked any profile settings. 

![image](https://user-images.githubusercontent.com/51435948/120600447-68ddb280-c466-11eb-9235-603a47e70e94.png)

Please help me.

Windows 10 1809 LTSC
Fleunt Terminal 0.7.5.0

**Comment by felixse** [comment]
You need to restart Fluent Terminal (Select Exit in the System Tray to completely quit it)

**Comment by Cyberdroid1** [comment]
I had done that.

Well, I am happy to report that after restarting my PC, it seems to work again 😅😂

Thanks!
