### ISSUE TITLE
[Looking for Feedback] Roadmap

### ISSUE THREAD

**Issue by felixse** [felixse/FluentTerminal#93]
Hey All,

I just wanted to share my plan for the near future of Fluent Terminal. As you might have noticed I'm currently busy with another project, but I should be able to commit my full attention to this one very soon again. Please note that nothing here is set in stone, so if you have something you want to have addressed earlier or have some further ideas please share your thoughts 😄 

## 0.2.2.0
* Keybindings to create new terminals with specific profiles (#85)
* Default color scheme for profile (#28)
* Add support for [ConPTY](https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/) (requires 1809)
* Admin rights for powershell/CMD ([Might be tied to 1809](https://stefanwick.com/2018/10/06/app-elevation-samples-part-2/))

## 0.2.3.0
* Refactor multi window to be based on multiple instances (this will raise minium target version to 1803)
* Jumplist support (#88)
* Split panes (#16, #89)
* Broadcast input (#21)

## Unscheduled:
* Support new search APIs of xterm.js
* Localization (#67)
* Always on top windows (#89)
* Built-In SSH support (#39)
* Switch to Azure DevOps CI
* Improve CLI interface of flute.exe to improve interoperability (#87)

**Comment by skipmeister123** [comment]
I'd like to see split panes on the actual roadmap. Do we have a feature 
request for broadcast input? I think that should come along with split 
panes, ideally.
--
Hans Kokx

**Comment by felixse** [comment]
You're right, also added some missing references to the unscheduled items. I think 0.2.3.0 would be a good release for split panes & broadcast, since this one will concentrate on window management.

**Comment by skipmeister123** [comment]
👍
--
Hans Kokx

**Comment by JensMertelmeyer** [comment]
Stupid question:
> Refactor multi window to be based on multiple instances
What purpose does that solve?

**Comment by bhramchari** [comment]
this discussion might be of interest as there were some comments about getting the app into the store and uwp/runfulltrust/conpty etc, maybe useful for putting it on the roadmap 

https://github.com/Microsoft/console/issues/274#issuecomment-427878605

**Comment by JensMertelmeyer** [comment]
Thank you for replying. Can we be sure multi-instances fix #81?

Take note: The following article from Microsoft states that **calculator uses "multi-view"** instead of "multi-instances":
https://blogs.windows.com/buildingapps/2018/02/23/windows-community-standup-discussing-multi-instancing-console-uwps-broader-file-system-access/

PS: OneNote is another good example for "_Switch back to previous desktop, then spawn a new window_"

**Comment by felixse** [comment]
Good point. Just checked this myself, Calculator is multi-view. I would still prefer to implement multi-instance, mainly for stability. But maybe we can fix #81 independent of this.

**Comment by hrzafer** [comment]
Hi,

I think it would be great, if you could prioritize the following tasks.

1- Documentation. 
- There need a little bit more information on why Fluent-Terminal is more preferable over others. Personally, I loved the looks and simplicity.  Besides the looks, it is very easy and intuitive to configure Fluent-Terminal. 
- Better installation documentation. Currently there are 3 ways presented. The first two are problematic, only the last one works smoothly.
- Does it makes use of ConPTY? Above ConPTY support is written under 0.2.2.0 roadmap. We're at 0.3.1.0. Does this release has support for it?
- Simpler versioning. Maybe only major.minor.patch ?

2- Better selection of terminal type. Currently, the only way of starting a terminal other than the default profile is keyboard shortcuts. There is no GUI control for that. It is very easy to forget which `ctrl + alt + number` point to which profile. I tried using letters, `ctrl + alt + c` => cmd, `ctrl + alt + b` => bash, etc. But then I installed conda which brings its own cmd and letter c was already occupied. 

ctrl + shitf + p => type command would be a solution. (VS Code style)

3- Split pane would be good but similar functionality can be achieved by setting `Open new terminals as` to `Windows` and using windows + arrow keys.

**Comment by ericcornelissen** [comment]
Just for you information regarding your second point @hrzafer, the GUI will soon have a button to open a new tab (see #196) for now I recommend you enable the "Always use tabs" option (under Settings `->` General), this adds a GUI element to open a new tab even if you have only a single tab open :wink:

**Comment by hrzafer** [comment]
@ericcornelissen actually, my second concern is better addressed at #88. Since this is terminal, I personally think that any action that we frequently do must be done by keyboard shortcuts. In that regard, I prefer and find more convenient using `ctrl + T` to open a new tab. But this always starts a shell with the default profile. 

Again, I love the looks and simplicity of FT 👍.

**Comment by ericcornelissen** [comment]
> Let me know how I can help with the improvement of the documentation of the project.

I don't believe there is currently any documentation on the available keyboard shortcuts. Although personally I feel like they all have descriptive names and you can just go through them in the settings, you can write something up I guess (perhaps in the Wiki? I believe you can make a new page). Only problem I foresee is that things might change in the future without the docs being updated...
