### ISSUE TITLE
[Feature request] Natural copy/paste

### ISSUE THREAD

**Issue by KaKi87** [felixse/FluentTerminal#932]
Hello,

I would like to suggest implementing a natural copy/paste feature : that consists in allowing to use `Ctrl+C` and `Ctrl+V` without `Shift` to copy/paste when something is selected, while still allowing to use `Ctrl+C` to send `SIGINT` when nothing is selected.

Other terminal emulators do that : https://github.com/cmderdev/cmder, https://github.com/elementary/terminal.

This improvement makes UX much better.

Thanks

**Comment by felixse** [comment]
It actually does exactly that if you change the keybinding to `Ctrl+C`, I should probably document that somewhere

**Comment by KaKi87** [comment]
Indeed, thanks
