### ISSUE TITLE
WSL True Color not working.

### ISSUE THREAD

**Issue by sarahkittyy** [felixse/FluentTerminal#941]
I use this WSL distro: https://github.com/yuk7/ArchWSL

### How to reproduce

* Enable ConPTY
* Open Fluent, use the default powershell profile.
* `wsl`
* Note the colors (true color is working).
* Now exit.
* Open actual powershell
* `flute.exe run wsl`
* Note the colors (true color is not working).

This is an issue because the WSL distro I sent has an option to use fluent terminal as default, and if I use that, and start the distro from the `Arch.exe` executable, true colors break.

Started normally (by typing `wsl`):
![image](https://user-images.githubusercontent.com/31551546/127249023-cb7e0c98-76ba-4b29-8a01-92cfbd43f662.png)

Started indirectly, through `Arch.exe` or through `flute.exe run wsl`
![image](https://user-images.githubusercontent.com/31551546/127249039-113ae837-8845-435d-9651-2c871f674d42.png)

**Comment by felixse** [comment]
check whether ConPty is enabled in Settings/General (last toggle on the page)

**Comment by sarahkittyy** [comment]
> check whether ConPty is enabled in Settings/General (last toggle on the page)

![image](https://user-images.githubusercontent.com/31551546/127384283-0cdd009c-752d-4788-ad46-65adc323c4ee.png)

ConPTY is enabled.

**Comment by hanskokx** [comment]
Try turning it off, Sarah.  ConPTY has been known to cause a bunch of weird issues.

**Comment by felixse** [comment]
true color is only supported for ConPty, so that won't help

**Comment by hanskokx** [comment]
Oh! Good to know - is that in the docs anywhere?

**Comment by felixse** [comment]
I found the problem, it will be fixed in the next release (or if you build it from master)

> Oh! Good to know - is that in the docs anywhere?

Might be worth documenting, you're right.
