### ISSUE TITLE
Cannot build on Windows 11?

### ISSUE THREAD

**Issue by sarahkittyy** [felixse/FluentTerminal#974]
Hi!

I want to compile this from master (Specifically because #941 isn't in any release yet) but it seems to not work on Windows 11.

![image](https://user-images.githubusercontent.com/31551546/139561337-e1eb96f9-f306-417c-a1d4-916579c6a810.png)

Do you know what could be causing this? Let me know what you need me to attach.

Thanks!

**Comment by sarahkittyy** [comment]
Fixed, I just right clicked FluentTerminal.App and built that instead of building the whole solution :)

**Comment by hanskokx** [comment]
Great job, Sarah! Thanks for being so invested in the vision of FT to not 
only file a bug report, but also compile your own copy. I would be proud to 
work with you. 🥰
