### ISSUE TITLE
Add "About" section to settings

### ISSUE THREAD

**Issue by jonaskuske** [felixse/FluentTerminal#98]
I'd like to see a section called "About" (or similar) in the settings, giving you information about the version number, license, etc.
Especially because having the version number directly in the app makes it easier for people submitting an issue to specify which version they are using – without having to jump into `Windows settings → Apps → FluentTerminal → Advanced options`.

**Comment by felixse** [comment]
Good idea, would make this look like a real application 😄

**Comment by ericcornelissen** [comment]
I started [working on this over here](https://github.com/ericcornelissen/FluentTerminal/tree/about). Any suggestions on what I should include besides version number and license? 

My ideas:
- A button to view the release notes (I'd suggest using [the GitHub releases](https://github.com/felixse/FluentTerminal/releases) for now)
- A short text with something like "Created by _felixse_ and [contributors](https://github.com/felixse/FluentTerminal/graphs/contributors)"
- A button to check for updates. Or, for now, a button that takes you to the page with the download for the latest version 😅 

Also @felixse, how should I go about adding a new icon to the font-file for the about tab in the settings view?

**Comment by skipmeister123** [comment]
I think having it check for a new release when you open the about page is 
becoming quite common. "Your version: xxx. Latest version: yyy. Check for 
updates?" Etc
--
Hans Kokx

**Comment by felixse** [comment]
Thanks for looking into this 👍  I'm not quite sure if the settings dialog is the right place for this. Maybe a dialog window in the hamburger menu of the main window? 

Apart from that the content sounds fine. We already have some mechanism to check for new versions on startup, so checking the version should be no big problem.

**Comment by ericcornelissen** [comment]
> Thanks for looking into this 👍 I'm not quite sure if the settings dialog is the right place for this. Maybe a dialog window in the hamburger menu of the main window?

In the end it is up to you, I like the idea of a button in the hamburger menu either way (by that I mean, if we keep an "about" section in the settings, this button would open the settings on that page). I will finish my thing in the settings dialogue as soon as possible (I want to learn writing UWPs anyway...) and after that you can let me know what you want 🙂 


> Apart from that the content sounds fine. We already have some mechanism to check for new versions on startup, so checking the version should be no big problem.

Didn't know that, I'll have look and see if I can get that working 👍

**Comment by ericcornelissen** [comment]
Here is a preview of what I got so far. Comments are welcome. And @felixse, if you don't like it all just say so, I learned a lot regardless 🙂 Personally I'm not a fan of the placing of the "Created by..." text, I would like it to be pushed to the bottom of the window, but I didn't manage to get that working.

Everything you see here is functional (i.e. the links and the `Check for updates` button). The only thing I did not yet get working is a button in the hamburger menu, as I didn't manage to open the window to a particular navigation item just yet 😞 

![preview image](https://user-images.githubusercontent.com/3742559/47271468-6e6e7e80-d582-11e8-8552-a12c70d5e1d0.png)

![preview animation](https://user-images.githubusercontent.com/3742559/47271478-83e3a880-d582-11e8-970e-9645d90bf3c4.gif)

**Comment by skipmeister123** [comment]
🙌
--
Hans Kokx

**Comment by felixse** [comment]
Looks good, as long as we can place it in the hamburger menu I don't really care if its a dialog or a page in settings 😄  I can work on some way of adding it there once you created a PR.

Only thing I would suggest is to put the logo and product name at the top of the page, makes it more in line with other about pages
