### ISSUE TITLE
i wish to show folder name as the title 

### ISSUE THREAD

**Issue by usernamedd** [felixse/FluentTerminal#982]
often i open four or more terminal by explorer context menu , their titles on the title tab appear the same :powershell. i want to distinguish each other and click the right one that target a path of folder. but it is hard.
so why donot show the last section of a path as the title?

**Comment by kikyoulg** [comment]
1111111111111111

**Comment by felixse** [comment]
The terminal does not know the current directory of the shell process. But you can configure your shell to use the as title as explained [here](https://devblogs.microsoft.com/powershell/setting-the-console-title-to-be-your-current-working-directory/)

**Comment by usernamedd** [comment]
> The terminal does not know the current directory of the shell process. But you can configure your shell to use the as title as explained for PowerShell [here](https://devblogs.microsoft.com/powershell/setting-the-console-title-to-be-your-current-working-directory/)
Thx，sure ,I am using Powershell as the defatult terminal .
