### ISSUE TITLE
Upgrade xterm.js to 3.8

### ISSUE THREAD

**Issue by Tyriar** [felixse/FluentTerminal#99]
3.7/3.8 include some performance improvements which should improve responsiveness:

- https://github.com/xtermjs/xterm.js/pull/1622
- https://github.com/xtermjs/xterm.js/pull/1624

**Comment by Riebart** [comment]
This is actually a pretty straight forward operation, and is documented in the commit message on https://github.com/felixse/FluentTerminal/pull/68/commits/70e6dbf92a5628ec46b1c0e083c26056294c0bfb

**Comment by felixse** [comment]
Thanks for reminding us. You guys do a great job with xterm.js, always looking forward to your latest improvements 😃

**Comment by Tyriar** [comment]
@felixse no worries, looking forward to seeing how the release performs with 3.8 😃
